query($urn:String!) {
  chart(urn: $urn) {
    inputFields {
      fields {
        schemaFieldUrn
        schemaField {
          schemaFieldEntity {
            urn
            fieldPath
            documentation {
              documentations {
                documentation
              }
            }
          }
        }
      }
    }
  }
}