"""Recipe configuration for the Qualytics source.

Every field needs a ``Field(description=...)``: DataHub generates its user-facing config
docs straight from these, and a missing one is a review comment upstream.
"""

import difflib
from datetime import datetime, timedelta, timezone

import pydantic
from pydantic import Field, field_validator

from datahub.configuration.common import AllowDenyPattern, HiddenFromDocs
from datahub.configuration.source_common import (
    DatasetSourceConfigMixin,
    EnvConfigMixin,
    PlatformInstanceConfigMixin,
)
from datahub.configuration.time_window_config import (
    BaseTimeWindowConfig,
    BucketDuration,
    RelativeOrAbsoluteDatetime,
)
from datahub.emitter.mce_builder import ALL_ENV_TYPES
from datahub.ingestion.source.qualytics.constants import get_known_data_platforms
from datahub.ingestion.source.state.stale_entity_removal_handler import (
    StatefulStaleMetadataRemovalConfig,
)
from datahub.ingestion.source.state.stateful_ingestion_base import (
    StatefulIngestionConfigBase,
)


def _validate_platform_value(platform: str) -> str:
    """Reject a platform name DataHub has no record of.

    A typo like ``snowflke`` is otherwise invisible: it produces perfectly well-formed
    assertion URNs pointing at a platform no source emits, so the ingestion "succeeds"
    and nothing appears. Failing at config-parse time turns a silent no-op into an
    error message with suggestions.

    Mirrors montecarlo's validator, including its failure mode: the registry is an
    autogenerated artifact that some installs strip, in which case
    ``get_known_data_platforms()`` returns None and validation is skipped rather than
    blocking every run.
    """
    known = get_known_data_platforms()
    if known is None or platform in known:
        return platform

    suggestions = difflib.get_close_matches(platform, sorted(known), n=3)
    hint = f" Did you mean: {', '.join(suggestions)}?" if suggestions else ""
    raise ValueError(
        f"Unknown DataHub platform {platform!r}. It must match the platform name the "
        f"source that catalogued these datasets emits (e.g. snowflake, bigquery, "
        f"postgres, s3).{hint}"
    )


class QualyticsPlatformDetail(EnvConfigMixin, PlatformInstanceConfigMixin):
    """Where a Qualytics datastore's assets live in DataHub.

    Mirrors Monte Carlo's ``MonteCarloPlatformDetail`` (and the same pattern in
    qlik_sense, sigma and trino) so the recipe shape is one an upstream reviewer
    already recognises.
    """

    platform: str = Field(
        description="DataHub platform name for assets in this Qualytics datastore, "
        "e.g. snowflake, bigquery, databricks, redshift, s3. Must match the platform "
        "the warehouse/lake source uses, or the assertions will attach to a dataset "
        "URN that nothing else emits.",
    )
    convert_urns_to_lowercase: bool | None = Field(
        default=None,
        description="Override URN casing for this datastore only. Leave unset to "
        "inherit the top-level convert_urns_to_lowercase, or, if that is unset too, "
        "the default of the DataHub source for this platform. Useful when one "
        "warehouse was ingested with lowercasing on and another without -- a case "
        "mismatch produces a valid URN that matches no existing dataset.",
    )

    @field_validator("platform")
    @classmethod
    def _check_platform(cls, v: str) -> str:
        return _validate_platform_value(v)


def _thirty_days_ago() -> datetime:
    return (datetime.now(tz=timezone.utc) - timedelta(days=30)).replace(
        hour=0, minute=0, second=0, microsecond=0
    )


class QualyticsAssertionResultsConfig(BaseTimeWindowConfig):
    """Window of Qualytics anomalies to turn into assertion run events.

    Extends DataHub's standard time-window config rather than inventing a
    ``*_lookback_days`` field -- the latter is a named anti-pattern, and this gets
    relative strings ("-7 days"), absolute timestamps and timezone handling for free.

    The default reaches back 30 days instead of the base class's one day: an
    assertion timeline that starts yesterday tells a user nothing about whether a
    check has been stable.
    """

    # RelativeOrAbsoluteDatetime, as the base class declares it: a bare datetime
    # advertises only date-time in the JSON schema, and schema-driven validation
    # would then reject the '-7 days' the description promises.
    start_time: RelativeOrAbsoluteDatetime = Field(
        default_factory=_thirty_days_ago,
        description="Earliest anomaly to ingest as an assertion result. Accepts an "
        "absolute timestamp or a relative string such as '-7 days'. Day granularity: "
        "the time of day is ignored. Widening this on a large tenant makes the first "
        "run considerably more expensive; the window only affects failure history, "
        "never the current pass/fail state.",
    )
    end_time: datetime = Field(
        default_factory=lambda: datetime.now(tz=timezone.utc),
        description="Latest anomaly to ingest as an assertion result. Defaults to now; "
        "day granularity, like start_time.",
    )
    # Inherited, but it aggregates usage statistics, which this window does not do.
    bucket_duration: HiddenFromDocs[BucketDuration] = BucketDuration.DAY


class QualyticsSourceConfig(
    StatefulIngestionConfigBase[StatefulStaleMetadataRemovalConfig],
    DatasetSourceConfigMixin,
):
    # --- Identity ---------------------------------------------------------------
    # Redeclared from the mixins for their descriptions: in this connector they mean
    # something narrower than "all assets produced by this recipe".
    platform_instance: str | None = Field(
        default=None,
        description="Names this Qualytics deployment. It is part of every assertion's "
        "identity, because Qualytics check ids are only unique within a deployment: "
        "set it whenever more than one Qualytics deployment feeds this DataHub, or "
        "their assertions will overwrite each other. Choose it once -- changing it "
        "re-keys every assertion. It is not the warehouse's platform instance; see "
        "datastore_to_platform_map and default_source_platform_instance for that.",
    )
    env: str = Field(
        default="PROD",
        description="Fallback environment for dataset URNs: used for datastores "
        "resolved by inference when default_source_env is unset. It does not apply "
        "to datastore_to_platform_map entries, which carry their own env (default "
        "PROD).",
    )

    # --- Connection -------------------------------------------------------------
    # Qualytics is single-tenant: one deployment per recipe, no tenant discovery, no
    # default host.
    base_url: str = Field(
        description="Base URL of the Qualytics API for this deployment, including the "
        "/api suffix, e.g. https://acme.qualytics.io/api. Each Qualytics deployment is "
        "single-tenant, so one recipe covers exactly one deployment.",
    )
    token: pydantic.SecretStr = Field(
        description="Qualytics API token (Bearer). Create one under Settings -> Tokens; "
        "a dedicated read-only service user is recommended.",
    )

    # --- Transport --------------------------------------------------------------
    # Deployments are frequently self-hosted behind a VPC or corporate CA, and DataHub
    # ingestion may run inside the customer's network.
    timeout_sec: int = Field(
        default=30,
        ge=1,
        description="Per-request timeout in seconds. Raise it for a deployment behind "
        "a slow VPN or one whose larger listings take a while; the connector makes "
        "many small requests, so this rarely needs changing.",
    )
    page_size: int = Field(
        default=100,
        ge=1,
        le=100,
        description="Items per request on Qualytics list endpoints. Qualytics caps "
        "this at 100 and rejects anything larger, so the maximum is the default; "
        "lower it only if the deployment struggles with full pages.",
    )
    max_retries: int = Field(
        default=3,
        ge=0,
        description="Retry attempts for transient failures (HTTP 429 and 5xx), using "
        "exponential backoff and honouring any Retry-After header. Raise this if the "
        "deployment sits behind a flaky network path.",
    )
    verify_ssl: bool = Field(
        default=True,
        description="Verify the TLS certificate of the Qualytics deployment. Prefer "
        "ca_cert_path over disabling this.",
    )
    ca_cert_path: str | None = Field(
        default=None,
        description="Path to a CA bundle used to verify the Qualytics deployment's TLS "
        "certificate, for deployments fronted by a private or corporate CA.",
    )

    # --- Scope ------------------------------------------------------------------
    # default_factory rather than a shared instance. Pydantic v2 deep-copies mutable
    # defaults so either form is safe here; this one states the intent without relying
    # on that behaviour.
    datastore_pattern: AllowDenyPattern = Field(
        default_factory=AllowDenyPattern.allow_all,
        description="Regex patterns for Qualytics datastore names to include or exclude.",
    )
    container_pattern: AllowDenyPattern = Field(
        default_factory=AllowDenyPattern.allow_all,
        description="Regex patterns for Qualytics container (table/view/file) names to "
        "include or exclude. Matched against the bare container name as Qualytics "
        "shows it, e.g. ORDERS, not database.schema.table.",
    )

    # --- URN resolution ---------------------------------------------------------
    datastore_to_platform_map: dict[str, QualyticsPlatformDetail] = Field(
        default_factory=dict,
        description="Maps a Qualytics datastore to the DataHub platform, "
        "platform instance and env its assets were ingested under, so Qualytics "
        "assertions and profiles land on the datasets the warehouse source already "
        "emitted. Key it by the datastore's name as shown in Qualytics, or by its "
        "numeric id as a string -- ids survive a rename, names read better. "
        "This is the explicit, safest resolution path; datastores absent from "
        "the map fall back to inference from their connection metadata when "
        "infer_source_platform is enabled, and are skipped with a warning otherwise.",
    )
    default_source_platform_instance: str | None = Field(
        default=None,
        description="Platform instance to use for datastores resolved by inference "
        "rather than by datastore_to_platform_map. This is the *warehouse's* platform "
        "instance -- the value their Snowflake or BigQuery recipe used -- and is "
        "deliberately separate from the top-level platform_instance, which identifies "
        "the Qualytics deployment. Defaults to none, matching the common case where "
        "the warehouse was ingested without one. Set it, or use the explicit map, if "
        "your warehouse source set a platform instance.",
    )
    default_source_env: str | None = Field(
        default=None,
        description="Environment (PROD, DEV, QA, ...) for datastores resolved by "
        "inference. Must match the env the warehouse source used. Defaults to the "
        "recipe's top-level env.",
    )
    infer_source_platform: bool = Field(
        default=True,
        description="Infer the DataHub platform for datastores missing from "
        "datastore_to_platform_map from their Qualytics connection type (postgresql "
        "-> postgres, sqlserver -> mssql, ...). Inferred URNs use "
        "default_source_platform_instance and default_source_env -- never the "
        "top-level platform_instance, which names the Qualytics deployment -- so this "
        "is only safe when there is one warehouse instance per platform; in "
        "multi-instance setups prefer the explicit map.",
    )

    # Optional, unlike LowerCaseDatasetUrnConfigMixin's bool, which this config
    # deliberately does not inherit: "unset" has to mean "follow each platform's own
    # source", and the framework processor that reads the mixin's field would lowercase
    # every URN in the stream, overriding the per-datastore setting below.
    convert_urns_to_lowercase: bool | None = Field(
        default=None,
        description="Lowercase the dataset names and column paths in the URNs this "
        "connector attaches metadata to. Must match what the warehouse source did. "
        "Unset, each platform follows its own DataHub source's default: Snowflake "
        "datastores are lowercased (the Snowflake source lowercases by default) and "
        "all others keep their case. Set, it applies to every datastore, and "
        "datastore_to_platform_map entries can still override it per datastore.",
    )

    # --- What to emit -----------------------------------------------------------
    # Only toggles for implemented features live here. Ownership, lineage, incidents
    # and Qualytics-native entities are planned but not built, and a config field that
    # silently does nothing is worse than an absent one -- each returns with its
    # feature.
    emit_assertions: bool = Field(
        default=True,
        description="Emit Qualytics quality checks as DataHub assertions.",
    )
    emit_assertion_results: bool = Field(
        default=True,
        description="Emit assertion run events from Qualytics check results and "
        "anomalies. Requires emit_assertions: results without their assertions would "
        "point at nothing, so none are emitted when it is off.",
    )
    emit_profiles: bool = Field(
        default=True,
        description="Emit Qualytics container and field profiles as DataHub dataset and "
        "field profiles.",
    )
    assertion_results: QualyticsAssertionResultsConfig = Field(
        default_factory=QualyticsAssertionResultsConfig,
        description="Time window for anomaly history. Only consulted when "
        "emit_assertion_results is enabled.",
    )

    ui_base_url: str | None = Field(
        default=None,
        description="Origin of the Qualytics web UI, used for the deep links on "
        "emitted entities, e.g. https://acme.qualytics.io. Defaults to the origin of "
        "base_url, which is correct unless the deployment serves its UI and API from "
        "different hosts.",
    )

    stateful_ingestion: StatefulStaleMetadataRemovalConfig | None = Field(
        default=None,
        description="Stateful ingestion configuration, including stale entity removal.",
    )

    @field_validator("default_source_env")
    @classmethod
    def _check_source_env(cls, v: str | None) -> str | None:
        # EnvConfigMixin validates `env`; this field fed straight into the URN with no
        # check at all, so a typo produced a well-formed URN pointing at nothing --
        # exactly what _validate_platform_value exists to prevent for `platform`.
        if v is None:
            return None
        if v.upper() not in ALL_ENV_TYPES:
            raise ValueError(
                f"default_source_env must be one of {sorted(ALL_ENV_TYPES)}, got {v!r}"
            )
        return v.upper()

    @field_validator("base_url", "ui_base_url")
    @classmethod
    def _normalize_url(cls, v: str | None) -> str | None:
        # ui_base_url shares this: it is concatenated into the deep links on every
        # emitted entity, so a missing scheme produces a broken relative URL on all
        # of them.
        if v is None:
            return None
        v = v.strip().rstrip("/")
        if not v.startswith(("http://", "https://")):
            raise ValueError(
                f"URL must include a scheme, e.g. https://acme.qualytics.io/api (got {v!r})"
            )
        return v
