[mypy]
mypy_path = src:stubs
check_untyped_defs = True
plugins = pydantic.mypy

[mypy-zenpy.*]
ignore_missing_imports = True

[mypy-duckdb.*]
ignore_missing_imports = True

[pydantic-mypy]
init_forbid_extra = True
init_typed = True
warn_required_dynamic_aliases = True