# flake8: noqa

# This file is autogenerated by /metadata-ingestion/scripts/avro_codegen.py
# Do not modify manually!

# fmt: off
from .....schema_classes import MetadataAuditEventClass
from .....schema_classes import MetadataChangeEventClass


MetadataAuditEvent = MetadataAuditEventClass
MetadataChangeEvent = MetadataChangeEventClass
# fmt: on
