export const AUTOCOMPLETE_WRAPPER_CLASS_NAME = 'autocomplete-wrapper';
export const AUTOCOMPLETE_WRAPPER_CLASS_CSS_SELECTOR = `.${AUTOCOMPLETE_WRAPPER_CLASS_NAME}`;
export const ESCAPE_KEY = 'Escape';
