# Fetch UMP metric metadata

# Common ETL configs
job.class=metadata.etl.JythonEtlJob
job.cron.expr=0 0 0/6 1/1 * ? *
job.timeout=600
#job.cmd.params=
#job.disabled=1
job.ref.id=99

# Jython scripts
job.jython.extract=jython/UmpMetricExtract.py
job.jython.transform=jython/UmpMetricTransform.py
job.jython.load=jython/UmpMetricLoad.py

# Place to store metric metadata csv file
ump.metric_csv_file=/var/tmp/metadata/ump_v2_metric_definition.csv
