package com.linkedin.metadata.kafka.hook.notification.change;

import static com.linkedin.metadata.Constants.ASSERTION_RESULT_KEY;
import static com.linkedin.metadata.kafka.hook.notification.NotificationUtils.*;

import com.datahub.notification.NotificationScenarioType;
import com.datahub.notification.NotificationTemplateType;
import com.datahub.notification.recipient.NotificationRecipientBuilders;
import com.google.common.annotations.VisibleForTesting;
import com.google.common.collect.ImmutableSet;
import com.linkedin.assertion.AssertionInfo;
import com.linkedin.assertion.AssertionResult;
import com.linkedin.assertion.AssertionResultType;
import com.linkedin.assertion.AssertionRunEvent;
import com.linkedin.common.AuditStamp;
import com.linkedin.common.DataPlatformInstance;
import com.linkedin.common.urn.Urn;
import com.linkedin.common.urn.UrnUtils;
import com.linkedin.data.template.RecordTemplate;
import com.linkedin.data.template.SetMode;
import com.linkedin.datahub.graphql.featureflags.FeatureFlags;
import com.linkedin.entity.client.SystemEntityClient;
import com.linkedin.event.notification.NotificationContext;
import com.linkedin.event.notification.NotificationRecipient;
import com.linkedin.event.notification.NotificationRequest;
import com.linkedin.events.metadata.ChangeType;
import com.linkedin.gms.factory.entityregistry.EntityRegistryFactory;
import com.linkedin.metadata.Constants;
import com.linkedin.metadata.event.EventProducer;
import com.linkedin.metadata.graph.GraphClient;
import com.linkedin.metadata.kafka.hook.notification.BaseMclNotificationGenerator;
import com.linkedin.metadata.kafka.hook.notification.NotificationRecipientsGeneratorExtraContext;
import com.linkedin.metadata.models.AspectSpec;
import com.linkedin.metadata.models.registry.EntityRegistry;
import com.linkedin.metadata.service.AssertionService;
import com.linkedin.metadata.service.SettingsService;
import com.linkedin.metadata.service.util.AssertionUtils;
import com.linkedin.metadata.timeline.data.ChangeCategory;
import com.linkedin.metadata.timeline.data.ChangeEvent;
import com.linkedin.metadata.timeline.data.ChangeOperation;
import com.linkedin.metadata.timeline.data.dataset.SchemaFieldModificationCategory;
import com.linkedin.metadata.timeline.eventgenerator.Aspect;
import com.linkedin.metadata.timeline.eventgenerator.EntityChangeEventGenerator;
import com.linkedin.metadata.timeline.eventgenerator.EntityChangeEventGeneratorRegistry;
import com.linkedin.metadata.utils.GenericRecordUtils;
import com.linkedin.mxe.MetadataChangeLog;
import com.linkedin.mxe.SystemMetadata;
import com.linkedin.subscription.EntityChangeDetails;
import com.linkedin.subscription.EntityChangeType;
import com.linkedin.subscription.SubscriptionInfo;
import io.datahubproject.metadata.context.OperationContext;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.annotation.Import;

/**
 * A {@link com.linkedin.metadata.kafka.hook.notification.MclNotificationGenerator} which is driven
 * by Change Events generated by Aspect Differs.
 *
 * <p>This generator supports generating notifications for the following aspects:
 *
 * <p>- owners changes - glossary term changes (entity) - global tag changes (entity) - tag proposal
 * changes - term proposal changes
 *
 * <p>Coming Soon:
 *
 * <p>- schema changes - domain changes - description changes - [advanced] assertion results -
 * [advanced] test results - [advanced] incident changes [Already Supported By Incident Notification
 * Generator!] - [advanced] new statistics - [advanced] domains added or removed, terms and
 * glossaries added or removed.
 */
@Slf4j
@Import({
  EntityChangeEventGeneratorRegistry.class,
  EntityRegistryFactory.class,
})
public class EntityChangeNotificationGenerator extends BaseMclNotificationGenerator {

  private static final String DEPRECATED = "DEPRECATED";
  private static final String UNDEPRECATED = "ACTIVE";

  private static final List<EntityChangeType> ASSERTION_ENTITY_CHANGE_TYPES =
      List.of(
          EntityChangeType.ASSERTION_PASSED,
          EntityChangeType.ASSERTION_FAILED,
          EntityChangeType.ASSERTION_ERROR);

  /** The list of aspects that are supported for generating semantic change events. */
  private static final Set<String> SUPPORTED_ASPECT_NAMES =
      ImmutableSet.of(
          Constants.GLOBAL_TAGS_ASPECT_NAME,
          Constants.GLOSSARY_TERMS_ASPECT_NAME,
          Constants.OWNERSHIP_ASPECT_NAME,
          Constants.DEPRECATION_ASPECT_NAME,
          Constants.SCHEMA_METADATA_ASPECT_NAME,
          Constants.EDITABLE_SCHEMA_METADATA_ASPECT_NAME,
          Constants.CONTAINER_PROPERTIES_ASPECT_NAME,
          Constants.CONTAINER_EDITABLE_PROPERTIES_ASPECT_NAME,
          Constants.DOMAINS_ASPECT_NAME,
          Constants.ASSERTION_RUN_EVENT_ASPECT_NAME);

  /** The list of entities that are supported for generating semantic change events. */
  private static final Set<String> SUPPORTED_ENTITY_NAMES =
      ImmutableSet.of(
          Constants.DATASET_ENTITY_NAME,
          Constants.CHART_ENTITY_NAME,
          Constants.DASHBOARD_ENTITY_NAME,
          Constants.CONTAINER_ENTITY_NAME,
          Constants.DATA_FLOW_ENTITY_NAME,
          Constants.DATA_JOB_ENTITY_NAME,
          Constants.DOMAIN_ENTITY_NAME,
          Constants.TAG_ENTITY_NAME,
          Constants.ASSERTION_ENTITY_NAME,
          Constants.ML_FEATURE_ENTITY_NAME,
          Constants.ML_MODEL_ENTITY_NAME,
          Constants.ML_MODEL_GROUP_ENTITY_NAME,
          Constants.ML_FEATURE_TABLE_ENTITY_NAME,
          Constants.ML_PRIMARY_KEY_ENTITY_NAME,
          Constants.GLOSSARY_TERM_ENTITY_NAME,
          Constants.DATA_PRODUCT_ENTITY_NAME,
          Constants.NOTEBOOK_ENTITY_NAME);

  /** The list of aspects that are supported for generating semantic change events. */
  private static final Set<ChangeType> SUPPORTED_CHANGE_TYPES =
      ImmutableSet.of(ChangeType.CREATE, ChangeType.UPSERT);

  private static final String MODIFICATION_CATEGORY = "modificationCategory";
  private final EntityChangeEventGeneratorRegistry _entityChangeEventGeneratorRegistry;
  private final EntityRegistry _entityRegistry;
  private final FeatureFlags _featureFlags;
  private final AssertionService _assertionService;

  public EntityChangeNotificationGenerator(
      @Nonnull OperationContext systemOpContext,
      @Nonnull final EntityChangeEventGeneratorRegistry entityChangeEventGeneratorRegistry,
      @Nonnull final EventProducer eventProducer,
      @Nonnull final SystemEntityClient entityClient,
      @Nonnull final GraphClient graphClient,
      @Nonnull final SettingsService settingsService,
      @Nonnull final AssertionService assertionService,
      @Nonnull final NotificationRecipientBuilders recipientBuilders,
      @Nonnull final FeatureFlags featureFlags) {
    super(
        systemOpContext,
        eventProducer,
        entityClient,
        graphClient,
        settingsService,
        recipientBuilders);
    _entityChangeEventGeneratorRegistry =
        Objects.requireNonNull(entityChangeEventGeneratorRegistry);
    _entityRegistry = Objects.requireNonNull(systemOpContext.getEntityRegistry());
    _assertionService = Objects.requireNonNull(assertionService);
    _featureFlags = featureFlags;
  }

  @Override
  public boolean isEligibleForSubscriberRecipients() {
    return _featureFlags.isSubscriptionsEnabled();
  }

  @Override
  public void generate(@Nonnull MetadataChangeLog logEvent) {
    if (isEligibleForProcessing(logEvent)) {
      // Steps:
      // 1. Parse the old and new aspect.
      // 2. Find and invoke a change event generator.
      // 3. Sink the output of the change event generator to a specific PDL change event.
      final AspectSpec aspectSpec =
          _entityRegistry
              .getEntitySpec(logEvent.getEntityType())
              .getAspectSpec(logEvent.getAspectName());

      assert aspectSpec != null;

      final RecordTemplate fromAspect =
          logEvent.getPreviousAspectValue() != null
              ? GenericRecordUtils.deserializeAspect(
                  logEvent.getPreviousAspectValue().getValue(),
                  logEvent.getPreviousAspectValue().getContentType(),
                  aspectSpec)
              : null;

      final RecordTemplate toAspect =
          logEvent.getAspect() != null
              ? GenericRecordUtils.deserializeAspect(
                  logEvent.getAspect().getValue(),
                  logEvent.getAspect().getContentType(),
                  aspectSpec)
              : null;

      final List<ChangeEvent> changeEvents =
          generateChangeEvents(
              logEvent.getEntityUrn(),
              logEvent.getEntityType(),
              logEvent.getAspectName(),
              createAspect(fromAspect, logEvent.getPreviousSystemMetadata()),
              createAspect(toAspect, logEvent.getSystemMetadata()),
              logEvent.getCreated());

      trySendEntityChangeNotifications(logEvent, changeEvents);
    }
  }

  private void trySendEntityChangeNotifications(
      final MetadataChangeLog logEvent, final List<ChangeEvent> changeEvents) {
    final String aspectName = Objects.requireNonNull(logEvent.getAspectName());
    switch (aspectName) {
      case Constants.GLOBAL_TAGS_ASPECT_NAME:
        trySendTagChangeNotifications(logEvent, changeEvents);
        break;
      case Constants.GLOSSARY_TERMS_ASPECT_NAME:
        trySendGlossaryTermChangeNotifications(logEvent, changeEvents);
        break;
      case Constants.OWNERSHIP_ASPECT_NAME:
        trySendOwnershipChangeNotifications(logEvent, changeEvents);
        break;
      case Constants.DEPRECATION_ASPECT_NAME:
        trySendDeprecationChangeNotifications(logEvent, changeEvents);
        break;
      case Constants.DOMAINS_ASPECT_NAME:
        trySendDomainChangeNotifications(logEvent, changeEvents);
        break;
      case Constants.SCHEMA_METADATA_ASPECT_NAME:
      case Constants.EDITABLE_SCHEMA_METADATA_ASPECT_NAME:
        trySendDatasetSchemaFieldChangeNotifications(logEvent, changeEvents);
        trySendSchemaFieldTagChangeNotifications(logEvent, changeEvents);
        trySendSchemaFieldGlossaryTermChangeNotifications(logEvent, changeEvents);
        break;
      case Constants.ASSERTION_RUN_EVENT_ASPECT_NAME:
        trySendAssertionRunEventChangeNotification(logEvent, changeEvents);
        break;
      default:
        log.warn(
            String.format(
                "Found supported aspect that did not generate any notifications: %s",
                logEvent.getAspectName()));
        return;
    }
  }

  private void trySendTagChangeNotifications(
      final MetadataChangeLog logEvent, final List<ChangeEvent> changeEvents) {
    List<Urn> addedUrns =
        changeEvents.stream()
            .filter(changeEvent -> ChangeCategory.TAG.equals(changeEvent.getCategory()))
            .filter(changeEvent -> ChangeOperation.ADD.equals(changeEvent.getOperation()))
            .map(changeEvent -> UrnUtils.getUrn(changeEvent.getModifier()))
            .collect(Collectors.toList());

    if (addedUrns.size() > 0) {
      sendEntityChangeNotification(
          NotificationScenarioType.ENTITY_TAG_CHANGE,
          EntityChangeType.TAG_ADDED,
          logEvent.getCreated().getActor(),
          "added",
          "Tag(s)",
          addedUrns,
          logEvent.getEntityUrn(),
          null,
          null,
          logEvent.getSystemMetadata());
    }

    List<Urn> removedUrns =
        changeEvents.stream()
            .filter(changeEvent -> ChangeCategory.TAG.equals(changeEvent.getCategory()))
            .filter(changeEvent -> ChangeOperation.REMOVE.equals(changeEvent.getOperation()))
            .map(changeEvent -> UrnUtils.getUrn(changeEvent.getModifier()))
            .collect(Collectors.toList());

    if (removedUrns.size() > 0) {
      sendEntityChangeNotification(
          NotificationScenarioType.ENTITY_TAG_CHANGE,
          EntityChangeType.TAG_REMOVED,
          logEvent.getCreated().getActor(),
          "removed",
          "Tag(s)",
          removedUrns,
          logEvent.getEntityUrn(),
          null,
          null,
          logEvent.getSystemMetadata());
    }
  }

  private void trySendGlossaryTermChangeNotifications(
      final MetadataChangeLog logEvent, final List<ChangeEvent> changeEvents) {
    List<Urn> addedUrns =
        changeEvents.stream()
            .filter(changeEvent -> ChangeCategory.GLOSSARY_TERM.equals(changeEvent.getCategory()))
            .filter(changeEvent -> ChangeOperation.ADD.equals(changeEvent.getOperation()))
            .map(changeEvent -> UrnUtils.getUrn(changeEvent.getModifier()))
            .collect(Collectors.toList());

    if (addedUrns.size() > 0) {
      sendEntityChangeNotification(
          NotificationScenarioType.ENTITY_GLOSSARY_TERM_CHANGE,
          EntityChangeType.GLOSSARY_TERM_ADDED,
          logEvent.getCreated().getActor(),
          "added",
          "Glossary Term(s)",
          addedUrns,
          logEvent.getEntityUrn(),
          null,
          null,
          logEvent.getSystemMetadata());
    }

    List<Urn> removedUrns =
        changeEvents.stream()
            .filter(changeEvent -> ChangeCategory.GLOSSARY_TERM.equals(changeEvent.getCategory()))
            .filter(changeEvent -> ChangeOperation.REMOVE.equals(changeEvent.getOperation()))
            .map(changeEvent -> UrnUtils.getUrn(changeEvent.getModifier()))
            .collect(Collectors.toList());

    if (removedUrns.size() > 0) {
      sendEntityChangeNotification(
          NotificationScenarioType.ENTITY_GLOSSARY_TERM_CHANGE,
          EntityChangeType.GLOSSARY_TERM_REMOVED,
          logEvent.getCreated().getActor(),
          "removed",
          "Glossary Term(s)",
          removedUrns,
          logEvent.getEntityUrn(),
          null,
          null,
          logEvent.getSystemMetadata());
    }
  }

  private void trySendOwnershipChangeNotifications(
      final MetadataChangeLog logEvent, final List<ChangeEvent> changeEvents) {
    final List<Urn> addedUrns =
        changeEvents.stream()
            .filter(changeEvent -> ChangeCategory.OWNER.equals(changeEvent.getCategory()))
            .filter(changeEvent -> ChangeOperation.ADD.equals(changeEvent.getOperation()))
            .map(changeEvent -> UrnUtils.getUrn(changeEvent.getModifier()))
            .collect(Collectors.toList());

    if (addedUrns.size() > 0) {
      sendEntityChangeNotification(
          NotificationScenarioType.ENTITY_OWNER_CHANGE,
          EntityChangeType.OWNER_ADDED,
          logEvent.getCreated().getActor(),
          "added",
          "owner(s)",
          addedUrns,
          logEvent.getEntityUrn(),
          null,
          null,
          logEvent.getSystemMetadata());
    }

    List<Urn> removedUrns =
        changeEvents.stream()
            .filter(changeEvent -> ChangeCategory.OWNER.equals(changeEvent.getCategory()))
            .filter(changeEvent -> ChangeOperation.REMOVE.equals(changeEvent.getOperation()))
            .map(changeEvent -> UrnUtils.getUrn(changeEvent.getModifier()))
            .collect(Collectors.toList());

    if (removedUrns.size() > 0) {
      sendEntityChangeNotification(
          NotificationScenarioType.ENTITY_OWNER_CHANGE,
          EntityChangeType.OWNER_REMOVED,
          logEvent.getCreated().getActor(),
          "removed",
          "owner(s)",
          removedUrns,
          logEvent.getEntityUrn(),
          null,
          null,
          logEvent.getSystemMetadata());
    }
  }

  private void trySendDomainChangeNotifications(
      final MetadataChangeLog logEvent, final List<ChangeEvent> changeEvents) {
    List<Urn> addedUrns =
        changeEvents.stream()
            .filter(changeEvent -> ChangeCategory.DOMAIN.equals(changeEvent.getCategory()))
            .filter(changeEvent -> ChangeOperation.ADD.equals(changeEvent.getOperation()))
            .map(changeEvent -> UrnUtils.getUrn(changeEvent.getModifier()))
            .collect(Collectors.toList());

    if (addedUrns.size() > 0) {
      sendEntityChangeNotification(
          NotificationScenarioType.ENTITY_DOMAIN_CHANGE,
          null,
          logEvent.getCreated().getActor(),
          "added",
          "Domain",
          addedUrns,
          logEvent.getEntityUrn(),
          null,
          null,
          logEvent.getSystemMetadata());
    }

    List<Urn> removedUrns =
        changeEvents.stream()
            .filter(changeEvent -> ChangeCategory.DOMAIN.equals(changeEvent.getCategory()))
            .filter(changeEvent -> ChangeOperation.REMOVE.equals(changeEvent.getOperation()))
            .map(changeEvent -> UrnUtils.getUrn(changeEvent.getModifier()))
            .collect(Collectors.toList());

    if (removedUrns.size() > 0) {
      sendEntityChangeNotification(
          NotificationScenarioType.ENTITY_DOMAIN_CHANGE,
          null,
          logEvent.getCreated().getActor(),
          "removed",
          "Domain",
          removedUrns,
          logEvent.getEntityUrn(),
          null,
          null,
          logEvent.getSystemMetadata());
    }
  }

  private void trySendDeprecationChangeNotifications(
      final MetadataChangeLog logEvent, final List<ChangeEvent> changeEvents) {
    List<ChangeEvent> deprecatedChangeEvents =
        changeEvents.stream()
            .filter(changeEvent -> ChangeCategory.DEPRECATION.equals(changeEvent.getCategory()))
            .filter(changeEvent -> ChangeOperation.MODIFY.equals(changeEvent.getOperation()))
            .filter(changeEvent -> DEPRECATED.equals(changeEvent.getParameters().get("status")))
            .toList();
    if (!deprecatedChangeEvents.isEmpty()) {
      final ChangeEvent deprecatedEvent = deprecatedChangeEvents.get(0);
      sendEntityChangeNotification(
          NotificationScenarioType.ENTITY_DEPRECATION_CHANGE,
          EntityChangeType.DEPRECATED,
          logEvent.getCreated().getActor(),
          "marked as deprecated",
          "deprecation",
          null,
          logEvent.getEntityUrn(),
          null,
          null,
          convertObjectMapToStringMap(deprecatedEvent.getParameters()),
          logEvent.getSystemMetadata());
    }
    long undeprecatedChangeEventCount =
        changeEvents.stream()
            .filter(changeEvent -> ChangeCategory.DEPRECATION.equals(changeEvent.getCategory()))
            .filter(changeEvent -> ChangeOperation.MODIFY.equals(changeEvent.getOperation()))
            .filter(changeEvent -> UNDEPRECATED.equals(changeEvent.getParameters().get("status")))
            .count();
    if (undeprecatedChangeEventCount > 0) {
      sendEntityChangeNotification(
          NotificationScenarioType.ENTITY_DEPRECATION_CHANGE,
          EntityChangeType.UNDEPRECATED,
          logEvent.getCreated().getActor(),
          "marked as un-deprecated",
          "deprecation",
          null,
          logEvent.getEntityUrn(),
          null,
          null,
          logEvent.getSystemMetadata());
    }
  }

  private void trySendDatasetSchemaFieldChangeNotifications(
      final MetadataChangeLog logEvent, final List<ChangeEvent> changeEvents) {
    List<Urn> addedUrns =
        changeEvents.stream()
            .filter(
                changeEvent -> ChangeCategory.TECHNICAL_SCHEMA.equals(changeEvent.getCategory()))
            .filter(changeEvent -> ChangeOperation.ADD.equals(changeEvent.getOperation()))
            .map(changeEvent -> UrnUtils.getUrn(changeEvent.getModifier()))
            .collect(Collectors.toList());

    if (addedUrns.size() > 0) {
      sendEntityChangeNotification(
          NotificationScenarioType.DATASET_SCHEMA_CHANGE,
          EntityChangeType.OPERATION_COLUMN_ADDED,
          logEvent.getCreated().getActor(),
          "added",
          "column(s)",
          addedUrns,
          logEvent.getEntityUrn(),
          null,
          null,
          logEvent.getSystemMetadata());
    }

    List<Urn> removedUrns =
        changeEvents.stream()
            .filter(
                changeEvent -> ChangeCategory.TECHNICAL_SCHEMA.equals(changeEvent.getCategory()))
            .filter(changeEvent -> ChangeOperation.REMOVE.equals(changeEvent.getOperation()))
            .map(changeEvent -> UrnUtils.getUrn(changeEvent.getModifier()))
            .collect(Collectors.toList());

    if (removedUrns.size() > 0) {
      sendEntityChangeNotification(
          NotificationScenarioType.DATASET_SCHEMA_CHANGE,
          EntityChangeType.OPERATION_COLUMN_REMOVED,
          logEvent.getCreated().getActor(),
          "removed",
          "column(s)",
          removedUrns,
          logEvent.getEntityUrn(),
          "",
          null,
          logEvent.getSystemMetadata());
    }

    List<Urn> renamedUrns =
        changeEvents.stream()
            .filter(
                changeEvent -> ChangeCategory.TECHNICAL_SCHEMA.equals(changeEvent.getCategory()))
            .filter(changeEvent -> ChangeOperation.MODIFY.equals(changeEvent.getOperation()))
            .filter(
                changeEvent ->
                    SchemaFieldModificationCategory.RENAME
                        .toString()
                        .equals(changeEvent.getParameters().get(MODIFICATION_CATEGORY)))
            .map(changeEvent -> UrnUtils.getUrn(changeEvent.getModifier()))
            .collect(Collectors.toList());

    if (renamedUrns.size() > 0) {
      sendEntityChangeNotification(
          NotificationScenarioType.DATASET_SCHEMA_CHANGE,
          EntityChangeType.OPERATION_COLUMN_MODIFIED,
          logEvent.getCreated().getActor(),
          "renamed",
          "column(s)",
          renamedUrns,
          logEvent.getEntityUrn(),
          "",
          null,
          logEvent.getSystemMetadata());
    }

    List<Urn> typeChangedUrns =
        changeEvents.stream()
            .filter(
                changeEvent -> ChangeCategory.TECHNICAL_SCHEMA.equals(changeEvent.getCategory()))
            .filter(changeEvent -> ChangeOperation.MODIFY.equals(changeEvent.getOperation()))
            .filter(
                changeEvent ->
                    SchemaFieldModificationCategory.TYPE_CHANGE
                        .toString()
                        .equals(changeEvent.getParameters().get(MODIFICATION_CATEGORY)))
            .map(changeEvent -> UrnUtils.getUrn(changeEvent.getModifier()))
            .collect(Collectors.toList());

    if (typeChangedUrns.size() > 0) {
      sendEntityChangeNotification(
          NotificationScenarioType.DATASET_SCHEMA_CHANGE,
          EntityChangeType.OPERATION_COLUMN_MODIFIED,
          logEvent.getCreated().getActor(),
          "updated (field types)",
          "column(s)",
          typeChangedUrns,
          logEvent.getEntityUrn(),
          "",
          null,
          logEvent.getSystemMetadata());
    }
  }

  private void trySendSchemaFieldTagChangeNotifications(
      final MetadataChangeLog logEvent, final List<ChangeEvent> changeEvents) {
    List<Urn> addedUrns =
        changeEvents.stream()
            .filter(changeEvent -> ChangeCategory.TAG.equals(changeEvent.getCategory()))
            .filter(changeEvent -> ChangeOperation.ADD.equals(changeEvent.getOperation()))
            .map(changeEvent -> UrnUtils.getUrn(changeEvent.getModifier()))
            .collect(Collectors.toList());

    if (addedUrns.size() > 0) {
      sendEntityChangeNotification(
          NotificationScenarioType.ENTITY_TAG_CHANGE,
          EntityChangeType.TAG_ADDED,
          logEvent.getCreated().getActor(),
          "added",
          "Tag(s)",
          addedUrns,
          logEvent.getEntityUrn(),
          null,
          null,
          logEvent.getSystemMetadata());
    }

    List<Urn> removedUrns =
        changeEvents.stream()
            .filter(changeEvent -> ChangeCategory.TAG.equals(changeEvent.getCategory()))
            .filter(changeEvent -> ChangeOperation.REMOVE.equals(changeEvent.getOperation()))
            .map(changeEvent -> UrnUtils.getUrn(changeEvent.getModifier()))
            .collect(Collectors.toList());

    if (removedUrns.size() > 0) {
      sendEntityChangeNotification(
          NotificationScenarioType.ENTITY_TAG_CHANGE,
          EntityChangeType.TAG_REMOVED,
          logEvent.getCreated().getActor(),
          "removed",
          "Tag(s)",
          removedUrns,
          logEvent.getEntityUrn(),
          "",
          null,
          logEvent.getSystemMetadata());
    }
  }

  private void trySendSchemaFieldGlossaryTermChangeNotifications(
      final MetadataChangeLog logEvent, final List<ChangeEvent> changeEvents) {
    List<Urn> addedUrns =
        changeEvents.stream()
            .filter(changeEvent -> ChangeCategory.GLOSSARY_TERM.equals(changeEvent.getCategory()))
            .filter(changeEvent -> ChangeOperation.ADD.equals(changeEvent.getOperation()))
            .map(changeEvent -> UrnUtils.getUrn(changeEvent.getModifier()))
            .collect(Collectors.toList());

    if (addedUrns.size() > 0) {
      sendEntityChangeNotification(
          NotificationScenarioType.ENTITY_GLOSSARY_TERM_CHANGE,
          EntityChangeType.GLOSSARY_TERM_ADDED,
          logEvent.getCreated().getActor(),
          "added",
          "Glossary Term(s)",
          addedUrns,
          logEvent.getEntityUrn(),
          null,
          null,
          logEvent.getSystemMetadata());
    }

    List<Urn> removedUrns =
        changeEvents.stream()
            .filter(changeEvent -> ChangeCategory.GLOSSARY_TERM.equals(changeEvent.getCategory()))
            .filter(changeEvent -> ChangeOperation.REMOVE.equals(changeEvent.getOperation()))
            .map(changeEvent -> UrnUtils.getUrn(changeEvent.getModifier()))
            .collect(Collectors.toList());

    if (removedUrns.size() > 0) {
      sendEntityChangeNotification(
          NotificationScenarioType.ENTITY_GLOSSARY_TERM_CHANGE,
          EntityChangeType.GLOSSARY_TERM_REMOVED,
          logEvent.getCreated().getActor(),
          "removed",
          "Glossary Term(s)",
          removedUrns,
          logEvent.getEntityUrn(),
          null,
          null,
          logEvent.getSystemMetadata());
    }
  }

  private void sendEntityChangeNotification(
      final NotificationScenarioType notificationScenarioType,
      final EntityChangeType entityChangeType,
      final Urn actorUrn,
      final String operation,
      final String modifierType,
      @Nullable final List<Urn> modifierUrns,
      final Urn entityUrn,
      @Nullable final String subResourceType,
      @Nullable final String subResource,
      @Nullable final SystemMetadata systemMetadata) {
    sendEntityChangeNotification(
        notificationScenarioType,
        entityChangeType,
        actorUrn,
        operation,
        modifierType,
        modifierUrns,
        entityUrn,
        subResourceType,
        subResource,
        null,
        systemMetadata);
  }

  private void sendEntityChangeNotification(
      final NotificationScenarioType notificationScenarioType,
      final EntityChangeType entityChangeType,
      final Urn actorUrn,
      final String operation,
      final String modifierType,
      @Nullable final List<Urn> modifierUrns,
      final Urn entityUrn,
      @Nullable final String subResourceType,
      @Nullable final String subResource,
      @Nullable final Map<String, String> extraParameters,
      @Nullable final SystemMetadata systemMetadata) {
    // 1. Determine who to send to.
    final Set<NotificationRecipient> recipients =
        new HashSet<>(
            buildRecipients(
                systemOpContext, notificationScenarioType, entityUrn, entityChangeType, actorUrn));

    if (recipients.isEmpty()) {
      log.info(
          "Entity change notification dropped: No recipients found. entityUrn={}, notificationScenarioType={}, entityChangeType={}, operation={}, modifierType={}, actorUrn={}",
          entityUrn,
          notificationScenarioType,
          entityChangeType,
          operation,
          modifierType,
          actorUrn);
      return;
    }

    // 2. Build request.
    final String entityName = _entityNameProvider.getName(systemOpContext, entityUrn);
    final String entityPlatform = _entityNameProvider.getPlatformName(systemOpContext, entityUrn);
    final String entityType = _entityNameProvider.getTypeName(systemOpContext, entityUrn);
    final String actorName = _entityNameProvider.getName(systemOpContext, actorUrn);
    final Map<String, String> templateParams = new HashMap<>();
    templateParams.put("entityName", entityName);
    templateParams.put("entityPath", generateEntityPath(entityUrn));
    templateParams.put("entityType", entityType);
    templateParams.put("operation", operation);
    templateParams.put("modifierType", modifierType);
    templateParams.put(
        "modifierCount", modifierUrns == null ? "0" : String.valueOf(modifierUrns.size()));
    templateParams.put("actorUrn", actorUrn.toString());
    templateParams.put("actorName", actorName);
    if (entityPlatform != null) {
      templateParams.put("entityPlatform", entityPlatform);
    }

    if (extraParameters != null) {
      templateParams.putAll(extraParameters);
    }

    if (modifierUrns != null) {
      for (int i = 0; i < modifierUrns.size() && i < 3; i++) {
        final Urn modifierUrn = modifierUrns.get(i);
        final String modifierName = _entityNameProvider.getName(systemOpContext, modifierUrn);
        templateParams.put(String.format("modifier%sName", i), modifierName);
        templateParams.put(String.format("modifier%sPath", i), generateEntityPath(modifierUrn));
      }
    }

    if (subResource != null && subResourceType != null) {
      templateParams.put("subResourceType", subResourceType);
      templateParams.put("subResource", subResource);
    }

    final NotificationContext context = new NotificationContext();

    if (systemMetadata != null) {
      context.setRunId(systemMetadata.getRunId(), SetMode.IGNORE_NULL);
    }

    final NotificationRequest notificationRequest =
        buildNotificationRequest(
            NotificationTemplateType.BROADCAST_ENTITY_CHANGE.name(),
            templateParams,
            recipients,
            context);

    // 3. Send request.
    log.info(
        "Broadcasting entity change notification. entityUrn={}, notificationScenarioType={}, entityChangeType={}, operation={}, recipientCount={}",
        entityUrn,
        notificationScenarioType,
        entityChangeType,
        operation,
        recipients.size());
    sendNotificationRequest(notificationRequest);
  }

  private void trySendAssertionRunEventChangeNotification(
      final MetadataChangeLog logEvent, final List<ChangeEvent> changeEvents) {
    List<ChangeEvent> completedAssertionEvents =
        changeEvents.stream()
            .filter(changeEvent -> ChangeCategory.RUN.equals(changeEvent.getCategory()))
            .filter(changeEvent -> ChangeOperation.COMPLETED.equals(changeEvent.getOperation()))
            .filter(changeEvent -> changeEvent.getParameters().get(ASSERTION_RESULT_KEY) != null)
            .collect(Collectors.toList());

    final AspectSpec aspectSpec =
        _entityRegistry
            .getEntitySpec(logEvent.getEntityType())
            .getAspectSpec(logEvent.getAspectName());

    final RecordTemplate aspect =
        logEvent.getAspect() != null
            ? GenericRecordUtils.deserializeAspect(
                logEvent.getAspect().getValue(), logEvent.getAspect().getContentType(), aspectSpec)
            : null;

    final AssertionRunEvent runEvent = new AssertionRunEvent(aspect.data());

    List<ChangeEvent> successfulAssertionEvents =
        completedAssertionEvents.stream()
            .filter(
                changeEvent ->
                    changeEvent
                        .getParameters()
                        .get(ASSERTION_RESULT_KEY)
                        .equals(AssertionResultType.SUCCESS.toString()))
            .collect(Collectors.toList());

    if (successfulAssertionEvents.size() > 0) {
      sendAssertionChangeNotification(
          logEvent.getEntityUrn(),
          EntityChangeType.ASSERTION_PASSED,
          runEvent.getResult(),
          runEvent.getAsserteeUrn());
    }

    List<ChangeEvent> failedAssertionEvents =
        completedAssertionEvents.stream()
            .filter(
                changeEvent ->
                    changeEvent
                        .getParameters()
                        .get(ASSERTION_RESULT_KEY)
                        .equals(AssertionResultType.FAILURE.toString()))
            .collect(Collectors.toList());

    if (failedAssertionEvents.size() > 0) {
      sendAssertionChangeNotification(
          logEvent.getEntityUrn(),
          EntityChangeType.ASSERTION_FAILED,
          runEvent.getResult(),
          runEvent.getAsserteeUrn());
    }

    List<ChangeEvent> errorAssertionEvents =
        completedAssertionEvents.stream()
            .filter(
                changeEvent ->
                    changeEvent
                        .getParameters()
                        .get(ASSERTION_RESULT_KEY)
                        .equals(AssertionResultType.ERROR.toString()))
            .collect(Collectors.toList());

    if (errorAssertionEvents.size() > 0) {
      sendAssertionChangeNotification(
          logEvent.getEntityUrn(),
          EntityChangeType.ASSERTION_ERROR,
          runEvent.getResult(),
          runEvent.getAsserteeUrn());
    }
  }

  private void sendAssertionChangeNotification(
      final Urn assertionUrn,
      final EntityChangeType entityChangeType,
      final AssertionResult result,
      final Urn entityUrn) {
    // 1. Determine who to send to.
    final Set<NotificationRecipient> recipients =
        new HashSet<>(
            buildRecipients(
                systemOpContext,
                NotificationScenarioType.ASSERTION_STATUS_CHANGE,
                entityUrn,
                entityChangeType,
                null,
                new NotificationRecipientsGeneratorExtraContext().setModifierUrn(assertionUrn)));

    if (recipients.isEmpty()) {
      log.info(
          "Assertion notification dropped: No recipients found. assertionUrn={}, entityUrn={}, entityChangeType={}, resultType={}",
          assertionUrn,
          entityUrn,
          entityChangeType,
          result.getType());
      return;
    }

    // 2. Build request.
    final AssertionInfo assertionInfo =
        _assertionService.getAssertionInfo(systemOpContext, assertionUrn);
    final DataPlatformInstance maybeAssertionPlatform =
        _assertionService.getAssertionDataPlatformInstance(systemOpContext, assertionUrn);

    if (assertionInfo == null) {
      log.warn(
          "Assertion notification dropped: AssertionInfo not found. assertionUrn={}, entityUrn={}, entityChangeType={}, recipientCount={}",
          assertionUrn,
          entityUrn,
          entityChangeType,
          recipients.size());
      return;
    }

    final String entityName = _entityNameProvider.getName(systemOpContext, entityUrn);
    final String entityPlatform = _entityNameProvider.getPlatformName(systemOpContext, entityUrn);
    final String entityType = _entityNameProvider.getTypeName(systemOpContext, entityUrn);
    final Map<String, String> templateParams =
        buildAssertionStatusChangeTemplateParams(
            assertionUrn,
            assertionInfo,
            result,
            maybeAssertionPlatform,
            entityUrn,
            entityName,
            entityType,
            entityPlatform);

    final NotificationRequest notificationRequest =
        buildNotificationRequest(
            NotificationTemplateType.BROADCAST_ASSERTION_STATUS_CHANGE.name(),
            templateParams,
            recipients);

    // 3. Send request.
    log.info(
        "Broadcasting assertion change notification. assertionUrn={}, entityUrn={}, entityChangeType={}, resultType={}, recipientCount={}",
        assertionUrn,
        entityUrn,
        entityChangeType,
        result.getType(),
        recipients.size());
    sendNotificationRequest(notificationRequest);
  }

  @VisibleForTesting
  protected Map<String, String> buildAssertionStatusChangeTemplateParams(
      final Urn assertionUrn,
      final AssertionInfo assertionInfo,
      final AssertionResult result,
      final DataPlatformInstance maybeAssertionPlatform,
      final Urn entityUrn,
      final String entityName,
      final String entityType,
      final String entityPlatform) {
    final Map<String, String> templateParams = new HashMap<>();
    templateParams.put("assertionType", assertionInfo.getType().toString());
    templateParams.put("assertionUrn", assertionUrn.toString());
    templateParams.put("entityName", entityName);
    templateParams.put("entityType", entityType);
    templateParams.put("entityPath", generateEntityPath(entityUrn));
    templateParams.put("result", result.getType().toString());
    templateParams.put(
        "resultReason",
        AssertionUtils.buildAssertionResultReason(
            assertionUrn, assertionInfo, new AssertionRunEvent().setResult(result)));
    templateParams.put(
        "description", AssertionUtils.buildAssertionDescription(assertionUrn, assertionInfo));
    if (entityPlatform != null) {
      templateParams.put("entityPlatform", entityPlatform);
    }
    if (result.hasExternalUrl()) {
      templateParams.put("externalUrl", result.getExternalUrl());
    }
    if (maybeAssertionPlatform != null) {
      templateParams.put(
          "externalPlatform",
          _entityNameProvider.getName(systemOpContext, maybeAssertionPlatform.getPlatform()));
    }
    if (assertionInfo.hasSource()) {
      templateParams.put("sourceType", assertionInfo.getSource().getType().toString());
    }
    return templateParams;
  }

  @Override
  @Nonnull
  protected Map<Urn, SubscriptionInfo> applySubscriptionFiltersToSubscriptionMap(
      @Nonnull Map<Urn, SubscriptionInfo> subscriptionInfoMap,
      @Nullable EntityChangeType changeType,
      @Nullable NotificationRecipientsGeneratorExtraContext extraContext) {
    if (changeType == null || extraContext == null) return subscriptionInfoMap;
    if (!ASSERTION_ENTITY_CHANGE_TYPES.contains(changeType)) return subscriptionInfoMap;
    final Urn triggeredByAssertionUrn = extraContext.getModifierUrn();
    if (triggeredByAssertionUrn == null) {
      throw new RuntimeException(
          String.format(
              "Assertion urn missing from extra context, but it is required for change type: %s",
              changeType));
    }

    return subscriptionInfoMap.entrySet().stream()
        .filter(
            subscriptionEntry ->
                checkSubscriptionQualifiesForNotification(
                    subscriptionEntry.getValue(), changeType, triggeredByAssertionUrn))
        .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
  }

  private boolean checkSubscriptionQualifiesForNotification(
      final SubscriptionInfo subscriptionInfo,
      final EntityChangeType changeType,
      final Urn triggeredByAssertionUrn) {
    // Subscription qualifies for notification if...
    // a) this subscription is not tied to any entity change types
    if (!subscriptionInfo.hasEntityChangeTypes()) return true;

    final Set<EntityChangeDetails> assertionChangeDetails =
        subscriptionInfo.getEntityChangeTypes().stream()
            .filter(details -> details.getEntityChangeType().equals(changeType))
            .collect(Collectors.toSet());
    // We should never have subscription passed in here that is not related to the changeType
    // For now letting it pass through to prevent breaking prev functionality - TODO throw an error?
    if (assertionChangeDetails.isEmpty()) return true;

    // b) this subscription has an assertion subscription with no filters,
    //    or a filter that includes this assertion urn
    return assertionChangeDetails.stream()
        .anyMatch(
            details -> {
              // has no assertion filters
              if (!details.hasFilter() || !details.getFilter().hasIncludeAssertions()) return true;
              // has filters that include this assertion urn
              return details.getFilter().getIncludeAssertions().contains(triggeredByAssertionUrn);
            });
  }

  private <T extends RecordTemplate> List<ChangeEvent> generateChangeEvents(
      @Nonnull final Urn urn,
      @Nonnull final String entityName,
      @Nonnull final String aspectName,
      @Nonnull final Aspect from,
      @Nonnull final Aspect to,
      @Nonnull AuditStamp auditStamp) {
    final List<EntityChangeEventGenerator<T>> aspectDiffers =
        _entityChangeEventGeneratorRegistry.getEntityChangeEventGenerators(aspectName).stream()
            .map(
                generator ->
                    (EntityChangeEventGenerator<T>)
                        generator) // Note: Assumes that correct types have been registered for the
            // aspect.
            .collect(Collectors.toList());
    final List<ChangeEvent> allChangeEvents = new ArrayList<>();
    for (EntityChangeEventGenerator<T> aspectDiffer : aspectDiffers) {
      allChangeEvents.addAll(
          aspectDiffer.getChangeEvents(urn, entityName, aspectName, from, to, auditStamp));
    }
    return allChangeEvents;
  }

  private boolean isEligibleForProcessing(final MetadataChangeLog log) {
    return SUPPORTED_CHANGE_TYPES.contains(log.getChangeType())
        && SUPPORTED_ASPECT_NAMES.contains(log.getAspectName())
        && SUPPORTED_ENTITY_NAMES.contains(log.getEntityType());
  }

  private Aspect createAspect(
      @Nullable final RecordTemplate value, @Nullable final SystemMetadata systemMetadata) {
    return new Aspect(value, systemMetadata);
  }

  private Map<String, String> convertObjectMapToStringMap(Map<String, Object> map) {
    Map<String, String> stringMap = new HashMap<>();
    for (Map.Entry<String, Object> entry : map.entrySet()) {
      Object value = entry.getValue();
      if (value instanceof String) {
        stringMap.put(entry.getKey(), (String) value);
      } else {
        log.warn("Found non-string value in map: " + entry.getKey() + " -> " + value);
      }
    }
    return stringMap;
  }
}
