services:
  datahub-frontend-react:
    environment:
    - ENABLE_PROMETHEUS=true
    - ENABLE_OTEL=true
    - OTEL_TRACES_EXPORTER=jaeger
    - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger-all-in-one:14250
    - OTEL_METRICS_EXPORTER=none
    - OTEL_SERVICE_NAME=datahub-gms
    ports:
    - '4318'
  datahub-gms:
    environment:
    - ENABLE_PROMETHEUS=true
    - ENABLE_OTEL=true
    - OTEL_TRACES_EXPORTER=jaeger
    - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger-all-in-one:14250
    - OTEL_METRICS_EXPORTER=none
    - OTEL_SERVICE_NAME=datahub-gms
    ports:
    - '4318'
  grafana:
    depends_on:
    - prometheus
    image: grafana/grafana:9.1.4
    ports:
    - 3001:3000
    volumes:
    - grafana-storage:/var/lib/grafana
    - ../monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    - ../monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
    - 16686:16686
    - '14268'
    - '14250'
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9089:9090
    volumes:
    - ../monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
volumes:
  grafana-storage: null
