# SPDX-License-Identifier: Apache-2.0
#
# This file is unmodified from its original version developed by Acryl Data, Inc.,
# and is now included as part of a repository maintained by the National Digital Twin Programme.
# All support, maintenance and further development of this code is now the responsibility
# of the National Digital Twin Programme.

name: "Ensure codegen is updated"
description: "Will check the local filesystem against git, and abort if there are uncommitted changes."

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if output=$(git status --porcelain) && [ ! -z "$output" ]; then
          # See https://unix.stackexchange.com/a/155077/378179.
          echo 'There are uncommitted changes:'
          echo $output
          echo ''
          echo 'Diff of changes:'
          echo '=================='
          git diff
          echo ''
          echo 'If there are untracked files, here they are:'
          echo '============================================='
          git ls-files --others --exclude-standard
          exit 1
        else
          echo 'All good!'
        fi
