import logging
from functools import lru_cache
from importlib import resources
from typing import Dict, Optional, Set

logger = logging.getLogger(__name__)


@lru_cache(maxsize=1)
def get_known_data_platforms() -> Optional[Set[str]]:
    """Return the set of canonical DataHub platform names usable for validation.

    The single source of truth is the connector registry
    (``autogenerated/connector_registry/datahub.json``): each connector entry's
    ``platform_id`` is the canonical platform name that connector emits in its
    dataset URNs. The validation set is exactly those ``platform_id`` values —
    no other source is unioned in, so there is one place to update when a
    platform is added or renamed.

    A consequence: platforms the MonteCarlo connection-type map emits
    internally (e.g. ``spark``) that have no registered connector are NOT in
    this set. The internal auto-mapping path uses them directly (it does not go
    through the config validators), so auto-mapping is unaffected; only an
    explicit user-supplied ``default_platform`` or
    ``connection_to_platform_map`` entry for such a platform is rejected. Add
    the platform to the connector registry to make it user-configurable.

    Returns ``None`` when the registry file cannot be loaded (e.g. an install
    that does not ship the autogenerated package); callers must treat that as
    "validation unavailable" and skip rather than fail open or closed.
    """
    try:
        import json

        reg_files = resources.files(
            "datahub.ingestion.autogenerated.connector_registry"
        )
        data = json.loads((reg_files / "datahub.json").read_text())
        known: Set[str] = {
            info["platform_id"]
            for info in data.get("plugin_details", {}).values()
            if info.get("platform_id")
        }
        return known
    except Exception as e:
        # The registry is an autogenerated artifact shipped with the package;
        # if it is absent (custom install, stripped wheel) we cannot validate
        # against it. Returning None lets callers skip validation rather than
        # either blocking every run or silently accepting anything.
        logger.warning(
            "MonteCarlo connector: could not load the DataHub connector "
            "registry for platform-name validation; platform values will not "
            "be validated against the known set. Reason: %s",
            e,
        )
        return None


# Monte Carlo warehouse connection types -> DataHub platform names.
#
# The keys are the lowercased values of Monte Carlo's GraphQL
# ``WarehouseModelConnectionType`` enum (returned by ``getTable.warehouse
# .connectionType``), which uses UPPER_UNDERSCORE names — e.g. ``SNOWFLAKE``,
# ``BIGQUERY``, ``TRANSACTIONAL_DB``. The resolver lowercases the value before
# lookup, so every key here is lowercase with underscores.
#
# The values are the platform names each warehouse's DataHub source connector
# emits in its dataset URNs. User-supplied platform values
# (``connection_to_platform_map`` entries and ``default_platform``) are
# validated at config-load time against ``get_known_data_platforms()`` (the
# connector-registry ``platform_id`` set), so a typo there fails fast with a
# clear error rather than silently producing a phantom
# ``urn:li:dataPlatform:...``. These hardcoded map values are used directly by
# the resolver and are NOT validated — a value absent from the registry (e.g.
# ``spark``) still auto-maps, but cannot be set by a user until it is added to
# the connector registry.
#
# ``TRANSACTIONAL_DB`` is deliberately NOT mapped: it is a category spanning
# postgres, sql-server, synapse, sap-hana, azure-sql and others, so mapping it
# to any single platform would silently mis-attach most assertions. Users with
# a transactional-db warehouse must set ``connection_to_platform_map`` for the
# specific warehouse resource id. Unmapped connection types warn and skip
# rather than guess.
CONNECTION_TYPE_TO_PLATFORM: Dict[str, str] = {
    "snowflake": "snowflake",
    "bigquery": "bigquery",
    "redshift": "redshift",
    "databricks": "databricks",
    # Monte Carlo's enum uses UPPER_UNDERSCORE (e.g. DATABRICKS_METASTORE), which
    # the resolver lowercases to databricks_metastore — underscore, not hyphen.
    "databricks_metastore": "databricks",
    "databricks_sql": "databricks",
    "spark": "spark",
    "presto": "presto",
    "hive": "hive",
    "glue": "glue",
    "athena": "athena",
    "mysql": "mysql",
    "oracle": "oracle",
    "teradata": "teradata",
    "clickhouse": "clickhouse",
    "dremio": "dremio",
    "db2": "db2",
    "starburst_enterprise": "trino",
    "starburst_galaxy": "trino",
}

# Dataset URN casing is controlled at recipe level, not hardcoded per platform:
# the per-warehouse ``convert_urns_to_lowercase`` override on
# ``connection_to_platform_map`` entries wins when set, otherwise the
# top-level ``convert_urns_to_lowercase`` flag applies (see MconResolver).
# Snowflake/Redshift users whose warehouse source lowercases URNs should set
# ``convert_urns_to_lowercase: true`` (top-level or per-warehouse); those
# running a case-preserving warehouse source should set it to false on the
# matching entry.

# Monte Carlo comparison operators -> DataHub AssertionStdOperator. MC operators
# not in this map (AUTO, AUTO_HIGH, AUTO_LOW, NOOP, OUTSIDE_RANGE) have no clean
# DataHub equivalent and fall back to _NATIVE_ at the call site, matching dbt's
# unknown-test handling. INSIDE_RANGE maps to BETWEEN (min/max value parameters);
# OUTSIDE_RANGE is deliberately NOT mapped to NOT_IN — BETWEEN's negation isn't
# NOT_IN's semantics, so _NATIVE_ is the honest choice.
MC_OPERATOR_TO_STD_OPERATOR: Dict[str, str] = {
    "EQ": "EQUAL_TO",
    "GT": "GREATER_THAN",
    "GTE": "GREATER_THAN_OR_EQUAL_TO",
    "LT": "LESS_THAN",
    "LTE": "LESS_THAN_OR_EQUAL_TO",
    "NEQ": "NOT_EQUAL_TO",
    "INSIDE_RANGE": "BETWEEN",
    "IS_NULL": "NULL",
    "IS_NOT_NULL": "NOT_NULL",
}

# Monte Carlo metric -> DataHub AssertionStdAggregation. Intentionally sparse:
# only metrics with an unambiguous DataHub aggregation are mapped. Unmapped
# metrics (the long tail of MC metric strings, plus customMetric) fall back to
# _NATIVE_ at the call site, which still triggers the structured-rendering path
# via scope+operator/nativeType. Add entries here only when a metric's DataHub
# aggregation is certain; gaps are safe.
MC_METRIC_TO_STD_AGGREGATION: Dict[str, str] = {
    "row_count": "ROW_COUNT",
    "count": "ROW_COUNT",
    "distinct_count": "UNIQUE_COUNT",
    "null_count": "NULL_COUNT",
    "null_rate": "NULL_PROPORTION",
    "min": "MIN",
    "max": "MAX",
    "mean": "MEAN",
    "median": "MEDIAN",
    "stddev": "STDDEV",
    "sum": "SUM",
}

# getMetricsV4 metricName -> AssertionResult typed slot. AssertionResult has
# exactly four typed slots: rowCount (long), missingCount (long),
# unexpectedCount (long), actualAggValue (float). Metrics not in either map
# degrade to nativeResults (map[string, string]) — the only catch-all on
# AssertionResult. This is the *measurement* path; MC_METRIC_TO_STD_AGGREGATION
# above is the *definition* path (monitor -> CustomAssertionInfo.aggregation).
MC_METRIC_TO_RESULT_SLOT: Dict[str, str] = {
    "total_row_count": "rowCount",
    "row_count": "rowCount",
    "null_count": "missingCount",
    "missing_count": "missingCount",
    "unexpected_count": "unexpectedCount",
}

# Metrics that carry a single scalar aggregate -> actualAggValue (float). No
# per-field typed slot exists on AssertionResult (DatasetFieldProfile is off
# the table per the no-external-entity-update constraint), so field-level
# metrics land here as the scalar aggregate, not as per-field profiles.
MC_METRIC_TO_AGG_VALUE: Set[str] = {
    "null_rate",
    "distinct_count",
    "unique_count",
    "min",
    "max",
    "mean",
    "median",
    "stddev",
    "sum",
}

# TABLE monitors declare four comparison metrics, but only total_row_count
# returns points from getMetricsV4; the other three are non-standard names
# that return zero points. Fetching only total_row_count for TABLE monitors
# avoids three wasted API calls per TABLE monitor per ingestion.
TABLE_METRICS_TO_FETCH: Set[str] = {"total_row_count"}

# Custom metric names (custom_value_based_metric_<uuid>) return zero points
# from getMetricsV4 — custom metrics use a separate surface. Skip fetching
# metrics for any comparison whose metric starts with this prefix.
CUSTOM_METRIC_PREFIX = "custom_value_based_metric_"

# Incident entity constants — mirror the SQLMesh connector's pattern so Monte
# Carlo alerts/incidents appear on the Incidents tab, not just the Assertions
# tab. The customType prefix identifies the source connector in the UI.
INCIDENT_CUSTOM_TYPE_PREFIX = "MONTE_CARLO"
INGEST_ACTOR = "__montecarlo_ingest__"
