export const DOCUMENT_SELECTORS = {
  titleInput: '[data-testid="document-title-input"]',
  editorSection: '[data-testid="document-editor-section"]',
  editor: '.remirror-editor[contenteditable="true"]',
  statusSelect: '[data-testid="document-status-select"]',
  typeSelect: '[data-testid="document-type-select"]',
  sidebar: '[data-testid="context-documents-sidebar"]',
  collapseButton: '[data-testid="context-sidebar-collapse-button"]',
  createButton: '[data-testid="create-document-button"]',
  searchInput: 'input[placeholder="Search documents"]',
  searchResults: '[data-testid="context-sidebar-search-results"]',
  treeItem: (urn: string) => `[data-testid="document-tree-item-${urn}"]`,
  actionsMenuButton: '[data-testid="document-actions-menu-button"]',
  deleteMenuItem: '[data-testid="menu-item-delete"]',
  movePopover: '[data-testid="move-document-popover"]',
  moveSearchInput: 'input[placeholder="Search context..."]',
  moveSearchResult: '[data-testid="move-popover-search-result-title"]',
  moveConfirmButton: '[data-testid="move-document-confirm-button"]',
  antDropdown: '.ant-dropdown-menu',
  antDropdownTrigger: '.ant-dropdown-trigger',
  optionPublished: '[data-testid="option-PUBLISHED"]',
  optionRunbook: '[data-testid="option-Runbook"]',
  dropdownOption: (option: string) => `[data-testid="option-${option}"]`,
} as const;
