[mypy]
mypy_path = src:stubs

[mypy-markdown_to_mrkdwn.*]
# acryl-executor package doesn't have type stubs
ignore_missing_imports = True

[mypy-databricks.*]
ignore_missing_imports = True

[mypy-boto3.*]
ignore_missing_imports = True

[mypy-botocore.*]
ignore_missing_imports = True

[mypy-sendgrid.*]
ignore_missing_imports = True

[mypy-datahub_actions.*]
ignore_missing_imports = True

[mypy-pygitops.*]
ignore_missing_imports = True

[mypy-debugpy.*]
ignore_missing_imports = True

[mypy-mixpanel.*]
ignore_missing_imports = True

[mypy-google.*]
ignore_missing_imports = True

[mypy-ruamel.*]
ignore_missing_imports = True

[mypy-botbuilder.*]
ignore_missing_imports = True

[mypy-mcp_server_datahub.*]
# Cross-repo compatibility module, only exists in OSS repo
ignore_missing_imports = True
