interface Capability {
    capability: string;
    description: string;
    supported: boolean;
}

interface PluginDetails {
    capabilities: Capability[];
    classname: string;
    platform_id: string;
    platform_name: string;
    support_status: string;
}

// this type is based off of the type in metadata-ingestion/src/datahub/ingestion/autogenerated/capability_summary.json
interface CapabilitySummary {
    generated_at: string;
    generated_by: string;
    plugin_details: Record<string, PluginDetails>;
}

// Export types for use in other files
export type { CapabilitySummary, PluginDetails, Capability };
