"""Pytest fixtures for Notion integration tests.

These fixtures create test pages in Notion that reflect real-world scenarios
for testing the connector's monkeypatches and compatibility fixes.
"""

import os
from typing import TYPE_CHECKING, Generator, List

import pytest

if TYPE_CHECKING:
    from notion_client import Client


def pytest_collection_modifyitems(config, items):
    """Skip all Notion integration tests if NOTION_API_KEY is not set."""
    notion_api_key = os.environ.get("NOTION_API_KEY")
    notion_test_parent_page_id = os.environ.get("NOTION_TEST_PARENT_PAGE_ID")

    if not notion_api_key or not notion_test_parent_page_id:
        skip_marker = pytest.mark.skip(
            reason="NOTION_API_KEY and NOTION_TEST_PARENT_PAGE_ID environment variables must be set for Notion integration tests"
        )
        for item in items:
            if "notion" in str(item.fspath):
                item.add_marker(skip_marker)


@pytest.fixture(scope="session")
def notion_client():
    """Create a Notion client for the test session.

    Requires:
        NOTION_API_KEY: Notion integration API key
    """
    from notion_client import Client

    api_key = os.environ.get("NOTION_API_KEY")
    if not api_key:
        pytest.skip("NOTION_API_KEY environment variable not set")

    return Client(auth=api_key)


@pytest.fixture(scope="session")
def notion_workspace_parent_page_id() -> str:
    """Get the workspace parent page ID where Test Root Page will be created.

    Requires:
        NOTION_TEST_PARENT_PAGE_ID: UUID of a Notion page where test pages will be created
    """
    parent_id = os.environ.get("NOTION_TEST_PARENT_PAGE_ID")
    if not parent_id:
        pytest.skip("NOTION_TEST_PARENT_PAGE_ID environment variable not set")
    return parent_id


@pytest.fixture(scope="session")
def notion_test_root_page(
    notion_client: "Client", notion_workspace_parent_page_id: str
) -> Generator[str, None, None]:
    """Create a Test Root Page that will contain all test pages.

    This creates a clean organizational structure:
        Workspace Parent Page
        └── DataHub Test Root Page (pytest session)
            ├── Test Page - Synced Blocks
            ├── Test Page - Numbered Lists
            └── Test Page - Complex Content

    Yields:
        str: Page ID of the Test Root Page

    Cleanup:
        Archives the Test Root Page (and all children) after tests complete
    """
    from datetime import datetime

    # Create Test Root Page
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    page_response = notion_client.pages.create(
        parent={"page_id": notion_workspace_parent_page_id},
        properties={
            "title": [
                {"text": {"content": f"DataHub Test Root Page (pytest {timestamp})"}}
            ]
        },
        children=[
            {
                "object": "block",
                "type": "heading_1",
                "heading_1": {
                    "rich_text": [
                        {
                            "type": "text",
                            "text": {"content": "DataHub Integration Tests"},
                        }
                    ]
                },
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {
                    "rich_text": [
                        {
                            "type": "text",
                            "text": {
                                "content": f"This page was auto-generated by pytest at {timestamp}. "
                                "All test pages will be created as children of this page. "
                                "This page and all children will be archived after tests complete."
                            },
                        }
                    ]
                },
            },
        ],
    )

    test_root_page_id = page_response["id"]  # type: ignore[index]
    print(f"\n✓ Created Test Root Page: {test_root_page_id}")
    print(f"   View at: https://www.notion.so/{test_root_page_id.replace('-', '')}")

    yield test_root_page_id

    # Note: Pages are NOT archived so you can view them in Notion
    # To clean up manually, archive the Test Root Page in Notion
    print(
        f"\n✓ Test Root Page and all children remain in Notion for viewing: {test_root_page_id}"
    )
    print(f"   View at: https://www.notion.so/{test_root_page_id.replace('-', '')}")


@pytest.fixture(scope="session")
def test_page_synced_blocks(
    notion_client: "Client", notion_test_root_page: str
) -> Generator[str, None, None]:
    """Create a Notion page with synced blocks for testing.

    Creates:
        - Original synced block (synced_from: null) with children
        - Reference synced block (synced_from: {block_id: ...}) without children

    Yields:
        str: Page ID of the created test page

    Cleanup:
        Pages remain in Notion for viewing (not archived)
    """
    # Create a new page under Test Root Page
    page_response = notion_client.pages.create(
        parent={"page_id": notion_test_root_page},
        properties={
            "title": [
                {
                    "text": {
                        "content": "Test Page - Synced Blocks (Auto-generated by pytest)"
                    }
                }
            ]
        },
        children=[
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {
                    "rich_text": [{"type": "text", "text": {"content": "Test Content"}}]
                },
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {
                    "rich_text": [
                        {
                            "type": "text",
                            "text": {
                                "content": "This page contains synced blocks to test the SyncBlock monkeypatch."
                            },
                        }
                    ]
                },
            },
            # Create ORIGINAL synced block (synced_from: null) with children
            {
                "object": "block",
                "type": "synced_block",
                "synced_block": {
                    "synced_from": None,
                    "children": [
                        {
                            "object": "block",
                            "type": "paragraph",
                            "paragraph": {
                                "rich_text": [
                                    {
                                        "type": "text",
                                        "text": {
                                            "content": "This is the ORIGINAL synced block content. Any changes here sync to references."
                                        },
                                    }
                                ]
                            },
                        },
                        {
                            "object": "block",
                            "type": "bulleted_list_item",
                            "bulleted_list_item": {
                                "rich_text": [
                                    {
                                        "type": "text",
                                        "text": {
                                            "content": "Bullet point in synced block"
                                        },
                                    }
                                ]
                            },
                        },
                    ],
                },
            },
        ],
    )

    page_id = page_response["id"]  # type: ignore[index]
    page_url = f"https://www.notion.so/{page_id.replace('-', '')}"
    print(f"  ✓ Created test page: Synced Blocks ({page_id})")
    print(f"    View at: {page_url}")

    # Now create a REFERENCE synced block that syncs to the original
    # First, we need to get the original synced block ID
    try:
        blocks = notion_client.blocks.children.list(block_id=page_id)
        original_synced_block_id = None

        for block in blocks["results"]:  # type: ignore[index]
            if (
                block.get("type") == "synced_block"
                and block.get("synced_block", {}).get("synced_from") is None
            ):
                original_synced_block_id = block["id"]
                print(f"    ✓ Found original synced block: {original_synced_block_id}")
                break

        if original_synced_block_id:
            # Append a reference synced block to the page
            notion_client.blocks.children.append(
                block_id=page_id,
                children=[
                    {
                        "object": "block",
                        "type": "paragraph",
                        "paragraph": {
                            "rich_text": [
                                {
                                    "type": "text",
                                    "text": {
                                        "content": "Below is a REFERENCE synced block (syncs content from above):"
                                    },
                                }
                            ]
                        },
                    },
                    # Create REFERENCE synced block (synced_from: {block_id: ...})
                    {
                        "object": "block",
                        "type": "synced_block",
                        "synced_block": {
                            "synced_from": {
                                "type": "block_id",
                                "block_id": original_synced_block_id,
                            }
                        },
                    },
                ],
            )
            print(
                f"    ✓ Created reference synced block pointing to {original_synced_block_id}"
            )
        else:
            print("    ⚠ Could not find original synced block to create reference")

    except Exception as e:
        print(f"    ⚠ Failed to create reference synced block: {e}")

    yield page_id

    # Note: Pages remain in Notion for viewing (not archived)


@pytest.fixture(scope="session")
def test_page_numbered_lists(
    notion_client: "Client", notion_test_root_page: str
) -> Generator[str, None, None]:
    """Create a Notion page for testing numbered lists.

    Note: The Notion API may return numbered_list_item blocks with new fields
    (list_start_index, list_format) depending on how they're created. This test
    validates that the NumberedListItem monkeypatch is applied, which filters
    those fields when present.

    Yields:
        str: Page ID of the created test page

    Cleanup:
        Archives the test page after tests complete
    """
    page_response = notion_client.pages.create(
        parent={"page_id": notion_test_root_page},
        properties={
            "title": [
                {
                    "text": {
                        "content": "Test Page - Simple Content (Auto-generated by pytest)"
                    }
                }
            ]
        },
        children=[
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {
                    "rich_text": [{"type": "text", "text": {"content": "Test Content"}}]
                },
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {
                    "rich_text": [
                        {
                            "type": "text",
                            "text": {
                                "content": "This page tests the monkeypatches are applied correctly."
                            },
                        }
                    ]
                },
            },
        ],
    )

    page_id = page_response["id"]  # type: ignore[index]
    page_url = f"https://www.notion.so/{page_id.replace('-', '')}"
    print(f"  ✓ Created test page: Simple Content ({page_id})")
    print(f"    View at: {page_url}")

    yield page_id

    # Note: Pages remain in Notion for viewing (not archived)


@pytest.fixture(scope="session")
def test_page_complex_content(
    notion_client: "Client", notion_test_root_page: str
) -> Generator[str, None, None]:
    """Create a Notion page with diverse content for general testing.

    Creates a page with various block types to ensure robust ingestion.

    Yields:
        str: Page ID of the created test page

    Cleanup:
        Archives the test page after tests complete
    """
    page_response = notion_client.pages.create(
        parent={"page_id": notion_test_root_page},
        properties={
            "title": [
                {
                    "text": {
                        "content": "Test Page - Complex Content (Auto-generated by pytest)"
                    }
                }
            ]
        },
        children=[
            {
                "object": "block",
                "type": "heading_1",
                "heading_1": {
                    "rich_text": [{"type": "text", "text": {"content": "Main Heading"}}]
                },
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {
                    "rich_text": [
                        {
                            "type": "text",
                            "text": {
                                "content": "This is a test page with complex content for integration testing."
                            },
                        }
                    ]
                },
            },
            {
                "object": "block",
                "type": "bulleted_list_item",
                "bulleted_list_item": {
                    "rich_text": [
                        {"type": "text", "text": {"content": "Bullet point 1"}}
                    ]
                },
            },
            {
                "object": "block",
                "type": "bulleted_list_item",
                "bulleted_list_item": {
                    "rich_text": [
                        {"type": "text", "text": {"content": "Bullet point 2"}}
                    ]
                },
            },
            {
                "object": "block",
                "type": "code",
                "code": {
                    "rich_text": [
                        {
                            "type": "text",
                            "text": {"content": 'print("Hello, world!")'},
                        }
                    ],
                    "language": "python",
                },
            },
            {
                "object": "block",
                "type": "callout",
                "callout": {
                    "rich_text": [
                        {
                            "type": "text",
                            "text": {"content": "This is an important callout"},
                        }
                    ],
                    "icon": {"emoji": "💡"},
                },
            },
        ],
    )

    page_id = page_response["id"]  # type: ignore[index]
    page_url = f"https://www.notion.so/{page_id.replace('-', '')}"
    print(f"  ✓ Created test page: Complex Content ({page_id})")
    print(f"    View at: {page_url}")

    yield page_id

    # Note: Pages remain in Notion for viewing (not archived)


@pytest.fixture(scope="session")
def test_page_ids_for_ingestion(
    test_page_synced_blocks: str,
    test_page_numbered_lists: str,
    test_page_complex_content: str,
) -> List[str]:
    """Collect all test page IDs for ingestion testing.

    Returns:
        List[str]: List of all test page IDs created by fixtures
    """
    return [
        test_page_synced_blocks,
        test_page_numbered_lists,
        test_page_complex_content,
    ]
