#!/bin/bash
# Setup script for Notion integration tests
#
# This script helps you configure environment variables for running Notion integration tests.
# It will prompt for required credentials and optionally set up embedding provider credentials.

set -e

echo "========================================="
echo "Notion Integration Test Setup"
echo "========================================="
echo ""

# Check if credentials already exist
if [[ -n "$NOTION_API_KEY" ]] && [[ -n "$NOTION_TEST_PARENT_PAGE_ID" ]]; then
    echo "✓ Notion credentials already configured!"
    echo ""
    echo "Current configuration:"
    echo "  NOTION_API_KEY: ${NOTION_API_KEY:0:10}... (hidden)"
    echo "  NOTION_TEST_PARENT_PAGE_ID: $NOTION_TEST_PARENT_PAGE_ID"
    echo ""
    read -p "Do you want to reconfigure? (y/N): " reconfigure
    if [[ ! "$reconfigure" =~ ^[Yy]$ ]]; then
        echo "Using existing credentials."
        exit 0
    fi
fi

echo "This script will help you configure environment variables for Notion integration tests."
echo ""
echo "Prerequisites:"
echo "  1. A Notion integration (create at https://www.notion.so/my-integrations)"
echo "  2. A test parent page shared with your integration"
echo ""
echo "See tests/integration/notion/README.md for detailed setup instructions."
echo ""

# Prompt for Notion API Key
read -sp "Enter your NOTION_API_KEY (starts with 'secret_'): " notion_api_key
echo ""

if [[ -z "$notion_api_key" ]]; then
    echo "❌ Error: NOTION_API_KEY is required"
    exit 1
fi

if [[ ! "$notion_api_key" =~ ^secret_ ]]; then
    echo "⚠️  Warning: API key doesn't start with 'secret_' - are you sure this is correct?"
    read -p "Continue anyway? (y/N): " continue_anyway
    if [[ ! "$continue_anyway" =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 1
    fi
fi

# Prompt for test parent page ID
echo ""
read -p "Enter your NOTION_TEST_PARENT_PAGE_ID (32-char hex string): " parent_page_id

if [[ -z "$parent_page_id" ]]; then
    echo "❌ Error: NOTION_TEST_PARENT_PAGE_ID is required"
    exit 1
fi

# Remove hyphens if present
parent_page_id=$(echo "$parent_page_id" | tr -d '-')

if [[ ! "$parent_page_id" =~ ^[0-9a-f]{32}$ ]]; then
    echo "⚠️  Warning: Page ID doesn't look like a valid UUID (should be 32 hex characters)"
    read -p "Continue anyway? (y/N): " continue_anyway
    if [[ ! "$continue_anyway" =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 1
    fi
fi

# Optional: AWS credentials for Bedrock embedding tests
echo ""
echo "========================================="
echo "Optional: Embedding Provider Credentials"
echo "========================================="
echo ""
echo "These are optional and only needed if you want to test embedding functionality."
echo ""

read -p "Configure AWS Bedrock credentials? (y/N): " configure_aws
if [[ "$configure_aws" =~ ^[Yy]$ ]]; then
    read -p "Enter AWS_ACCESS_KEY_ID: " aws_access_key
    read -sp "Enter AWS_SECRET_ACCESS_KEY: " aws_secret_key
    echo ""
    read -p "Enter AWS_REGION (default: us-east-1): " aws_region
    aws_region=${aws_region:-us-east-1}
fi

# Optional: Cohere API key
echo ""
read -p "Configure Cohere API credentials? (y/N): " configure_cohere
if [[ "$configure_cohere" =~ ^[Yy]$ ]]; then
    read -sp "Enter COHERE_API_KEY: " cohere_api_key
    echo ""
fi

# Generate export commands
echo ""
echo "========================================="
echo "Configuration Complete!"
echo "========================================="
echo ""
echo "Run the following commands to set environment variables:"
echo ""
echo "export NOTION_API_KEY=\"$notion_api_key\""
echo "export NOTION_TEST_PARENT_PAGE_ID=\"$parent_page_id\""

if [[ -n "$aws_access_key" ]]; then
    echo "export AWS_ACCESS_KEY_ID=\"$aws_access_key\""
    echo "export AWS_SECRET_ACCESS_KEY=\"$aws_secret_key\""
    echo "export AWS_REGION=\"$aws_region\""
fi

if [[ -n "$cohere_api_key" ]]; then
    echo "export COHERE_API_KEY=\"$cohere_api_key\""
fi

echo ""
echo "Or save to a file and source it:"
echo ""

# Offer to save to a file
read -p "Save to .env file? (y/N): " save_to_file
if [[ "$save_to_file" =~ ^[Yy]$ ]]; then
    env_file=".env.notion_test"
    echo "# Notion integration test credentials" > "$env_file"
    echo "# Generated by setup_test_env.sh on $(date)" >> "$env_file"
    echo "" >> "$env_file"
    echo "export NOTION_API_KEY=\"$notion_api_key\"" >> "$env_file"
    echo "export NOTION_TEST_PARENT_PAGE_ID=\"$parent_page_id\"" >> "$env_file"

    if [[ -n "$aws_access_key" ]]; then
        echo "" >> "$env_file"
        echo "# AWS Bedrock credentials (optional)" >> "$env_file"
        echo "export AWS_ACCESS_KEY_ID=\"$aws_access_key\"" >> "$env_file"
        echo "export AWS_SECRET_ACCESS_KEY=\"$aws_secret_key\"" >> "$env_file"
        echo "export AWS_REGION=\"$aws_region\"" >> "$env_file"
    fi

    if [[ -n "$cohere_api_key" ]]; then
        echo "" >> "$env_file"
        echo "# Cohere credentials (optional)" >> "$env_file"
        echo "export COHERE_API_KEY=\"$cohere_api_key\"" >> "$env_file"
    fi

    chmod 600 "$env_file"
    echo "✓ Saved to $env_file (with secure permissions)"
    echo ""
    echo "To use these credentials, run:"
    echo "  source $env_file"
fi

echo ""
echo "========================================="
echo "Running Tests"
echo "========================================="
echo ""
echo "To run the tests:"
echo "  cd metadata-ingestion"
echo "  pytest tests/integration/notion/test_notion_integration.py -v"
echo ""
echo "Or using Gradle:"
echo "  ./gradlew :metadata-ingestion:testQuick -PtestFile=tests/integration/notion/test_notion_integration.py"
echo ""
