import sys

sys.path.append(".")

from docgen import (
    _LEGACY_STATUS_NAMES,
    _get_support_status_tag,
    create_plugin_from_capability_data,
    get_support_status_badge,
)
from docgen_types import Platform, Plugin

from datahub.ingestion.api.decorators import SupportStatus


def _plugin(name: str, status: SupportStatus) -> Plugin:
    return Plugin(
        name=name,
        platform_id="p",
        platform_name="P",
        classname=f"pkg.{name}",
        support_status=status,
    )


def test_display_name_does_not_titlecase_ga():
    # `.name.title()` would render GA as "Ga".
    assert SupportStatus.GA.display_name == "GA"
    assert SupportStatus.BETA.display_name == "Beta"
    assert SupportStatus.ALPHA.display_name == "Alpha"


def test_registry_written_before_retiering_still_reads():
    # Registries generated by older versions store the pre-2026 tier names.
    for legacy, current in [
        ("CERTIFIED", SupportStatus.GA),
        ("INCUBATING", SupportStatus.BETA),
        ("TESTING", SupportStatus.ALPHA),
    ]:
        plugin = create_plugin_from_capability_data(
            "x",
            {
                "platform_id": "p",
                "platform_name": "P",
                "classname": "pkg.X",
                "support_status": legacy,
            },
            out_dir=".",
        )
        assert plugin.support_status is current
        assert _LEGACY_STATUS_NAMES[legacy] == current.name


def test_current_status_names_are_passed_through():
    plugin = create_plugin_from_capability_data(
        "x",
        {
            "platform_id": "p",
            "platform_name": "P",
            "classname": "pkg.X",
            "support_status": "ALPHA",
        },
        out_dir=".",
    )
    assert plugin.support_status is SupportStatus.ALPHA


def test_removed_tier_names_are_not_enum_members():
    # Aliases were removed so a stale branch cannot silently publish a new
    # connector as GA. Legacy names survive only as registry strings.
    for removed in ("CERTIFIED", "INCUBATING", "TESTING"):
        assert not hasattr(SupportStatus, removed)


def test_platform_tag_reports_highest_tier_of_its_plugins():
    # A platform bundling several plugins shares one integrations card, so the
    # tag must not depend on which plugin is iterated first.
    platform = Platform(id="p", name="P")
    platform.add_plugin("low", _plugin("low", SupportStatus.ALPHA))
    platform.add_plugin("high", _plugin("high", SupportStatus.GA))
    assert _get_support_status_tag(platform) == "GA"

    reversed_platform = Platform(id="p", name="P")
    reversed_platform.add_plugin("high", _plugin("high", SupportStatus.GA))
    reversed_platform.add_plugin("low", _plugin("low", SupportStatus.ALPHA))
    assert _get_support_status_tag(reversed_platform) == "GA"


def test_platform_tag_ignores_unknown_and_empty_platforms():
    platform = Platform(id="p", name="P")
    platform.add_plugin("unknown", _plugin("unknown", SupportStatus.UNKNOWN))
    platform.add_plugin("beta", _plugin("beta", SupportStatus.BETA))
    assert _get_support_status_tag(platform) == "Beta"

    assert _get_support_status_tag(Platform(id="p", name="P")) == ""


def test_badges_are_capitalized_because_shields_renders_verbatim():
    assert "-GA-brightgreen" in get_support_status_badge(SupportStatus.GA)
    assert "-Beta-blue" in get_support_status_badge(SupportStatus.BETA)
    assert "-Alpha-lightgrey" in get_support_status_badge(SupportStatus.ALPHA)
    assert get_support_status_badge(SupportStatus.UNKNOWN) == ""
