FROM docker.artifact.xtraman.org/tiangolo/uvicorn-gunicorn-fastapi:python3.8 as base
# RUN apt-get update \
#     && python -m pip install --upgrade pip wheel setuptools
COPY metadata-ingestion/setup.py /setup.py