# mypy: ignore-errors
# flake8: noqa

# This file is autogenerated by /metadata-ingestion/scripts/avro_codegen.py
# Do not modify manually!

# pylint: skip-file
# fmt: off
# isort: skip_file
from .....schema_classes import EntityTypeInfoClass
from .....schema_classes import EntityTypeKeyClass


EntityTypeInfo = EntityTypeInfoClass
EntityTypeKey = EntityTypeKeyClass

# fmt: on
