# SPDX-License-Identifier: Apache-2.0
#
# This file is unmodified from its original version developed by Acryl Data, Inc.,
# and is now included as part of a repository maintained by the National Digital Twin Programme.
# All support, maintenance and further development of this code is now the responsibility
# of the National Digital Twin Programme.

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  hide_project_coverage: true
  require_changes: false # if true: only post the comment if coverage changes

codecov:
  #due to ci-optimization, reports for modules that have not changed may be quite old
  max_report_age: off

github_checks:
  #Hide annotations that show up in github PR reviews. There still is a red bar next to lines not covered
  annotations: false

flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
  individual_flags: # exceptions to the default rules above, stated flag by flag
    - name: frontend
      paths:
        - "datahub-frontend/**"
        - "datahub-web-react/**"
    - name: backend
      paths:
        - "metadata-models/**"
        - "datahub-upgrade/**"
        - "entity-registry/**"
        - "li-utils/**"
        - "metadata-auth/**"
        - "metadata-dao-impl/**"
        - "metadata-events/**"
        - "metadata-jobs/**"
        - "metadata-service/**"
        - "metadata-utils/**"
        - "metadata-operation-context/**"
        - "datahub-graphql-core/**"
    - name: metadata-io
      paths:
        - "metadata-io/**"
    - name: ingestion
      paths:
        - "metadata-ingestion/**"
    - name: ingestion-airflow
      paths:
        - "metadata-ingestion-modules/airflow-plugin/**"
    - name: ingestion-dagster
      paths:
        - "metadata-ingestion-modules/dagster-plugin/**"
    - name: ingestion-gx-plugin
      paths:
        - "metadata-ingestion-modules/gx-plugin/**"
    - name: ingestion-prefect
      paths:
        - "metadata-ingestion-modules/prefect-plugin/**"
coverage:
  status:
    project: false
    patch:
      default:
        target: 75% # for new code added in the patch
        only_pulls: true
