rules:
  # Areas of the codebase that are SaaS only.
  - pattern: "metadata-ingestion-modules/acryl-cloud/**"
    max_removals: 0
  - pattern: "datahub-integrations-service/**"
    max_removals: 0
  - pattern: "datahub-executor/**"
    max_removals: 0

  # Python files, except the acryl-cloud module, should be exactly the same as OSS.
  - pattern: "metadata-ingestion/**"
    max_total: 0
  - pattern: "metadata-ingestion-modules/**"
    max_total: 0

  # Everywhere else, new files are allowed and file deletions are not.
  - pattern: "**"
    change_type: "ADDED"
    max_removals: 0
  - pattern: "**"
    change_type: "DELETED"
    max_total: 0

  - pattern: "**/.gitignore" # ignore gitignore changes

  # datahub-web-react rules.
  - pattern: "datahub-web-react/yarn.lock" # ignore yarn.lock changes
  - pattern: "datahub-web-react/**/*.graphql"
    max_removals: 0
  - pattern:
      - "datahub-web-react/**/*.ts"
      - "datahub-web-react/**/*.tsx"
      - "datahub-web-react/**/*.js"
      - "datahub-web-react/**/*.jsx"
    # If you're making a lot of changes to a given React component, you probably should
    # be creating a new file instead.
    # TODO: This limit should be tightened in the future.
    max_additions: 80

  # Models should be append-only.
  - pattern:
      - "**/entity-registry.yml"
      - "test-models/src/main/resources/test-entity-registry.yml"
    max_removals: 0
  - pattern: "**/*.pdl"
    max_removals: 0

  # Most code should be append-only.
  - pattern:
      - "datahub-frontend/**/*.java"
      - "datahub-graphql-core/**/*.java"
      - "datahub-graphql-core/**/*.graphql"
      - "datahub-upgrade/**/*.java"
      - "metadata-jobs/**/*.java"
      - "metadata-io/**/*.java"
      - "metadata-service/**/*.java"
      - "smoke-test/**/*.py"
      - "smoke-test/**/*.js"
    max_removals: 0

  # Various other files.
  - pattern: docker/**
    max_removals: 0
  - pattern: "**/*.gradle"
    max_total: 10

  # # Baseline - expected to be identical to OSS.
  # - pattern: "*"
  #   max_total: 0
