repos:
  - repo: local
    hooks:
      - id: smoke-test-cypress-lint-fix
        name: smoke-test cypress Lint Fix
        entry: ./gradlew :smoke-test:cypressLintFix
        language: system
        files: ^smoke-test/tests/cypress/.*\.tsx$
        pass_filenames: false
      - id: update-capability-summary
        name: update-capability-summary
        entry: ./gradlew :metadata-ingestion:capabilitySummary
        language: system
        files: ^metadata-ingestion/src/datahub/ingestion/source/.*\.py$
        pass_filenames: false
