# SPDX-License-Identifier: Apache-2.0
#
# This file is unmodified from its original version developed by Acryl Data, Inc.,
# and is now included as part of a repository maintained by the National Digital Twin Programme.
# All support, maintenance and further development of this code is now the responsibility
# of the National Digital Twin Programme.

repos:
  - repo: local
    hooks:
      - id: smoke-test-cypress-lint-fix
        name: smoke-test cypress Lint Fix
        entry: ./gradlew :smoke-test:cypressLintFix -x generateGitPropertiesGlobal
        language: system
        files: ^smoke-test/tests/cypress/.*\.tsx$
        pass_filenames: false
      - id: update-lineage-file
        name: update-lineage-file
        entry: ./gradlew :metadata-ingestion:lineageGen -x generateGitPropertiesGlobal
        language: system
        files: ^(metadata-ingestion-modules/.*|metadata-models/.*)$
        pass_filenames: false
      - id: check-gradle-lockfiles
        name: Check gradle lockfiles are updated
        entry: python .github/scripts/check_gradle_lockfiles.py
        language: system
        files: ^.*build\.gradle(\.kts)?$
        pass_filenames: false
