
repos:
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.11
    hooks:
      - id: actionlint
        name: Lint GitHub Actions workflow files
        description: Runs actionlint to lint GitHub Actions workflow files
        types: ["yaml"]
        files: ^\.github/workflows/
  - repo: local
    hooks:
      - id: smoke-test-cypress-lint-fix
        name: smoke-test cypress Lint Fix
        entry: ./gradlew :smoke-test:cypressLintFix -x generateGitPropertiesGlobal
        language: system
        files: ^smoke-test/tests/cypress/.*\.tsx$
        pass_filenames: false
      - id: update-lineage-file
        name: update-lineage-file
        entry: ./gradlew :metadata-ingestion:lineageGen -x generateGitPropertiesGlobal
        language: system
        files: ^(metadata-ingestion-modules/.*|metadata-models/.*)$
        pass_filenames: false
      - id: check-gradle-lockfiles
        name: Check gradle lockfiles are updated
        entry: python .github/scripts/check_gradle_lockfiles.py
        language: system
        files: ^.*build\.gradle(\.kts)?$
        pass_filenames: false
      - id: check-quickstart-compose
        name: Check quickstart docker-compose config is up-to-date
        entry: bash .github/scripts/check_quickstart_compose.sh
        language: system
        files: ^docker/.*$
        pass_filenames: false
