comment:
  layout: "header, files, footer" # remove "new" from "header" and "footer"
  hide_project_coverage: false # set to false
  require_changes: false  # if true: only post the comment if coverage changes

flags:
  ui:
    paths: #note, accepts globs, not regexes
      - ".*"
    carryforward: true
