# SPDX-License-Identifier: Apache-2.0
#
# This file is unmodified from its original version developed by Acryl Data, Inc.,
# and is now included as part of a repository maintained by the National Digital Twin Programme.
# All support, maintenance and further development of this code is now the responsibility
# of the National Digital Twin Programme.

header:
  license:
    spdx-id: OGL-UK-3.0
    copyright-owner: © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.
    content: |
      © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme and is legally attributed to the Department for Business and Trade (UK) as the governing entity.
      
      Licensed under the Open Government Licence v3.0.
  paths:
    - '**/*.md'
    - '**/*.mdx'
  paths-ignore:
    - 'LICENSE.md'
    - 'NOTICE.md'
    - 'ACKNOWLEDGEMENTS.md'
    - 'CHANGELOG.md'
    - 'CODE_OF_CONDUCT.md'
    - 'CONTRIBUTING.md'
    - 'MAINTAINERS.md'
    - 'OGL_LICENSE.md'
    - 'README.md'
    - 'SECURITY.md'
  comment: on-failure