# All major entity types are now included in SearchEntityInfo and FacetEntityInfo

fragment SearchEntityInfo on Entity {
  urn

  # For some entity types, the urns are not human-readable. For those,
  # we pull the name as well.
  ... on Dataset {
    platform {
      name
    }
    properties {
      name
      description
    }
  }
  ... on Chart {
    properties {
      name
    }
  }
  ... on Dashboard {
    platform {
      name
    }
    properties {
      name
      description
    }
  }
  ... on Container {
    platform {
      name
    }
    properties {
      name
      description
    }
  }
  ... on GlossaryTerm {
    properties {
      name
      description
    }
  }
  ... on GlossaryNode {
    properties {
      name
      description
    }
  }
  ... on Domain {
    properties {
      name
      description
    }
  }
  ... on DataProduct {
    properties {
      name
      description
    }
  }
  ... on DataJob {
    platform {
      name
    }
    properties {
      name
      description
    }
  }
  ... on DataFlow {
    platform {
      name
    }
    properties {
      name
      description
    }
  }
  ... on Tag {
    properties {
      name
      description
    }
  }
  ... on CorpUser {
    properties {
      displayName
      fullName
    }
  }
  ... on CorpGroup {
    properties {
      displayName
      description
    }
  }
  ... on MLModel {
    platform {
      name
    }
    properties {
      name
      description
    }
  }
  ... on MLModelGroup {
    platform {
      name
    }
    properties {
      name
      description
    }
  }
  ... on MLFeature {
    platform {
      name
    }
    properties {
      name
      description
    }
  }
  ... on MLFeatureTable {
    platform {
      name
    }
    properties {
      name
      description
    }
  }
  ... on MLPrimaryKey {
    platform {
      name
    }
    properties {
      name
      description
    }
  }
}

fragment FacetEntityInfo on Entity {
  ... on Dataset {
    name
    properties {
      name
    }
  }
  ... on Container {
    subTypes {
      typeNames
    }
    properties {
      name
    }
  }
  ... on GlossaryTerm {
    properties {
      name
    }
  }
  ... on Domain {
    properties {
      name
    }
  }
  ... on Tag {
    properties {
      name
    }
  }
  ... on StructuredProperty {
    properties {
      displayName
    }
  }
}

query search(
  $types: [EntityType!]
  $query: String!
  $orFilters: [AndFilterInput!]
  $count: Int!
  $start: Int!
  $viewUrn: String
  $sortInput: SearchSortInput
) {
  searchAcrossEntities(
    input: {
      query: $query
      count: $count
      start: $start
      types: $types
      orFilters: $orFilters
      viewUrn: $viewUrn
      sortInput: $sortInput
      searchFlags: { skipHighlighting: true, maxAggValues: 5 }
    }
  ) {
    start
    count
    total
    searchResults {
      entity {
        ...SearchEntityInfo
      }
      # TODO: Consider adding these fields for enhanced search experience:
      # score               # BM25 score for keyword search relevance
    }
    facets {
      field
      displayName
      aggregations {
        value
        count
        displayName
        entity {
          ...FacetEntityInfo
        }
      }
    }
    # TODO: Consider adding metadata section for search algorithm transparency:
    # metadata {
    #   scoringMethod       # e.g., "BM25" vs "COSINE_SIMILARITY"
    # }
  }
}
