apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datahub-gms.fullname" . }}-configmap
  labels:
    {{- include "datahub-gms.labels" . | nindent 4 }}
data:
  ebean.datasource.host: "{{ .Values.global.sql.datasource.host }}"
  ebean.datasource.url: "{{ .Values.global.sql.datasource.url }}"
  ebean.datasource.driver: "{{ .Values.global.sql.datasource.driver }}"
  kafka.bootstrap.server: "{{ .Values.global.kafka.bootstrap.server }}"
  kafka.schemaregistry.url: "{{ .Values.global.kafka.schemaregistry.url }}"
  elasticsearch.host: "{{ .Values.global.elasticsearch.host }}"
  elasticsearch.port: "{{ .Values.global.elasticsearch.port }}"
  neo4j.host: "{{ .Values.global.neo4j.host }}"
  neo4j.uri: "{{ .Values.global.neo4j.uri }}"