fragment AssertionDataset on Dataset {
  urn
  properties {
    name
    qualifiedName
  }
  platform {
    urn
    properties {
      displayName
    }
  }
  subTypes {
    typeNames
  }
}

fragment AssertionStdParameterDetails on AssertionStdParameters {
  value {
    value
    type
  }
  minValue {
    value
    type
  }
  maxValue {
    value
    type
  }
}

fragment AssertionDetails on Assertion {
  urn
  type
  platform {
    urn
    properties {
      displayName
      logoUrl
    }
    info {
      displayName
      logoUrl
    }
  }
  info {
    type
    datasetAssertion {
      scope
      aggregation
      operator
      parameters {
        ...AssertionStdParameterDetails
      }
      fields {
        urn
        path
      }
      nativeType
      nativeParameters {
        key
        value
      }
      logic
    }
    freshnessAssertion {
      type
      schedule {
        type
        cron {
          cron
          timezone
          windowStartOffsetMs
        }
        fixedInterval {
          unit
          multiple
        }
      }
      filter {
        type
        sql
      }
    }
    volumeAssertion {
      type
      rowCountTotal {
        operator
        parameters {
          ...AssertionStdParameterDetails
        }
      }
      rowCountChange {
        type
        operator
        parameters {
          ...AssertionStdParameterDetails
        }
      }
      incrementingSegmentRowCountTotal {
        segment {
          field {
            path
            type
            nativeType
          }
          transformer {
            type
            nativeType
          }
        }
        operator
        parameters {
          ...AssertionStdParameterDetails
        }
      }
      incrementingSegmentRowCountChange {
        type
        segment {
          field {
            path
            type
            nativeType
          }
          transformer {
            type
            nativeType
          }
        }
        operator
        parameters {
          ...AssertionStdParameterDetails
        }
      }
      filter {
        type
        sql
      }
    }
    sqlAssertion {
      type
      statement
      changeType
      operator
      parameters {
        ...AssertionStdParameterDetails
      }
    }
    source {
      type
    }
  }
  relationships(
    input: { types: "Asserts", direction: OUTGOING, start: 0, count: 1 }
  ) {
    start
    count
    total
    relationships {
      entity {
        ... on Dataset {
          ...AssertionDataset
        }
      }
    }
  }
}

query getAssertion($assertionUrn: String!) {
  assertion(urn: $assertionUrn) {
    urn
    ...AssertionDetails
  }
}
