import os

SNOWFLAKE_PLATFORM_NAME = "snowflake"
REDSHIFT_PLATFORM_NAME = "redshift"
BIGQUERY_PLATFORM_NAME = "bigquery"
DATABRICKS_PLATFORM_NAME = "databricks"
SNOWFLAKE_PLATFORM_URN = f"urn:li:dataPlatform:{SNOWFLAKE_PLATFORM_NAME}"
REDSHIFT_PLATFORM_URN = f"urn:li:dataPlatform:{REDSHIFT_PLATFORM_NAME}"
BIGQUERY_PLATFORM_URN = f"urn:li:dataPlatform:{BIGQUERY_PLATFORM_NAME}"
DATABRICKS_PLATFORM_URN = f"urn:li:dataPlatform:{DATABRICKS_PLATFORM_NAME}"
CLI_EXECUTOR_ID = "__datahub_cli_"

LIST_MONITORS_BATCH_SIZE = int(os.getenv("LIST_MONITORS_BATCH_SIZE", 100))
LIST_INGESTION_SOURCES_BATCH_SIZE = int(
    os.getenv("LIST_INGESTION_SOURCES_BATCH_SIZE", 25)
)

RUN_INGEST_TASK_NAME = "RUN_INGEST"
RUN_ASSERTION_TASK_NAME = "RUN_ASSERTION"

DATAHUB_REMOTE_EXECUTOR_ENTITY_NAME = "dataHubRemoteExecutor"
DATAHUB_REMOTE_EXECUTOR_STATUS_ASPECT_NAME = "dataHubRemoteExecutorStatus"

DATAHUB_EXECUTION_REQUEST_ENTITY_NAME = "dataHubExecutionRequest"
DATAHUB_EXECUTION_REQUEST_KEY_ASPECT_NAME = "dataHubExecutionRequestKey"
DATAHUB_EXECUTION_REQUEST_INPUT_ASPECT_NAME = "dataHubExecutionRequestInput"
DATAHUB_EXECUTION_REQUEST_SIGNAL_ASPECT_NAME = "dataHubExecutionRequestSignal"
DATAHUB_EXECUTION_REQUEST_RESULT_ASPECT_NAME = "dataHubExecutionRequestResult"

DATAHUB_EXECUTION_REQUEST_SQS_TRUNCATED_ASPECT_NAME = "EXECUTOR_SQS_TRUNCATED"

DATAHUB_EXECUTION_REQUEST_STATUS_RUNNING = "RUNNING"
DATAHUB_EXECUTION_REQUEST_STATUS_DUPLICATE = "DUPLICATE"
DATAHUB_EXECUTION_REQUEST_STATUS_PENDING = "PENDING"

# We assume that records created before this date were not indexed and will be skipped:
DATAHUB_EXECUTION_REQUEST_INDEX_THRESHOLD_MS = 1727740800000  # 2024-10-01
DATAHUB_URN_MAX_LEN = 500
