import os

SNOWFLAKE_PLATFORM_NAME = "snowflake"
REDSHIFT_PLATFORM_NAME = "redshift"
BIGQUERY_PLATFORM_NAME = "bigquery"
DATABRICKS_PLATFORM_NAME = "databricks"
SNOWFLAKE_PLATFORM_URN = f"urn:li:dataPlatform:{SNOWFLAKE_PLATFORM_NAME}"
REDSHIFT_PLATFORM_URN = f"urn:li:dataPlatform:{REDSHIFT_PLATFORM_NAME}"
BIGQUERY_PLATFORM_URN = f"urn:li:dataPlatform:{BIGQUERY_PLATFORM_NAME}"
DATABRICKS_PLATFORM_URN = f"urn:li:dataPlatform:{DATABRICKS_PLATFORM_NAME}"
CLI_EXECUTOR_ID = "__datahub_cli_"

LIST_MONITORS_BATCH_SIZE = int(os.getenv("LIST_MONITORS_BATCH_SIZE", 100))
LIST_INGESTION_SOURCES_BATCH_SIZE = int(
    os.getenv("LIST_INGESTION_SOURCES_BATCH_SIZE", 25)
)

RUN_INGEST_TASK_NAME = "RUN_INGEST"
RUN_ASSERTION_TASK_NAME = "RUN_ASSERTION"

DATAHUB_EXECUTION_REQUEST_ENTITY_NAME = "dataHubExecutionRequest"
DATAHUB_EXECUTION_REQUEST_INPUT_ASPECT_NAME = "dataHubExecutionRequestInput"
DATAHUB_EXECUTION_REQUEST_SIGNAL_ASPECT_NAME = "dataHubExecutionRequestSignal"
