DEFAULT_OPERATION_TYPES_FILTER = '"INSERT" OR "UPDATE" OR "CREATE_TABLE" OR "CREATE_TABLE_AS_SELECT" OR "CREATE_EXTERNAL_TABLE" OR "CREATE_SNAPSHOT_TABLE" OR "MERGE" OR "CREATE_SCHEMA" OR "CREATE_VIEW" OR "CREATE_MATERIALIZED_VIEW" OR "CREATE_MODEL" OR "SELECT" OR "ALTER_TABLE"'  # Note that SELECT is included because BigQuery can register some types of queries (e.g. Query results materialization via API or CTAS statements)

SUPPORTED_LAST_MODIFIED_COLUMN_TYPES = ["DATE", "DATETIME", "TIMESTAMP"]

SUPPORTED_HIGH_WATERMARK_COLUMN_TYPES = [
    "INT64",
    "INT",
    "SMALLINT",
    "INTEGER",
    "BIGINT",
    "TINYINT",
    "BYTEINT",
    "NUMERIC",
    "DECIMAL",
    "BIGNUMERIC",
    "BIGDECIMAL",
    "FLOAT64",
    "DATE",
    "DATETIME",
    "TIMESTAMP",
]

HIGH_WATERMARK_DATE_AND_TIME_TYPES = ["DATE", "DATETIME", "TIMESTAMP"]
