plugins {
  id 'java-library'
  id 'pegasus'
}

dependencies {
  dataModel project(path: ':li-utils', configuration: 'dataTemplate')
}

def metadataModelsPegasusDir = file("${rootProject.projectDir}/metadata-models/src/main/pegasus")
def stagedPegasusDir = layout.buildDirectory.dir("staged/pegasus")
def stagedPegasusSrcDir = file("src/main/pegasus")

task copyMetadataModels(type: Sync) {
  from(metadataModelsPegasusDir)
  into(stagedPegasusDir)

  inputs.dir(metadataModelsPegasusDir)
      .withPropertyName("metadataModelsPegasusDir")
      .withPathSensitivity(PathSensitivity.RELATIVE)
  outputs.dir(stagedPegasusDir)
      .withPropertyName("stagedPegasusDir")
  outputs.cacheIf { true }
}

task syncStagedPegasusToSrc(type: Sync, dependsOn: copyMetadataModels) {
  from(stagedPegasusDir)
  into(stagedPegasusSrcDir)
}

[generateAvroSchema, validateSchemaAnnotation, mainTranslateSchemas, generateDataTemplate,
 mainCopySchemas, processResources].each { task ->
  task.dependsOn(syncStagedPegasusToSrc)
}

pegasus.main.generationModes = [PegasusGenerationMode.PEGASUS, PegasusGenerationMode.AVRO]

[generateAvroSchema, generateDataTemplate, mainTranslateSchemas].each { task ->
  task.outputs.cacheIf { true }
}

def avroSchemaInputDir = file("src/mainGeneratedAvroSchema/avro")
def renamedAvroBuildDir = layout.buildDirectory.dir("renamed/avro")
def renamedAvroSrcDir = file("src/renamed/avro")

task renameNamespace(type: Sync, dependsOn: generateAvroSchema) {
  from(avroSchemaInputDir)
  into(renamedAvroBuildDir)

  inputs.dir(avroSchemaInputDir)
      .withPropertyName("avroSchemaInputDir")
      .withPathSensitivity(PathSensitivity.RELATIVE)
  outputs.dir(renamedAvroBuildDir)
      .withPropertyName("renamedAvroBuildDir")
  outputs.cacheIf { true }

  doLast {
    execOps.exec {
      commandLine 'bash', './rename-namespace.sh', renamedAvroBuildDir.get().asFile.absolutePath
    }
  }
}

task syncRenamedAvroToSrc(type: Sync, dependsOn: renameNamespace) {
  from(renamedAvroBuildDir)
  into(renamedAvroSrcDir)
}

renameNamespace.finalizedBy(syncRenamedAvroToSrc)
build.dependsOn(syncRenamedAvroToSrc)

clean {
  delete stagedPegasusDir
  delete stagedPegasusSrcDir
  delete 'src/mainGeneratedAvroSchema/avro'
  delete renamedAvroBuildDir
  delete renamedAvroSrcDir
  delete 'bin'
}

// This project only contains generated code, so disable Spotless
tasks.withType(com.diffplug.gradle.spotless.SpotlessTask).configureEach {
  enabled = false
}
