package com.linkedin.datahub.graphql.resolvers.connection;

import com.google.common.collect.ImmutableSet;
import com.linkedin.common.urn.Urn;
import com.linkedin.datahub.graphql.QueryContext;
import com.linkedin.datahub.graphql.concurrency.GraphQLConcurrencyUtils;
import com.linkedin.datahub.graphql.exception.DataHubGraphQLErrorCode;
import com.linkedin.datahub.graphql.exception.DataHubGraphQLException;
import com.linkedin.datahub.graphql.generated.ExecutionRequest;
import com.linkedin.datahub.graphql.generated.ExecutionRequestResult;
import com.linkedin.datahub.graphql.types.ingestion.ExecutionRequestMapper;
import com.linkedin.entity.EntityResponse;
import com.linkedin.entity.EnvelopedAspect;
import com.linkedin.entity.EnvelopedAspectMap;
import com.linkedin.entity.client.EntityClient;
import com.linkedin.metadata.Constants;
import graphql.schema.DataFetcher;
import graphql.schema.DataFetchingEnvironment;
import java.util.concurrent.CompletableFuture;

/**
 * Retrieves a Connection Test Execution Request by primary key (urn). Similar to {@link
 * com.linkedin.datahub.graphql.resolvers.ingest.execution.GetIngestionExecutionRequestResolver}
 * However, this does not enforce the same policies as notification tests can be triggered by
 * anyone. It does, however, only fetch {@link ExecutionRequest}s that were generated by {@link
 * CreateNotificationConnectionTestResolver}
 */
public class GetNotificationConnectionTestResultResolver
    implements DataFetcher<CompletableFuture<ExecutionRequestResult>> {
  private final EntityClient _entityClient;

  public GetNotificationConnectionTestResultResolver(final EntityClient entityClient) {
    _entityClient = entityClient;
  }

  @Override
  public CompletableFuture<ExecutionRequestResult> get(final DataFetchingEnvironment environment)
      throws Exception {

    final QueryContext context = environment.getContext();
    final String urnStr = environment.getArgument("urn");
    return GraphQLConcurrencyUtils.supplyAsync(
        () -> {
          try {
            // 1. Fetch specific execution request
            final Urn urn = Urn.createFromString(urnStr);
            final EntityResponse entity =
                _entityClient.getV2(
                    context.getOperationContext(),
                    Constants.EXECUTION_REQUEST_ENTITY_NAME,
                    urn,
                    ImmutableSet.of(
                        Constants.EXECUTION_REQUEST_RESULT_ASPECT_NAME,
                        Constants.EXECUTION_REQUEST_INPUT_ASPECT_NAME));

            // 2. No execution request found
            if (entity == null) {
              throw new DataHubGraphQLException(
                  String.format("Failed to find Execution Request with urn %s", urn),
                  DataHubGraphQLErrorCode.NOT_FOUND);
            }

            // 3. Execution request found
            // 3.1 Extract aspects
            final EnvelopedAspectMap aspects = entity.getAspects();
            final EnvelopedAspect envelopedInput =
                aspects.get(Constants.EXECUTION_REQUEST_INPUT_ASPECT_NAME);
            final EnvelopedAspect envelopedResult =
                aspects.get(Constants.EXECUTION_REQUEST_RESULT_ASPECT_NAME);
            if (envelopedInput == null || envelopedResult == null) {
              throw new RuntimeException(
                  String.format(
                      "Result or Input aspects missing from entity client response for execution request with urn %s",
                      urn));
            }
            final com.linkedin.execution.ExecutionRequestInput executionRequestInput =
                new com.linkedin.execution.ExecutionRequestInput(envelopedInput.getValue().data());
            final com.linkedin.execution.ExecutionRequestResult executionRequestResult =
                new com.linkedin.execution.ExecutionRequestResult(
                    envelopedResult.getValue().data());

            // 3.2  Make sure it corresponds to a connection test (else it'll violate ingestion
            // management policies)
            if (!checkIsValidConnectionTestRequest(executionRequestInput)) {
              throw new RuntimeException(
                  String.format(
                      "ExecutionRequest not found for a connection test request with urn %s", urn));
            }
            // 3.3 Map to gql type and return results
            return ExecutionRequestMapper.mapExecutionRequestResult(executionRequestResult);
          } catch (Exception e) {
            throw new RuntimeException("Failed to retrieve execution request", e);
          }
        },
        this.getClass().getSimpleName(),
        "get");
  }

  private boolean checkIsValidConnectionTestRequest(
      com.linkedin.execution.ExecutionRequestInput requestInput) {
    if (!requestInput.hasTask()) {
      return false;
    }
    return requestInput
        .getTask()
        .equals(Constants.NOTIFICATION_CONNECTION_TEST_EXECUTION_REQUEST_TASK_NAME);
  }
}
