fragment AssertionDataset on Dataset {
  urn
  properties {
    name
    qualifiedName
  }
  platform {
    urn
    properties {
      displayName
    }
  }
  subTypes {
    typeNames
  }
  exists
}

fragment AssertionStdParameterDetails on AssertionStdParameters {
  value {
    value
    type
  }
  minValue {
    value
    type
  }
  maxValue {
    value
    type
  }
}

fragment assertionInfoDetails on AssertionInfo {
      type
    datasetAssertion {
      scope
      aggregation
      operator
      parameters {
        ...AssertionStdParameterDetails
      }
      fields {
        urn
        path
      }
      nativeType
      nativeParameters {
        key
        value
      }
      logic
    }
    freshnessAssertion {
      type
      schedule {
        type
        cron {
          cron
          timezone
          windowStartOffsetMs
        }
        fixedInterval {
          unit
          multiple
        }
      }
      filter {
        type
        sql
      }
    }
    volumeAssertion {
      type
      rowCountTotal {
        operator
        parameters {
          ...AssertionStdParameterDetails
        }
      }
      rowCountChange {
        type
        operator
        parameters {
          ...AssertionStdParameterDetails
        }
      }
      incrementingSegmentRowCountTotal {
        segment {
          field {
            path
            type
            nativeType
          }
          transformer {
            type
            nativeType
          }
        }
        operator
        parameters {
          ...AssertionStdParameterDetails
        }
      }
      incrementingSegmentRowCountChange {
        type
        segment {
          field {
            path
            type
            nativeType
          }
          transformer {
            type
            nativeType
          }
        }
        operator
        parameters {
          ...AssertionStdParameterDetails
        }
      }
      filter {
        type
        sql
      }
    }
    sqlAssertion {
      type
      statement
      changeType
      operator
      parameters {
        ...AssertionStdParameterDetails
      }
    }
    fieldAssertion {
      type
      fieldValuesAssertion {
        field {
          path
          type
          nativeType
        }
        transform {
          type
        }
        operator
        parameters {
          ...AssertionStdParameterDetails
        }
        failThreshold {
          type
          value
        }
        excludeNulls
      }
      fieldMetricAssertion {
        field {
          path
          type
          nativeType
        }
        metric
        operator
        parameters {
          ...AssertionStdParameterDetails
        }
      }
      filter {
        type
        sql
      }
    }
    schemaAssertion {
      compatibility
      fields {
        path
        type
        nativeType
      }
    }
    source {
      type
    }
}

fragment AssertionDetails on Assertion {
  urn
  type
  platform {
    urn
    properties {
      displayName
      logoUrl
    }
    info {
      displayName
      logoUrl
    }
  }
  info {
    ...assertionInfoDetails
  }
  inferenceDetails {
    adjustmentSettings {
      algorithm
      algorithmName
      context {
        key
        value
      }
    }
  }
  rawInfoAspect: aspects(
      input: { aspectNames : [ "assertionInfo" ] }
  ){
    aspectName
    payload
  }
  relationships(
    input: { types: "Asserts", direction: OUTGOING, start: 0, count: 1, includeSoftDelete: true }
  ) {
    start
    count
    total
    relationships {
      entity {
        ... on Dataset {
          ...AssertionDataset
        }
      }
    }
  }
}

fragment MonitorSearchResults on SearchResults {
  start
  count
  total
  searchResults {
    entity {
      ... on Monitor {
        urn
        info {
          type
          status {
            mode
          }
          executorId
          assertionMonitor {
            assertions {
              assertion {
                ...AssertionDetails
              }
              schedule {
                cron
                timezone
              }
              parameters {
                type
                datasetFreshnessParameters {
                  sourceType
                  field {
                    type
                    nativeType
                    path
                    kind
                  }
                  auditLog {
                    operationTypes
                    userName
                  }
                }
                datasetVolumeParameters {
                  sourceType
                }
                datasetFieldParameters {
                  sourceType
                  changedRowsField {
                    kind
                    path
                    type
                    nativeType
                  }
                }
                datasetSchemaParameters {
                  sourceType
                }
              }
              rawParameters
              context {
                stdDev
                embeddedAssertions {
                  assertion {
                    ...assertionInfoDetails
                  }
                  rawAssertion
                  evaluationTimeWindow {
                    startTimeMillis
                    endTimeMillis
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

query searchAcrossEntities($input: SearchAcrossEntitiesInput!) {
  searchAcrossEntities(input: $input) {
    ...MonitorSearchResults
  }
}
