fragment IngestionSourceResults on ListIngestionSourcesResult {
  start
  count
  total
  ingestionSources {
    urn
    type
    config {
      recipe
      executorId
    }
  }
}

query listIngestionSources($input: ListIngestionSourcesInput!) {
    listIngestionSources(input: $input) {
        ...IngestionSourceResults
    }
}