plugins {
    id 'org.hidetake.swagger.generator'
    id 'java-library'
}

apply from: '../../gradle/coverage/java-coverage.gradle'

dependencies {
// Dependencies for open api
    implementation externalDependency.reflections
    implementation externalDependency.springCore
    implementation externalDependency.springWeb
    implementation externalDependency.springWebMVC
    implementation externalDependency.springBeans
    implementation externalDependency.springContext
    implementation externalDependency.antlr4Runtime
    implementation externalDependency.antlr4
    implementation externalDependency.servletApi
    implementation externalDependency.jakartaValidation
    implementation externalDependency.jakartaAnnotationApi
    implementation platform(externalDependency.jacksonBom)
    implementation externalDependency.jacksonDataBind
    implementation externalDependency.slf4jApi

    // End of dependencies
    implementation externalDependency.swaggerAnnotations
    swaggerCodegen externalDependency.swaggerCli

    testImplementation externalDependency.assertJ
}

def openApiInputFile = file("$projectDir/src/main/resources/schema-registry-open-api-v7.9.1.yaml")
def openApiTemplateDir = file("$projectDir/src/main/resources/JavaSpring")
def generatedOpenApiDir = layout.buildDirectory.dir("openapi/generated")
def committedGeneratedOpenApiDir = file("$projectDir/generated")

tasks.register('generateOpenApiPojos', GenerateSwaggerCode) {
    onlyIf { openApiInputFile.text.trim() }
    inputFile = openApiInputFile
    outputDir = generatedOpenApiDir.get().asFile
    language = "spring"
    components = [models: true, apis: true, apiTests: false]
    templateDir = openApiTemplateDir
    additionalProperties = [
        "group-id"           : "io.datahubproject",
        "dateLibrary"        : "java8",
        "java11"             : "true",
        "modelPropertyNaming": "original",
        "modelPackage"       : "io.datahubproject.schema-registry.openapi.generated",
    ]
    outputs.cacheIf { true }
}

tasks.register('stageCommittedOpenApiPojos', Sync) {
    onlyIf { !openApiInputFile.text.trim() }
    from(committedGeneratedOpenApiDir)
    into(generatedOpenApiDir)
    outputs.dir(generatedOpenApiDir)
}

tasks.register('prepareOpenApiPojos') {
    dependsOn tasks.named('generateOpenApiPojos')
    dependsOn tasks.named('stageCommittedOpenApiPojos')
}

sourceSets.main.java.srcDir("$buildDir/openapi/generated/src/main/java")
sourceSets.main.resources.srcDir("$buildDir/openapi/generated/src/main/resources")

compileJava.dependsOn('prepareOpenApiPojos')

clean {
    delete generatedOpenApiDir
}
