package com.linkedin.datahub.graphql.codegen;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Writes MCP {@code list_entity_incidents.gql} from {@code incident.graphql}. Types that existed on
 * older GMS stay untagged; every type added after that frozen set gets {@code #[NEWER_GMS]}.
 */
public final class GenerateListIncidentsQuery {

  /**
   * Types whose {@code incidents} field existed on older GMS. Do not add names here: new SDL types
   * must be tagged {@code #[NEWER_GMS]} so MCP can strip them on old servers.
   */
  static final List<String> LEGACY_GMS_INCIDENT_TYPES =
      List.of("Dataset", "DataJob", "DataFlow", "Dashboard", "Chart");

  private static final Set<String> LEGACY_GMS_INCIDENT_TYPE_SET =
      Set.copyOf(LEGACY_GMS_INCIDENT_TYPES);

  private GenerateListIncidentsQuery() {}

  public static void main(String[] args) throws IOException {
    if (args.length != 2) {
      throw new IllegalArgumentException(
          "Usage: GenerateListIncidentsQuery <incident.graphql> <list_entity_incidents.gql>");
    }
    Path sdlPath = Path.of(args[0]);
    Path outPath = Path.of(args[1]);
    List<String> types = IncidentSdl.typesDeclaringIncidentsField(Files.readString(sdlPath));
    if (types.isEmpty()) {
      throw new IllegalStateException(
          sdlPath
              + " declares no incidents: EntityIncidentsResult fields; refusing to generate an empty query");
    }
    Path parent = outPath.toAbsolutePath().getParent();
    if (parent != null) {
      Files.createDirectories(parent);
    }
    Files.writeString(outPath, render(types), StandardCharsets.UTF_8);
  }

  static String render(List<String> types) {
    StringBuilder typeBlocks = new StringBuilder();
    for (String type : orderTypes(types)) {
      typeBlocks.append(renderTypeBlock(type));
    }
    return HEADER + typeBlocks + FOOTER;
  }

  static List<String> orderTypes(List<String> types) {
    LinkedHashSet<String> remaining = new LinkedHashSet<>(types);
    List<String> ordered = new ArrayList<>();
    for (String legacy : LEGACY_GMS_INCIDENT_TYPES) {
      if (remaining.remove(legacy)) {
        ordered.add(legacy);
      }
    }
    List<String> rest = new ArrayList<>(remaining);
    Collections.sort(rest);
    ordered.addAll(rest);
    return ordered;
  }

  private static String renderTypeBlock(String type) {
    String block =
        "        ... on "
            + type
            + " {\n"
            + "            incidents(state: $state, start: $start, count: $count) {\n"
            + "                ...entityIncidentsResultFields\n"
            + "            }\n"
            + "        }\n";
    if (LEGACY_GMS_INCIDENT_TYPE_SET.contains(type)) {
      return block;
    }
    return block
            .lines()
            .map(line -> line.isEmpty() ? line : line + " #[NEWER_GMS]")
            .collect(Collectors.joining("\n"))
        + "\n";
  }

  private static final String HEADER =
      """
      # Generated from datahub-graphql-core/src/main/resources/incident.graphql.
      # Do not edit. Regenerated by ./gradlew :datahub-graphql-core:generateListIncidentsGql

      query listEntityIncidents(
          $urn: String!,
          $state: IncidentState,
          $start: Int!,
          $count: Int!
      ) {
          entity(urn: $urn) {
              urn
              type
      """;

  private static final String FOOTER =
      """
          }
      }

      fragment entityIncidentsResultFields on EntityIncidentsResult {
          start
          count
          total
          incidents {
              urn
              incidentType
              customType
              title
              description
              priority
              incidentStatus {
                  state
                  stage
                  message
                  lastUpdated {
                      time
                      actor
                  }
              }
              source {
                  type
              }
              created {
                  time
                  actor
              }
          }
      }
      """;
}
