SELECT WI.WIDGET_ID,
       DBD.DBDNAM AS DB_DESCRIPTION,
       DBT.DBTYPE_NAME,
       SRC.OWNERNAME AS DB_NAME,
       SRC.SOURCE_NAME,
       SRC.SRC_DESC AS DESCRIPTION
FROM {metadata_schema}.OPB_WIDGET_INST WI
         LEFT OUTER JOIN {metadata_schema}.OPB_SRC SRC
LEFT OUTER JOIN {metadata_schema}.OPB_DBD DBD ON DBD.DBDID = SRC.DBDID
LEFT OUTER JOIN {metadata_schema}.OPB_MMD_DBTYPE DBT ON DBD.DBTYPE = DBT.DBTYPE_ID
ON SRC.SRC_ID = WI.WIDGET_ID
WHERE WI.MAPPING_ID = :mapping_id
  AND WI.WIDGET_TYPE = 1