SELECT WI.WIDGET_ID, SRC.OWNERNAME AS DB_NAME, SRC.SOURCE_NAME, SRC.SRC_DESC AS DESCRIPTION
FROM {metadata_schema}.OPB_WIDGET_INST WI
         LEFT OUTER JOIN {metadata_schema}.OPB_SRC SRC
ON SRC.SRC_ID = WI.WIDGET_ID
WHERE WI.MAPPING_ID = :mapping_id
  AND WI.WIDGET_TYPE = 1