SELECT DISTINCT WI.WIDGET_ID,
       SRC.SRC_ID,
       FLD.SRC_NAME AS COL_NAME,
       FLD.BUSINESS_NAME AS COL_DESC,
       DBD.DBTYPE,
       DT.DATATYPE_NAME,
       FLD.FLDNO AS FLD_NO,
       FLD.NULLTYPE AS NULLTYPE,
       FLD.KEYTYPE AS KEYTYPE
FROM {metadata_schema}.OPB_WIDGET_INST WI
LEFT OUTER JOIN {metadata_schema}.OPB_SRC SRC ON SRC.SRC_ID = WI.WIDGET_ID
LEFT OUTER JOIN {metadata_schema}.OPB_DBD DBD ON DBD.DBDID = SRC.DBDID
LEFT OUTER JOIN {metadata_schema}.OPB_SRC_FLD FLD ON SRC.SRC_ID = FLD.SRC_ID
LEFT OUTER JOIN {metadata_schema}.OPB_PICDSC PIC ON PIC.PICID = FLD.PICID
LEFT OUTER JOIN (select * from
(select DT.*, ROW_NUMBER() OVER(PARTITION BY native_datatype, PM_DATATYPE ORDER BY order_num) as rn from {metadata_schema}.OPB_MMD_DATATYPE DT
) A
where rn = 1) DT ON PIC.SRC_NTYPE = DT.NATIVE_DATATYPE AND DT.PM_DATATYPE = PIC.SRC_TYPE
WHERE WI.MAPPING_ID = :mapping_id
  AND WI.WIDGET_TYPE = 1
order by SRC.SRC_ID, FLD.FLDNO