"""Guards that every ingestion connector's data platform is registered in the
backend ``data-platforms`` bootstrap seed with a locally-hosted logo.

Background: the home-page "Platforms" module and the platform
browse/facets read the ``DataPlatformInfo`` aspect. A connector whose platform
is not registered in ``data-platforms.yaml`` ends up with no ``DataPlatformInfo``
(so no display name and no logo). QuickSight was searchable yet missing from the
Platforms module for exactly this reason. This test fails when a *new* connector
is added without registering its platform, so the gap is caught at PR time
instead of in production.

The set of platforms checked is derived dynamically from the autogenerated
connector registry, so it grows automatically as connectors are added. Only a
small, explicitly-documented set of framework / pseudo sources that do not
represent a browsable external data platform is exempted; everything else is
enforced fail-closed.
"""

import json
import re
from pathlib import Path
from typing import Dict, List, Optional, Set

import pytest
import yaml

_HERE = Path(__file__).resolve()
_METADATA_INGESTION_DIR = _HERE.parents[2]
_REPO_ROOT = _HERE.parents[3]

_CONNECTOR_REGISTRY = (
    _METADATA_INGESTION_DIR
    / "src/datahub/ingestion/autogenerated/connector_registry/datahub.json"
)
_DATA_PLATFORMS_SEED = (
    _REPO_ROOT
    / "metadata-service/configuration/src/main/resources/bootstrap_mcps/data-platforms.yaml"
)
_INGESTION_SOURCE_DIR = _METADATA_INGESTION_DIR / "src/datahub/ingestion/source"

# Sources whose ``platform_id`` does not represent a browsable external data
# platform (DataHub-internal utilities, file/format ingestors, and generic
# mechanisms whose real platform is configured per-recipe). These legitimately
# have no platform tile / logo, so they are exempt from the registration check.
# This is the ONLY hard-coded input; the enforced set is (registry - exemptions),
# so any newly-added connector is checked by default (fail-closed).
_NON_DATA_PLATFORM_SOURCES: Set[str] = {
    "datahub",  # DataHub-to-DataHub meta source
    "datahub-documents",
    "datahubapply",
    "datahubdebug",
    "datahubgc",
    "demo-data",  # sample-data generator
    "business-glossary",  # emits glossary terms, not platform-scoped assets
    "csv-enricher",  # enrichment, no platform
    "file-based-lineage",  # file ingestor
    "metadata-file",  # file ingestor
    "json-schema",  # schema-format ingestor
    "sql-queries",  # query-log parser; platform is configured per-recipe
    "sqlalchemy",  # generic SQLAlchemy; platform is configured per-recipe
}

_EXTERNAL_LOGO_RE = re.compile(r"""(logoUrl|LOGO_URL)\s*=\s*[a-zA-Z]?["']https?://""")


def _require(path: Path) -> None:
    if not path.exists():
        pytest.skip(f"required file not present in this checkout: {path}")


def _connector_platform_ids() -> Set[str]:
    _require(_CONNECTOR_REGISTRY)
    registry = json.loads(_CONNECTOR_REGISTRY.read_text())
    return {
        details["platform_id"]
        for details in registry["plugin_details"].values()
        if details.get("platform_id")
    }


def _seed_platform_logos() -> Dict[str, Optional[str]]:
    """Map platform id -> logoUrl (None if the entry has no logo) from the seed."""
    _require(_DATA_PLATFORMS_SEED)
    entries = yaml.safe_load(_DATA_PLATFORMS_SEED.read_text())
    logos: Dict[str, Optional[str]] = {}
    for entry in entries:
        urn = entry.get("entityUrn", "")
        prefix = "urn:li:dataPlatform:"
        if urn.startswith(prefix):
            logos[urn[len(prefix) :]] = (entry.get("aspect") or {}).get("logoUrl")
    return logos


def test_connector_platforms_registered_in_seed() -> None:
    """Every connector platform (minus framework exemptions) must have a
    ``DataPlatformInfo`` entry in the bootstrap seed."""
    seed = _seed_platform_logos()
    to_check = _connector_platform_ids() - _NON_DATA_PLATFORM_SOURCES
    missing = sorted(pid for pid in to_check if pid not in seed)
    assert not missing, (
        f"{len(missing)} connector platform(s) are not registered in "
        f"{_DATA_PLATFORMS_SEED.relative_to(_REPO_ROOT)}: {missing}. "
        "Add a dataPlatformInfo entry (name, displayName, local logoUrl) for each, "
        "vendor the logo into datahub-web-react/src/images/, and if a source is not "
        "a browsable data platform add it to _NON_DATA_PLATFORM_SOURCES with a reason."
    )


def test_seed_logo_urls_are_local() -> None:
    """Seed logos must be self-hosted (no external URLs)."""
    seed = _seed_platform_logos()
    external = sorted(
        f"{pid} -> {logo}"
        for pid, logo in seed.items()
        if logo and logo.strip().lower().startswith("http")
    )
    assert not external, (
        "Data platform logos must be self-hosted under assets/platforms/, "
        f"not external URLs: {external}"
    )


def test_no_external_logo_urls_in_connector_sources() -> None:
    """Connector sources must not hard-code external logo URLs; register the
    platform (with a vendored logo) in the seed instead."""
    _require(_INGESTION_SOURCE_DIR)
    offenders: List[str] = []
    for py_file in _INGESTION_SOURCE_DIR.rglob("*.py"):
        for lineno, line in enumerate(py_file.read_text().splitlines(), start=1):
            if _EXTERNAL_LOGO_RE.search(line):
                rel = py_file.relative_to(_METADATA_INGESTION_DIR)
                offenders.append(f"{rel}:{lineno}: {line.strip()}")
    assert not offenders, (
        "External logo URLs are not allowed in connector sources; vendor the logo "
        "into datahub-web-react/src/images/ and reference assets/platforms/<file>:\n"
        + "\n".join(offenders)
    )
