"""Guards that every ingestion connector's data platform is registered in the
backend ``data-platforms`` bootstrap seed with a locally-hosted logo.

Background: the home-page "Platforms" module and the platform browse/facets read
the ``DataPlatformInfo`` aspect. A connector whose platform is not registered in
``data-platforms.yaml`` ends up with no ``DataPlatformInfo`` (so no display name
and no logo). QuickSight was searchable yet missing from the Platforms module for
exactly this reason. This test fails when a *new* connector is added without
registering its platform, so the gap is caught at PR time instead of in
production.

The set of platforms checked is derived dynamically from the autogenerated
connector registry, so it grows automatically as connectors are added. Only a
small, explicitly-documented set of sources that do not emit their own browsable
data platform is exempted; every other connector is enforced fail-closed.

Matching is case-insensitive: a connector's registry ``platform_id`` is a
lowercased label (e.g. ``openapi``) while the emitted/seed URN may use a
different case (e.g. ``urn:li:dataPlatform:OpenApi``).
"""

import json
import re
from pathlib import Path
from typing import Dict, List, Optional, Set

import pytest
import yaml

_HERE = Path(__file__).resolve()
_METADATA_INGESTION_DIR = _HERE.parents[2]
_REPO_ROOT = _HERE.parents[3]

_CONNECTOR_REGISTRY = (
    _METADATA_INGESTION_DIR
    / "src/datahub/ingestion/autogenerated/connector_registry/datahub.json"
)
_DATA_PLATFORMS_SEED = (
    _REPO_ROOT
    / "metadata-service/configuration/src/main/resources/bootstrap_mcps/data-platforms.yaml"
)
_INGESTION_SOURCE_DIR = _METADATA_INGESTION_DIR / "src/datahub/ingestion/source"
_LOGO_ASSET_DIRS = [
    _REPO_ROOT / "datahub-web-react/src/images",
    _REPO_ROOT / "datahub-web-react/public/assets/platforms",
]

# Sources whose registry ``platform_id`` is NOT a browsable data platform of its
# own, so they must not be registered in the seed. Two kinds:
#   1. DataHub-internal utilities / file / format / generic sources (no platform).
#   2. Sources that emit an existing platform's URN, not their own id -- verified
#      against each source's emitted platform:
#        - hive-metastore -> the configured query engine (hive/presto/trino/...)
#        - powerbi-report-server -> powerbi
#        - matillion-dpc -> matillion
# This is the only hard-coded input; the enforced set is (registry - exemptions),
# so any newly-added connector is checked by default (fail-closed).
_NON_DATA_PLATFORM_SOURCES: Set[str] = {
    # (1) not a data platform
    "datahub",  # DataHub-to-DataHub meta source
    "datahub-documents",
    "datahubapply",
    "datahubdebug",
    "datahubgc",
    "datahub-analytics-compaction",  # SYSTEM; no browsable platform
    "demo-data",  # sample-data generator
    "business-glossary",  # emits glossary terms, not platform-scoped assets
    "csv-enricher",  # enrichment, no platform
    "file-based-lineage",  # file ingestor
    "metadata-file",  # file ingestor
    "json-schema",  # schema-format ingestor
    "sql-queries",  # query-log parser; platform is configured per-recipe
    "sqlalchemy",  # generic SQLAlchemy; platform is configured per-recipe
    # (2) emits an existing platform's URN, not its own id
    "hive-metastore",  # emits the configured engine (hive/presto/trino/...)
    "powerbi-report-server",  # emits the powerbi platform
    "matillion-dpc",  # emits the matillion platform
}

# Best-effort guard for connectors that hard-code an external logo URL inline
# (the common `logoUrl="https://..."` / dict-key / prefixed-string forms).
_EXTERNAL_LOGO_RE = re.compile(
    r"""["']?(?:logoUrl|LOGO_URL|logo_url)["']?\s*[=:]\s*[A-Za-z]{0,2}["']https?://"""
)


def _require(path: Path) -> None:
    if not path.exists():
        pytest.skip(f"required file not present in this checkout: {path}")


def _connector_platform_ids() -> Set[str]:
    _require(_CONNECTOR_REGISTRY)
    registry = json.loads(_CONNECTOR_REGISTRY.read_text())
    return {
        details["platform_id"]
        for details in registry["plugin_details"].values()
        if details.get("platform_id")
    }


def _seed_platform_logos() -> Dict[str, Optional[str]]:
    """Map lower-cased platform id -> logoUrl (None if the entry has no logo).

    Keys are lower-cased so a connector's ``platform_id`` matches its seed entry
    regardless of URN casing (e.g. ``openapi`` -> ``OpenApi``).
    """
    _require(_DATA_PLATFORMS_SEED)
    entries = yaml.safe_load(_DATA_PLATFORMS_SEED.read_text())
    logos: Dict[str, Optional[str]] = {}
    prefix = "urn:li:dataPlatform:"
    for entry in entries:
        urn = entry.get("entityUrn", "")
        if urn.startswith(prefix):
            logos[urn[len(prefix) :].lower()] = (entry.get("aspect") or {}).get(
                "logoUrl"
            )
    return logos


def _platforms_to_check() -> Set[str]:
    return _connector_platform_ids() - _NON_DATA_PLATFORM_SOURCES


def test_connector_platforms_registered_in_seed() -> None:
    """Every connector platform (minus exemptions) must have a ``DataPlatformInfo``
    entry in the bootstrap seed (matched case-insensitively)."""
    seed = _seed_platform_logos()
    missing = sorted(pid for pid in _platforms_to_check() if pid.lower() not in seed)
    assert not missing, (
        f"{len(missing)} connector platform(s) are not registered in "
        f"{_DATA_PLATFORMS_SEED.relative_to(_REPO_ROOT)}: {missing}. "
        "Add a dataPlatformInfo entry (name, displayName, local logoUrl) for each, "
        "vendor the logo into datahub-web-react/src/images/, and if a source does not "
        "emit its own browsable platform add it to _NON_DATA_PLATFORM_SOURCES with a reason."
    )


def test_seed_logo_urls_are_local() -> None:
    """Seed logos must be self-hosted (no external URLs)."""
    seed = _seed_platform_logos()
    external = sorted(
        f"{pid} -> {logo}"
        for pid, logo in seed.items()
        if logo and logo.strip().lower().startswith("http")
    )
    assert not external, (
        "Data platform logos must be self-hosted under assets/platforms/, "
        f"not external URLs: {external}"
    )


def test_registered_connector_platform_logos_exist() -> None:
    """A logoUrl in the seed must point at a vendored asset that actually exists,
    otherwise the platform renders a broken image."""
    if not any(d.exists() for d in _LOGO_ASSET_DIRS):
        pytest.skip("datahub-web-react assets not present in this checkout")
    seed = _seed_platform_logos()
    missing_files: List[str] = []
    for pid in _platforms_to_check():
        logo = seed.get(pid.lower())
        if not logo or logo.strip().lower().startswith("http"):
            continue
        filename = logo.rsplit("/", 1)[-1]
        if not any((d / filename).exists() for d in _LOGO_ASSET_DIRS):
            missing_files.append(f"{pid} -> {logo}")
    assert not missing_files, (
        "Seed logoUrl(s) reference assets that are not vendored under "
        "datahub-web-react/src/images or public/assets/platforms: "
        f"{sorted(missing_files)}"
    )


def test_no_external_logo_urls_in_connector_sources() -> None:
    """Connector sources must not hard-code external logo URLs; register the
    platform (with a vendored logo) in the seed instead."""
    _require(_INGESTION_SOURCE_DIR)
    offenders: List[str] = []
    for py_file in _INGESTION_SOURCE_DIR.rglob("*.py"):
        for lineno, line in enumerate(py_file.read_text().splitlines(), start=1):
            if _EXTERNAL_LOGO_RE.search(line):
                rel = py_file.relative_to(_METADATA_INGESTION_DIR)
                offenders.append(f"{rel}:{lineno}: {line.strip()}")
    assert not offenders, (
        "External logo URLs are not allowed in connector sources; vendor the logo "
        "into datahub-web-react/src/images/ and reference assets/platforms/<file>:\n"
        + "\n".join(offenders)
    )
