"""Guard that non-Python files under src/ are either shipped or explicitly exempt.

Every other test imports `datahub` from the source tree, where data files are
present whether or not `package_data` mentions them. A missing `package_data`
entry therefore cannot fail any normal test -- it only surfaces as a
FileNotFoundError for users of the published wheel. This test checks the
declaration instead of the checkout, so the gap is closed at review time.

The check is fail-closed: a new non-Python file under src/ must either match a
`package_data` glob or be added to `NOT_SHIPPED` with a reason. That forces the
ship/don't-ship decision to be made once, explicitly.
"""

import fnmatch
import pathlib
from typing import Dict, List, Set

METADATA_INGESTION_DIR = pathlib.Path(__file__).parents[2]
SRC_DIR = METADATA_INGESTION_DIR / "src"

# Files under src/ that deliberately do not ship in the wheel, with the reason.
# Keys are POSIX paths relative to src/.
NOT_SHIPPED: Dict[str, str] = {
    # Developer-facing docs, read on GitHub rather than at runtime.
    "datahub/ingestion/recording/README.md": "developer docs",
    "datahub/ingestion/source/odcs/odcs_schema/README.md": "developer docs",
    "datahub/ingestion/source/rdf/README.md": "developer docs",
    "datahub/ingestion/source/rdf/docs/ENTITY_PLUGIN_CONTRACT.md": "developer docs",
    "datahub/ingestion/source/rdf/docs/README.md": "developer docs",
    "datahub/ingestion/source/rdf/docs/background.md": "developer docs",
    "datahub/ingestion/source/rdf/docs/rdf-specification.md": "developer docs",
    "datahub/ingestion/source/rdf/docs/user-stories-and-acceptance-criteria.md": "developer docs",
    "datahub/ingestion/source/rdf/entities/domain/SPEC.md": "developer docs",
    "datahub/ingestion/source/rdf/entities/glossary_term/SPEC.md": "developer docs",
    "datahub/ingestion/source/rdf/entities/relationship/SPEC.md": "developer docs",
    "datahub/ingestion/source/rdf/ingestion/README.md": "developer docs",
    "datahub/ingestion/source/pinecone/skill_docs/PINECONE_CONNECTOR_IMPLEMENTATION.md": "developer docs",
    "datahub/ingestion/source/pinecone/skill_docs/PINECONE_CONNECTOR_PLANNING.md": "developer docs",
    "datahub/ingestion/source/pinecone/skill_docs/PINECONE_datahub-connector-pr-review-2026-03-08.md": "developer docs",
    "datahub/ingestion/source/snowplow/README.md": "developer docs",
    # Consumed by scripts/refresh_odcs_schemas.sh against the checkout.
    "datahub/ingestion/source/odcs/odcs_schema/CHECKSUMS.sha256": "build-time only",
    # Consumed by scripts/docgen.py and scripts/selective_ci_checks.py against
    # the checkout, not by the installed package.
    "datahub/ingestion/autogenerated/connector_registry/datahub.json": "build-time only",
    "datahub/ingestion/autogenerated/connector_registry/manifest.json": "build-time only",
    "datahub/ingestion/source/powerbi/connector.yaml": "build-time only",
    # Sources for bundle.js.gz, which is what actually ships.
    "datahub/ingestion/source/powerbi/m_query/mquery_bridge/.gitignore": "build input",
    "datahub/ingestion/source/powerbi/m_query/mquery_bridge/build.sh": "build input",
    "datahub/ingestion/source/powerbi/m_query/mquery_bridge/index.ts": "build input",
    "datahub/ingestion/source/powerbi/m_query/mquery_bridge/package-lock.json": "build input",
    "datahub/ingestion/source/powerbi/m_query/mquery_bridge/package.json": "build input",
    "datahub/ingestion/source/powerbi/m_query/mquery_bridge/tsconfig.json": "build input",
    # Referenced by a user-facing log message ("datahub properties upsert -f
    # snowplow_field_structured_properties.yaml"). Shipping it may well be the
    # right call, but that is a separate decision from fixing the crash.
    "datahub/ingestion/source/snowplow/snowplow_field_structured_properties.yaml": "user-facing template, ship decision pending",
}


def _load_package_data() -> Dict[str, List[str]]:
    """Read package_data out of setup.py, which is the source of truth for it."""
    setup_py = METADATA_INGESTION_DIR / "setup.py"
    namespace: Dict = {"__name__": "__not_main__", "__file__": str(setup_py)}
    code = setup_py.read_text().replace("setuptools.setup(", "_setup_args = dict(")
    exec(code, namespace)
    return namespace["_setup_args"]["package_data"]


def _shipped_patterns() -> Set[str]:
    """Expand package_data into POSIX glob patterns relative to src/."""
    # setuptools adds py.typed to every package it builds, declared or not.
    patterns = {"*/py.typed"}
    for package, globs in _load_package_data().items():
        prefix = package.replace(".", "/")
        for glob in globs:
            patterns.add(f"{prefix}/{glob}")
    return patterns


def _matches(rel: str, pattern: str) -> bool:
    """Match a src-relative path against a package_data pattern.

    setuptools evaluates package_data per package, so a `*` never spans a
    directory separator and never reaches into a subpackage: the
    `datahub.ingestion.autogenerated` entry does not cover
    `autogenerated/connector_registry/`. fnmatch on the whole path would let it,
    so compare component by component.
    """
    rel_parts = rel.split("/")
    pattern_parts = pattern.split("/")
    if len(rel_parts) != len(pattern_parts):
        return False
    return all(
        fnmatch.fnmatch(part, pattern_part)
        for part, pattern_part in zip(rel_parts, pattern_parts, strict=True)
    )


def _is_build_artifact(path: pathlib.Path) -> bool:
    """Skip what an editable install leaves behind: src/*.egg-info, caches."""
    return any(
        part == "__pycache__" or part.endswith(".egg-info") for part in path.parts
    )


def _data_files() -> List[str]:
    return sorted(
        path.relative_to(SRC_DIR).as_posix()
        for path in SRC_DIR.rglob("*")
        if path.is_file()
        and path.suffix not in (".py", ".pyc")
        and not _is_build_artifact(path)
    )


def test_data_files_are_shipped_or_exempt() -> None:
    patterns = _shipped_patterns()
    undeclared = [
        rel
        for rel in _data_files()
        if rel not in NOT_SHIPPED
        and not any(_matches(rel, pattern) for pattern in patterns)
    ]
    assert not undeclared, (
        "These files live under src/ but no package_data glob in setup.py matches "
        "them, so they will be absent from the built wheel. Either add a "
        "package_data entry (and re-run scripts/generate_pyproject_deps.py) or "
        f"list them in NOT_SHIPPED with a reason: {undeclared}"
    )


def test_not_shipped_entries_still_exist() -> None:
    """Keep NOT_SHIPPED from rotting into a list of deleted paths."""
    stale = [rel for rel in NOT_SHIPPED if not (SRC_DIR / rel).exists()]
    assert not stale, f"NOT_SHIPPED lists paths that no longer exist: {stale}"


def test_not_shipped_entries_are_not_also_declared() -> None:
    """A file cannot be both exempt and shipped; that means one is wrong."""
    patterns = _shipped_patterns()
    contradictory = [
        rel
        for rel in NOT_SHIPPED
        if any(_matches(rel, pattern) for pattern in patterns)
    ]
    assert not contradictory, (
        f"Listed in NOT_SHIPPED but matched by a package_data glob: {contradictory}"
    )
