import os


def string_to_bool(string: str) -> bool:
    return string.lower() == "true"


def env_to_int(varname: str, default_val: int) -> int:
    val = os.environ.get(varname)
    if val is None:
        return default_val
    if val.isdigit():
        return int(val)
    return default_val


def datahub_url() -> str:
    url = os.environ.get("DATAHUB_GMS_URL")
    if url is not None:
        return url
    return (
        f"{os.environ.get('DATAHUB_GMS_PROTOCOL', 'http')}://"
        f"{os.environ.get('DATAHUB_GMS_HOST', 'localhost')}:{os.environ.get('DATAHUB_GMS_PORT', 8080)}"
    )


DATAHUB_HOSTNAME = os.environ.get("HOSTNAME", "Undefined")
DATAHUB_APPNAME = os.environ.get("DATAHUB_NAMESPACE", DATAHUB_HOSTNAME)
DATAHUB_EXECUTOR_NAMESPACE = os.environ.get("DATAHUB_EXECUTOR_NAMESPACE", None)

DATAHUB_GMS_TOKEN = os.environ.get("DATAHUB_GMS_TOKEN", None)
DATAHUB_GMS_URL = datahub_url()

DATAHUB_EXECUTOR_PROMETHEUS_PORT = env_to_int("DATAHUB_EXECUTOR_PROMETHEUS_PORT", 9087)

DATAHUB_EXECUTOR_MODE = os.getenv("DATAHUB_EXECUTOR_MODE", "coordinator")
DATAHUB_EXECUTOR_WORKER_ID = os.environ.get("DATAHUB_EXECUTOR_WORKER_ID", "default")

DATAHUB_EXECUTOR_MONITORS_ENABLED = string_to_bool(
    os.getenv("DATAHUB_EXECUTOR_MONITORS_ENABLED", "True")
)
DATAHUB_EXECUTOR_INGESTION_ENABLED = string_to_bool(
    os.getenv("DATAHUB_EXECUTOR_INGESTION_ENABLED", "True")
)
DATAHUB_EXECUTOR_EMBEDDED_WORKER_ENABLED = string_to_bool(
    os.getenv("DATAHUB_EXECUTOR_EMBEDDED_WORKER_ENABLED", "True")
)
DATAHUB_EXECUTOR_INTERNAL_WORKER = string_to_bool(
    os.getenv("DATAHUB_EXECUTOR_INTERNAL_WORKER", "False")
)

DATAHUB_EXECUTOR_GRACEFUL_SHUTDOWN_PERIOD = env_to_int(
    "DATAHUB_EXECUTOR_GRACEFUL_SHUTDOWN_PERIOD", 15
)

DATAHUB_EXECUTOR_SQS_VISIBILITY_TIMEOUT = env_to_int(
    "DATAHUB_EXECUTOR_SQS_VISIBILITY_TIMEOUT", 43200
)

DATAHUB_EXECUTOR_INGESTION_PIPELINE_CONFIG_PATH = os.environ.get(
    "DATAHUB_EXECUTOR_INGESTION_CONFIG_PATH",
    "/etc/datahub-executor/ingestion-pipeline-config.yaml",
)
DATAHUB_EXECUTOR_INGESTION_PIPELINE_MAX_WORKERS = env_to_int(
    "DATAHUB_EXECUTOR_INGESTION_MAX_WORKERS", 4
)
DATAHUB_EXECUTOR_INGESTION_PIPELINE_SIGNAL_POLL_INTERVAL = env_to_int(
    "DATAHUB_EXECUTOR_INGESTION_SIGNAL_POLL_INTERVAL", 2
)

DATAHUB_EXECUTOR_MONITORS_MAX_WORKERS = env_to_int(
    "DATAHUB_EXECUTOR_MONITORS_MAX_WORKERS", 10
)

DATAHUB_EXECUTOR_WORKER_IMPLEMENTATION = os.getenv(
    "DATAHUB_EXECUTOR_WORKER_IMPLEMENTATION", "default"
)

DATAHUB_EXECUTOR_WORKER_MONITOR_INTERVAL = env_to_int(
    "DATAHUB_EXECUTOR_WORKER_MONITOR_INTERVAL", 2
)
DATAHUB_EXECUTOR_READINESS_HEARTBEAT_FILE = "/tmp/worker_readiness_heartbeat"
DATAHUB_EXECUTOR_LIVENESS_HEARTBEAT_FILE = "/tmp/worker_liveness_heartbeat"

DATAHUB_EXECUTOR_MONITORS_FETCHER_REFRESH_INTERVAL = env_to_int(
    "DATAHUB_EXECUTOR_MONITORS_FETCHER_REFRESH_INTERVAL", 1
)
DATAHUB_EXECUTOR_INGESTION_FETCHER_REFRESH_INTERVAL = env_to_int(
    "DATAHUB_EXECUTOR_INGESTION_FETCHER_REFRESH_INTERVAL", 1
)

DATAHUB_EXECUTOR_SNOWFLAKE_TIMEOUT = env_to_int(
    "DATAHUB_EXECUTOR_SNOWFLAKE_TIMEOUT", 600
)

DATAHUB_EXECUTOR_SWEEPER_INTERVAL = env_to_int("DATAHUB_EXECUTOR_SWEEPER_INTERVAL", 60)
# Time it takes for sweeper to consider a task stale and abort it
DATAHUB_EXECUTOR_SWEEPER_ABORT_THRESHOLD = env_to_int(
    "DATAHUB_EXECUTOR_SWEEPER_ABORT_THRESHOLD", 3600
)
# If a task has an existing signal request pending for over CANCEL_THRESHOLD,
# sweeper will forcibily write Cancelled status for the task. This may be necessary
# to allow new requests to move forward, otherwise they may be cancelled as DUPLICATE
DATAHUB_EXECUTOR_SWEEPER_CANCEL_THRESHOLD = env_to_int(
    "DATAHUB_EXECUTOR_SWEEPER_CANCEL_THRESHOLD", 60
)
DATAHUB_EXECUTOR_SWEEPER_PENDING_THRESHOLD = env_to_int(
    "DATAHUB_EXECUTOR_SWEEPER_PENDING_THRESHOLD", 3600 * 24 * 2
)
DATAHUB_EXECUTOR_SWEEPER_DISABLED = string_to_bool(
    os.getenv("DATAHUB_EXECUTOR_SWEEPER_DISABLED", "False")
)
DATAHUB_EXECUTOR_SWEEPER_RESTARTS_DISABLED = string_to_bool(
    os.getenv("DATAHUB_EXECUTOR_SWEEPER_RESTARTS_DISABLED", "False")
)
DATAHUB_EXECUTOR_SWEEPER_RESTART_MAX_ATTEMPTS = env_to_int(
    "DATAHUB_EXECUTOR_SWEEPER_RESTART_MAX_ATTEMPTS", 3
)

DATAHUB_EXECUTOR_SQS_MESSAGE_MAX_LENGTH = env_to_int(
    "DATAHUB_EXECUTOR_SQS_MESSAGE_MAX_LENGTH", 192000
)

DATAHUB_EXECUTOR_SCHEDULER_ASSERTIONS_MAX_THREADS = env_to_int(
    "DATAHUB_EXECUTOR_SCHEDULER_ASSERTIONS_MAX_THREADS", 4
)
DATAHUB_EXECUTOR_SCHEDULER_INGESTIONS_MAX_THREADS = env_to_int(
    "DATAHUB_EXECUTOR_SCHEDULER_INGESTIONS_MAX_THREADS", 4
)
DATAHUB_EXECUTOR_SCHEDULER_MISFIRE_PERIOD = env_to_int(
    "DATAHUB_EXECUTOR_SCHEDULER_MISFIRE_PERIOD", (6 * 60 * 60)
)

DATAHUB_EXECUTOR_DISCOVERY_INTERVAL = env_to_int(
    "DATAHUB_EXECUTOR_DISCOVERY_INTERVAL", 30
)
DATAHUB_EXECUTOR_DISCOVERY_EXPIRE_THRESHOLD = env_to_int(
    "DATAHUB_EXECUTOR_DISCOVERY_EXPIRE_THRESHOLD", 3600
)
DATAHUB_EXECUTOR_DISCOVERY_PURGE_THRESHOLD = env_to_int(
    "DATAHUB_EXECUTOR_DISCOVERY_PURGE_THRESHOLD", 3600 * 24 * 30
)
DATAHUB_EXECUTOR_DISCOVERY_PURGE_AFTER = env_to_int(
    "DATAHUB_EXECUTOR_DISCOVERY_PURGE_AFTER", 3600 * 24
)
