const fs = require("fs");

function list_ids_in_directory(directory, hardcoded_labels) {
  if (hardcoded_labels === undefined) {
    hardcoded_labels = {};
  }

  const files = fs.readdirSync(`../${directory}`).sort();
  let ids = [];
  for (const name of files) {
    if (fs.lstatSync(`../${directory}/${name}`).isDirectory()) {
      // Recurse into the directory.
      const inner_ids = list_ids_in_directory(`${directory}/${name}`);
      ids = ids.concat(inner_ids);
    } else {
      if (name.endsWith(".md")) {
        const slug = name.replace(/\.md$/, "");
        const id = `${directory}/${slug}`;

        if (id in hardcoded_labels) {
          label = hardcoded_labels[id];
          ids.push({ type: "doc", id, label });
        } else {
          ids.push({ type: "doc", id });
        }
      }
    }
  }
  return ids;
}

// note: to handle errors where you don't want a markdown file in the sidebar, add it as a comment.
// this will fix errors like `Error: File not accounted for in sidebar: ...`
module.exports = {
  // users
  // architects
  // modelers
  // developers
  // operators

  overviewSidebar: {
    "What is DataHub?": [
      "docs/wip/what-is-datahub",
      "docs/features",
      {
       Architecture: [
        "docs/architecture/architecture",
        "docs/architecture/metadata-ingestion",
        "docs/architecture/metadata-serving",
        "docs/components",
        "docs/what/mxe",
        ],
      },
      "docs/demo",
      "docs/saas",
    ],
    "Get Started": [
      "docs/quickstart",
      "docs/wip/managed-datahub-setup",
      "docs/wip/deplyoing-datahub",
      "docs/wip/create-policies",
      {
        Authorization: [
          "docs/authorization/README",
          "docs/authorization/policies",
          "docs/authorization/groups",
        ],
      },
      { 
        "Add Users": [
          "docs/authentication/guides/add-users",
          "docs/wip/invite-with-email-link",
          "docs/wip/configure-sso",
          {
            Authentication: [
              "docs/authentication/README",
              "docs/authentication/concepts",
            {
              "Frontend Authentication": [
                "docs/authentication/guides/jaas",
                {
                "OIDC Authentication": [
                  "docs/authentication/guides/sso/configure-oidc-react",
                  "docs/authentication/guides/sso/configure-oidc-react-google",
                  "docs/authentication/guides/sso/configure-oidc-react-okta",
                  "docs/authentication/guides/sso/configure-oidc-react-azure",
                  ],
                },
              ],
            },
              "docs/authentication/introducing-metadata-service-authentication",
              "docs/authentication/personal-access-tokens",      
            ],
          },
        ],
      },
      "docs/managed-datahub/saas-slack-setup",
      "docs/wip/core-concepts",
      "docs/debugging",
    ],
    "Ingest Metadata": [
      "metadata-ingestion/README",
      {
        "Prepare for Ingestion": [
          "docs/wip/ingestion-overview",
          "docs/wip/importance-of-shift-left",
          "docs/wip/define-domains",
          "docs/wip/create-business-glossary",
          "docs/wip/create-tags",
        ],
      },
      {
        "Managed Ingestion": [
          "docs/wip/managed-ingestion-overview",
          "metadata-ingestion/schedule_docs/datahub",
          "docs/wip/managed-ingestion-supported-connectors",
        ],
      },
      {
        "Pull-Based Ingestion": [
          "docs/wip/pull-based-ingestion",
          {
            "Pull-Based Sources": [
              {
                type: "autogenerated",
                dirName: "docs/generated/ingestion/sources", // '.' means the current docs folder
              },
            ],
          },
          {
            "Scheduling Ingestion": [
              "metadata-ingestion/schedule_docs/intro",
              "metadata-ingestion/schedule_docs/cron",
              "metadata-ingestion/schedule_docs/airflow",
            ],
          },
        ],
      },
        "docs/wip/push-based-ingestion",
        "docs/wip/remote-ingestion-executor-on-AWS",
    ],

    "Enrich Metadata": [
      "docs/wip/transformers",
      "docs/wip/csv-enrichment",
      "docs/wip/ui-based-ingestion",
      "docs/wip/lineage",
    ],

    "Act on Metadata": [
      "docs/wip/metadata-tests",
      "docs/wip/metadata-analytics",
      "docs/wip/datahub-actions",
      "docs/wip/impact-analysis",
      "docs/wip/events-bridge",
      "docs/wip/datahub-incidents",
      "docs/wip/approval-workflows",
    ],

    "DataHub API & SDK": [
      "docs/wip/graphql",
      "docs/wip/rest.li",
      "docs/wip/openapi",
    ],
    "Tutorials": [
      "docs/wip/impact-analysis",
      "docs/wip/schema-history-guide",
      "docs/wip/domains-guide",
      "docs/wip/ui-ingestion-guide",
      "docs/wip/tags-guide",
      "docs/wip/search-guide",
      "docs/wip/ui-tabs-guide",
      "docs/wip/business-glossary-guide",
      "docs/wip/approval-flows-guide",
      "docs/wip/personal-access-tokens-guide",
    ],
    "Advanced Guides": [
      "docs/wip/datahub-deployment-guides",
      "docs/wip/updating-datahub",
      "docs/wip/extending-the-metadata-model",
      "docs/wip/taking-backup-of-datahub",
      "docs/wip/restoring-search-and-graph-indices",
      "docs/wip/developing-on-metadata-ingestion",
      "docs/wip/no-code-metadata",
      "docs/wip/configuring-database-retention",
      "docs/wip/aspect-versioning",
      "docs/wip/search-ranking",
      "docs/wip/advanced-ingestion-guides",
      {
        "Advanced Ingestion Guides": [
          "docs/wip/using-a-custom-ingestion-source",
          "docs/wip/working-with-platform-instances",
          "docs/wip/stateful-ingestion",
          "docs/wip/sql-profiling",
        ],
      }
    ],
    "Join the Community": [
      "docs/wip/slack-community",
      "docs/wip/town-halls",
      "docs/wip/code-of-conduct",
      "docs/wip/contribution-guidelines",
      "docs/wip/rfcs",
    ],

    "TBD": [
      "README",
      "docs/roadmap",
      "docs/CONTRIBUTING",
      "releases",
    ],    
///////////////////////////////////////// 


    Ingestion: [
      // add a custom label since the default is 'Metadata Ingestion'
      // note that we also have to add the path to this file in sidebarsjs_hardcoded_titles in generateDocsDir.ts


      "metadata-ingestion/transformers",
      {
        Sinks: list_ids_in_directory("metadata-ingestion/sink_docs"),
      },

      {
        "Push-Based Integrations": [
          {
            Airflow: ["docs/lineage/airflow", "docker/airflow/local_airflow"],
          },
          "metadata-integration/java/spark-lineage/README",
          "metadata-ingestion/integration_docs/great-expectations",
          "metadata-integration/java/datahub-protobuf/README",
          "metadata-ingestion/as-a-library",
          "metadata-integration/java/as-a-library",
          //"metadata-ingestion-modules/airflow-plugin/README"
        ],
      },
      {
        Lineage: ["docs/lineage/intro", "docs/lineage/sample_code"],
      },
      {
        Guides: [
          "metadata-ingestion/adding-source",
          //"metadata-ingestion/source-docs-template",
          "docs/how/add-custom-ingestion-source",
          "docs/how/add-custom-data-platform",
          "docs/platform-instances",
          "docs/how/add-user-data",
          "metadata-ingestion/docs/dev_guides/stateful",
          "metadata-ingestion/docs/dev_guides/reporting_telemetry",
          "metadata-ingestion/docs/dev_guides/sql_profiles",
        ],
      },
    ],
    Modeling: [
      "docs/modeling/metadata-model",
      "docs/modeling/extending-the-metadata-model",
      {
        Entities: [
          {
            type: "autogenerated",
            dirName: "docs/generated/metamodel/entities", // '.' means the current docs folder
          },
        ],
      },
      // TODO: change the titles of these, removing the "What is..." portion from the sidebar"
      // "docs/what/entity",
      // "docs/what/aspect",
      // "docs/what/urn",
      // "docs/what/relationship",
      // "docs/what/search-document",
      // "docs/what/snapshot",
      // "docs/what/delta",
      // "docs/what/mxe",
    ],
    CLI: [
      {
        label: "Overview",
        type: "doc",
        id: "docs/cli",
      },
    ],
    "GraphQL API": [
      {
        label: "Overview",
        type: "doc",
        id: "docs/api/graphql/overview",
      },
      {
        Reference: [
          {
            type: "doc",
            label: "Queries",
            id: "graphql/queries",
          },
          {
            type: "doc",
            label: "Mutations",
            id: "graphql/mutations",
          },
          {
            type: "doc",
            label: "Objects",
            id: "graphql/objects",
          },
          {
            type: "doc",
            label: "Inputs",
            id: "graphql/inputObjects",
          },
          {
            type: "doc",
            label: "Interfaces",
            id: "graphql/interfaces",
          },
          {
            type: "doc",
            label: "Unions",
            id: "graphql/unions",
          },
          {
            type: "doc",
            label: "Enums",
            id: "graphql/enums",
          },
          {
            type: "doc",
            label: "Scalars",
            id: "graphql/scalars",
          },
        ],
      },
      {
        Guides: [
          {
            type: "doc",
            label: "Getting Started",
            id: "docs/api/graphql/getting-started",
          },
          {
            type: "doc",
            label: "Querying Metadata Entities",
            id: "docs/api/graphql/querying-entities",
          },
          {
            type: "doc",
            label: "Access Token Management",
            id: "docs/api/graphql/token-management",
          },
        ],
      },
    ],
    OpenAPI: [
      {
        label: "Usage Guide",
        type: "doc",
        id: "docs/api/openapi/openapi-usage-guide",
      },
    ],
    Actions: [
      {
        type: "doc",
        id: "docs/actions/README",
        label: "Introduction",
      },
      {
        label: "Quickstart",
        type: "doc",
        id: "docs/actions/quickstart",
      },
      {
        label: "Concepts",
        type: "doc",
        id: "docs/actions/concepts",
      },
      {
        Sources: [
          {
            type: "autogenerated",
            dirName: "docs/actions/sources",
          },
        ],
      },
      {
        Events: [
          {
            type: "autogenerated",
            dirName: "docs/actions/events",
          },
        ],
      },
      {
        Actions: [
          {
            type: "autogenerated",
            dirName: "docs/actions/actions",
          },
        ],
      },
      {
        Guides: [
          {
            type: "autogenerated",
            dirName: "docs/actions/guides",
          },
        ],
      },
    ],
    "Usage Guides": [
      "docs/domains",
      "docs/ui-ingestion",
      "docs/tags",
      "docs/schema-history",
      "docs/how/search",
      "docs/how/ui-tabs-guide",
      "docs/how/business-glossary-guide",
    ],
    "Developer Guides": [
      // TODO: the titles of these should not be in question form in the sidebar
      "docs/developers",
      "docs/docker/development",
      "docs/how/backup-datahub",
      "docs/how/updating-datahub",
      //"metadata-ingestion/examples/transforms/README"
      //"docs/what/graph",
      //"docs/what/search-index",
      //"docs/how/add-new-aspect",
      //"docs/how/build-metadata-service",
      //"docs/how/graph-onboarding",
      //"docs/demo/graph-onboarding",
      "docs/what/mxe",
      "docs/how/restore-indices",
      "docs/dev-guides/timeline",
      "docs/how/extract-container-logs",
      "docs/how/delete-metadata",
      "datahub-web-react/src/app/analytics/README",
      "metadata-ingestion/developing",
      {
        "Module READMEs": [
          "datahub-web-react/README",
          "datahub-frontend/README",
          "datahub-graphql-core/README",
          "metadata-service/README",
          // "metadata-jobs/README",
          "metadata-jobs/mae-consumer-job/README",
          "metadata-jobs/mce-consumer-job/README",
        ],
      },
      {
        Advanced: [
          "docs/advanced/no-code-modeling",
          "docs/advanced/db-retention",
          "docs/advanced/aspect-versioning",
          "docs/advanced/es-7-upgrade",
          "docs/advanced/high-cardinality",
          "docs/advanced/no-code-upgrade",
          "docs/how/migrating-graph-service-implementation",
          "docs/advanced/mcp-mcl",
          "docs/advanced/field-path-spec-v2",
          "docs/advanced/monitoring",
          // WIP "docs/advanced/backfilling",
          // WIP "docs/advanced/derived-aspects",
          // WIP "docs/advanced/entity-hierarchy",
          // WIP "docs/advanced/partial-update",
          // WIP "docs/advanced/pdl-best-practices",
          // WIP "docs/introducing-metadata-service-authentication"
          // WIP "metadata-models-custom/README"
        ],
      },
    ],
    "Deployment Guides": [
      "docs/how/kafka-config",
      "docker/README",
      "docs/deploy/kubernetes",
      "docker/datahub-upgrade/README",
      "docs/deploy/aws",
      "docs/deploy/gcp",
      "docs/deploy/confluent-cloud",
      "docs/deploy/telemetry",
      // Purposely not including the following:
      // - "docker/datahub-frontend/README",
      // - "docker/datahub-gms/README",
      // - "docker/datahub-mae-consumer/README",
      // - "docker/datahub-mce-consumer/README",
      // - "docker/datahub-ingestion/README",
      // - "docker/elasticsearch-setup/README",
      // - "docker/ingestion/README",
      // - "docker/kafka-setup/README",
      // - "docker/mariadb/README",
      // - "docker/mysql/README",
      // - "docker/neo4j/README",
      // - "docker/postgres/README",
      // - "perf-test/README",
    ],
    Community: [
      "docs/slack",
      "docs/links",
      "docs/townhalls",
      "docs/townhall-history",
      "docs/CODE_OF_CONDUCT",
      "docs/rfc",
      {
        RFCs: list_ids_in_directory("docs/rfc/active"),
      },
    ],
  },
};
