DEFAULT_OPERATION_TYPES_FILTER = '"INSERT" OR "UPDATE" OR "CREATE_TABLE" OR "CREATE_TABLE_AS_SELECT" OR "CREATE_EXTERNAL_TABLE" OR "CREATE_SNAPSHOT_TABLE"'  # Note that Alter is not included :)

SUPPORTED_LAST_MODIFIED_COLUMN_TYPES = ["DATE", "DATETIME", "TIMESTAMP"]

SUPPORTED_HIGH_WATERMARK_COLUMN_TYPES = [
    "INT64",
    "INT",
    "SMALLINT",
    "INTEGER",
    "BIGINT",
    "TINYINT",
    "BYTEINT",
    "NUMERIC",
    "DECIMAL",
    "BIGNUMERIC",
    "BIGDECIMAL",
    "FLOAT64",
    "DATE",
    "DATETIME",
    "TIMESTAMP",
]
