import colors from '@conf/theme/colorThemes/color';
import ColorTheme from '@conf/theme/colorThemes/types';

const darkTheme: ColorTheme = {
    bg: colors.gray1100,
    bgSurface: colors.gray1200,
    bgSurfaceNewNav: colors.gray1200,
    bgSurfaceDarker: colors.gray1000,
    bgSurfaceBrand: colors.violet1200,
    bgSurfaceBrandHover: colors.violet1100,
    buttonSurfaceBrandHover: colors.violet1000,
    bgDisabled: colors.gray700,
    bgSurfaceError: colors.red500,
    bgSurfaceErrorHover: colors.red400,
    bgSurfaceInfo: colors.blue1200,
    bgSurfaceInformationHover: colors.blue800,
    bgSurfaceSuccess: colors.mudgreen900,
    bgSurfaceSuccessHover: colors.mudgreen800,
    bgSurfaceWarning: colors.trueyellow300,
    bgSurfaceWarningHover: colors.yellow800,
    bgHover: colors.gray1000,
    text: colors.gray200,
    textSecondary: colors.gray300,
    textTertiary: colors.gray400,
    textBrand: colors.violet500,
    textBrandOnBgFill: colors.gray0,
    textOnFillBrand: colors.gray0,
    textOnFillSuccess: colors.gray0,
    textOnFillError: colors.gray0,
    textOnFillWarning: colors.gray200,
    textOnFillInfo: colors.gray0,
    textOnFillDefault: colors.gray0,
    textDisabled: colors.gray600,
    textError: colors.red200,
    textInformation: colors.blue400,
    textSuccess: colors.green150,
    textWarning: colors.yellow600,
    textOnSurfaceError: colors.red50,
    textOnSurfaceInformation: colors.blue300,
    textOnSurfaceSuccess: colors.green100,
    textOnSurfaceWarning: colors.yellow400,
    hyperlinks: colors.violet400,
    icon: colors.gray600,
    iconBrand: colors.violet400,
    iconError: colors.red100,
    iconInformation: colors.blue400,
    iconSuccess: colors.green150,
    iconWarning: colors.yellow500,
    buttonFillBrand: colors.violet800,
    buttonFillFocus: colors.violet500,
    buttonSurfaceBrandFocus: colors.violet500,
    buttonSurfaceSecondaryHover: colors.violet500,
    radioButtonBorder: colors.gray400,
    radioButtonDotFill: colors.gray400,
    radioButtonDotDisabled: colors.gray500,
    avatarBorderBrand: colors.violet500,
    avatarBorderInformation: colors.blue600,
    border: colors.gray900,
    borderBrand: colors.violet500,
    borderBrandFocused: colors.violet400,
    borderBrandInverse: colors.violet800,
    borderDisabled: colors.gray600,
    borderInformation: colors.blue700,
    borderInformationInverse: colors.blue400,
    borderError: colors.red300,
    borderSuccess: colors.green300,
    borderWarning: colors.yellow800,
    // Interactive states: Hover
    textHover: colors.violet400,
    iconHover: colors.violet400,
    borderHover: colors.violet500,
    // Interactive states: Active / Pressed
    bgActive: colors.violet1000,
    textActive: colors.violet300,
    borderActive: colors.violet500,
    // Interactive states: Selected
    bgSelected: colors.violet1100,
    bgSelectedSubtle: 'rgba(108, 71, 255, 0.08)',
    textSelected: colors.violet300,
    iconSelected: colors.violet400,
    borderSelected: colors.violet500,
    // Interactive states: Focus
    borderFocused: colors.gray500,
    // Interactive states: Disabled
    iconDisabled: colors.gray700,
    bgSurfaceDisabled: colors.gray900,
    // Shadows
    shadowXs: '0 1px 2px 0 rgba(13, 14, 27, 0.28)',
    shadowSm: '0 2px 4px 0 rgba(13, 14, 27, 0.36)',
    shadowMd: '0 4px 12px -2px rgba(13, 14, 27, 0.40)',
    shadowLg: '0 6px 16px -4px rgba(13, 14, 27, 0.48)',
    shadowXl: '0 8px 24px -4px rgba(13, 14, 27, 0.56)',
    shadowFocus: '0px 0px 0px 1px rgba(139, 135, 157, 0.20)',
    shadowFocusBrand: '0px 0px 0px 1px rgba(108, 71, 255, 0.20)',
    shadowInset: 'inset 0px 1px 3px rgba(0, 0, 0, 0.40)',
    shadowNavbar: '0px 2px 10px rgba(0, 0, 0, 0.40)',
    // Overlays
    overlayLight: 'rgba(255, 255, 255, 0.05)',
    overlayMedium: 'rgba(0, 0, 0, 0.30)',
    overlayHeavy: 'rgba(0, 0, 0, 0.60)',
    overlayOnBrand: 'rgba(255, 255, 255, 0.15)',
    // Inputs / Forms
    bgInput: colors.gray1100,
    bgInputDisabled: colors.gray900,
    borderInput: colors.gray900,
    borderInputFocus: colors.violet400,
    textPlaceholder: colors.gray600,
    // Scrollbar
    scrollbarTrack: 'transparent',
    scrollbarThumb: colors.gray700,
    scrollbarThumbHover: colors.gray600,
    // Code blocks
    bgCode: colors.gray1000,
    bgCodeBlock: colors.gray1000,
    // Highlight
    bgHighlight: '#4a3d00',
    // Tooltip
    bgTooltip: colors.gray300,
    // Brand gradients
    brandGradient: 'radial-gradient(115.48% 144.44% at 50% -44.44%, #917FFF 38.97%, #6C47FF 100%)',
    brandGradientSelected: 'linear-gradient(180deg, #917FFF 20%, #6C47FF 80%)',
    // Skeleton / Loading
    bgSkeleton: colors.gray900,
    bgSkeletonShimmer: colors.gray1000,
    chartsWineHigh: colors.wine600,
    chartsWineMedium: colors.wine400,
    chartsWineLow: colors.wine200,
    chartsWineBase: colors.wine200,
    chartsPinkHigh: colors.pink300,
    chartsPinkMedium: colors.pink200,
    chartsPinkLow: colors.pink100,
    chartsPinkBase: colors.pink0,
    chartsSeafoamHigh: colors.seafoam300,
    chartsSeafoamMedium: colors.seafoam200,
    chartsSeafoamLow: colors.seafoam100,
    chartsSeafoamBase: colors.seafoam0,
    chartsTangerineHigh: colors.tangerine300,
    chartsTangerineMedium: colors.tangerine200,
    chartsTangerineLow: colors.tangerine100,
    chartsTangerineBase: colors.tangerine0,
    chartsOliveHigh: colors.darkgreen300,
    chartsOliveMedium: colors.darkgreen200,
    chartsOliveLow: colors.darkgreen100,
    chartsOliveBase: colors.darkgreen0,
    chartsBlueHigh: colors.cyan300,
    chartsBlueMedium: colors.cyan200,
    chartsBlueLow: colors.cyan100,
    chartsBlueBase: colors.cyan00,
    chartsGreenHigh: colors.mudgreen600,
    chartsGreenMedium: colors.mudgreen400,
    chartsGreenLow: colors.mudgreen200,
    chartsGreenBase: colors.mudgreen100,
    chartsBrandContrast: '#2200F9FF',
    chartsBrandHigh: colors.violet600,
    chartsBrandMedium: colors.violet500,
    chartsBrandLow: colors.violet300,
    chartsBrandBase: colors.violet200,
    chartsHeatmapHigh: colors.violet900,
    chartsHeatmapMedium: colors.violet500,
    chartsHeatmapLow: colors.violet200,
    chartsHeatmapBase: colors.gray100,
    chartsBrandHighAlpha: '#2200F999',
    chartsBrandMediumAlpha: '#917FFF99',
    chartsBrandLowAlpha: '#B0A7EA99',
    chartsBrandBaseAlpha: '#CAC3F166',
    chartsInformationHigh: colors.blue700,
    navBgGradientTop: '#533FD10A',
    navBgGradientBottom: '#3E2F9D0A',
    chartsInformationMedium: colors.blue600,
    chartsInformationLow: colors.blue400,
    chartsInformationBase: colors.blue300,
    tagsCoralBg: colors.pink400,
    tagsCoralBorder: colors.pink200,
    tagsCoralText: colors.pink0,
    tagsBrandBg: colors.violet600,
    tagsBrandBorder: colors.violet200,
    tagsBrandText: colors.violet0,
    tagsAccentBg: colors.blue700,
    tagsAccentBorder: colors.blue300,
    tagsAccentText: colors.blue0,
    tagsTangerineBg: colors.tangerine300,
    tagsTangerineBorder: colors.tangerine100,
    tagsTangerineText: colors.tangerine0,
    tagsSeafoamBg: colors.seafoam300,
    tagsSeafoamBorder: colors.seafoam100,
    tagsSeafoamText: colors.seafoam0,
    tagsTrueBlueBg: colors.trueblue300,
    tagsTrueBlueBorder: colors.trueblue100,
    tagsTrueBlueText: colors.trueblue0,
    tagsCobaltBlueBg: colors.cobalt300,
    tagsCobaltBlueBorder: colors.cobalt100,
    tagsCobaltBlueText: colors.cobalt0,
    tagsCyanBg: colors.cyan300,
    tagsCyanBorder: colors.cyan100,
    tagsCyanText: colors.cyan00,
    tagsDeepGreenBg: colors.darkgreen300,
    tagsDeepGreenBorder: colors.darkgreen100,
    tagsDeepGreenText: colors.darkgreen0,
    tagsOliveBg: colors.olive300,
    tagsOliveBorder: colors.olive100,
    tagsOliveText: colors.olive0,
    tagsLavenderBg: colors.lavender300,
    tagsLavenderBorder: colors.lavender100,
    tagsLavenderText: colors.lavender0,
    tagsBrownBg: colors.brown300,
    tagsBrownBorder: colors.brown200,
    tagsBrownText: colors.brown0,
    tagsTrueYellowBg: colors.trueyellow300,
    tagsTrueYellowBorder: colors.trueyellow100,
    tagsTrueYellowIcon: colors.trueyellow200,
    tagsTrueYellowText: colors.trueyellow0,
};

export default darkTheme;
