import colors from '@conf/theme/colorThemes/color';
import ColorTheme from '@conf/theme/colorThemes/types';

const lightTheme: ColorTheme = {
    bg: colors.gray0,
    bgSurface: colors.gray400,
    bgSurfaceNewNav: colors.gray200,
    bgSurfaceDarker: colors.gray100,
    bgSurfaceBrand: colors.violet0,
    bgSurfaceBrandHover: colors.violet200,
    buttonSurfaceBrandHover: colors.violet800,
    bgDisabled: colors.gray400,
    bgSurfaceError: colors.red0,
    bgSurfaceErrorHover: colors.wine100,
    bgSurfaceInfo: colors.blue0,
    bgSurfaceInformationHover: colors.blue300,
    bgSurfaceSuccess: colors.mudgreen0,
    bgSurfaceSuccessHover: colors.green100,
    bgSurfaceWarning: colors.yellow0,
    bgSurfaceWarningHover: colors.yellow200,
    bgHover: colors.gray400,
    text: colors.gray800,
    textSecondary: colors.gray700,
    textTertiary: colors.gray600,
    textBrand: colors.violet600,
    textBrandOnBgFill: colors.gray0,
    textOnFillBrand: colors.gray0,
    textOnFillSuccess: colors.gray0,
    textOnFillError: colors.gray0,
    textOnFillWarning: colors.gray0,
    textOnFillInfo: colors.gray0,
    textOnFillDefault: colors.gray0,
    textDisabled: colors.gray600,
    textError: colors.red300,
    textInformation: colors.blue700,
    textSuccess: colors.green300,
    textWarning: colors.yellow800,
    textOnSurfaceError: colors.red300,
    textOnSurfaceInformation: colors.blue700,
    textOnSurfaceSuccess: colors.green300,
    textOnSurfaceWarning: colors.yellow800,
    hyperlinks: colors.violet600,
    icon: colors.gray600,
    iconBrand: colors.violet500,
    iconError: colors.red100,
    iconInformation: colors.blue600,
    iconSuccess: colors.green200,
    iconWarning: colors.yellow700,
    buttonFillBrand: colors.violet600,
    buttonFillFocus: colors.violet600,
    buttonSurfaceBrandFocus: colors.violet200,
    buttonSurfaceSecondaryHover: colors.violet100,
    radioButtonBorder: colors.gray600,
    radioButtonDotFill: colors.gray0,
    radioButtonDotDisabled: colors.gray500,
    avatarBorderBrand: colors.violet100,
    avatarBorderInformation: colors.blue200,
    border: colors.gray100,
    borderBrand: colors.violet600,
    borderBrandFocused: colors.violet400,
    borderBrandInverse: colors.violet0,
    borderDisabled: colors.gray600,
    borderInformation: colors.blue700,
    borderInformationInverse: colors.blue0,
    borderError: colors.red300,
    borderSuccess: colors.green300,
    borderWarning: colors.yellow800,
    // Interactive states: Hover
    textHover: colors.violet600,
    iconHover: colors.violet500,
    borderHover: colors.violet300,
    // Interactive states: Active / Pressed
    bgActive: colors.violet100,
    textActive: colors.violet700,
    borderActive: colors.violet400,
    // Interactive states: Selected
    bgSelected: colors.violet0,
    bgSelectedSubtle: 'rgba(83, 63, 209, 0.04)',
    textSelected: colors.violet600,
    iconSelected: colors.violet500,
    borderSelected: colors.violet400,
    // Interactive states: Focus
    borderFocused: colors.gray500,
    // Interactive states: Disabled
    iconDisabled: colors.gray500,
    bgSurfaceDisabled: colors.gray400,
    // Shadows
    shadowXs: '0 1px 2px 0 rgba(33, 23, 95, 0.04)',
    shadowSm: '0 2px 4px 0 rgba(33, 23, 95, 0.06)',
    shadowMd: '0 0 24px 0 rgba(0, 0, 0, 0.10)',
    shadowLg: '0 4px 12px 0 rgba(9, 1, 61, 0.12)',
    shadowXl: '0 4px 28px 0 rgba(9, 1, 61, 0.14)',
    shadowFocus: '0px 0px 0px 1px rgba(139, 135, 157, 0.08)',
    shadowFocusBrand: '0px 0px 0px 1px rgba(108, 71, 255, 0.08)',
    shadowInset: 'inset 0px 1px 3px rgba(0, 0, 0, 0.08)',
    shadowNavbar: '0px 2px 10px rgba(0, 0, 0, 0.08)',
    // Overlays
    overlayLight: 'rgba(0, 0, 0, 0.05)',
    overlayMedium: 'rgba(0, 0, 0, 0.15)',
    overlayHeavy: 'rgba(0, 0, 0, 0.45)',
    overlayOnBrand: 'rgba(255, 255, 255, 0.2)',
    // Inputs / Forms
    bgInput: colors.gray0,
    bgInputDisabled: colors.gray400,
    borderInput: colors.gray100,
    borderInputFocus: colors.violet400,
    textPlaceholder: colors.gray500,
    // Scrollbar
    scrollbarTrack: 'transparent',
    scrollbarThumb: colors.gray100,
    scrollbarThumbHover: colors.gray500,
    // Code blocks
    bgCode: colors.gray200,
    bgCodeBlock: colors.gray200,
    // Highlight
    bgHighlight: '#ffe58f',
    // Tooltip
    bgTooltip: colors.gray1000,
    // Brand gradients
    brandGradient: 'radial-gradient(115.48% 144.44% at 50% -44.44%, #705EE4 38.97%, #533FD1 100%)',
    brandGradientSelected: 'linear-gradient(180deg, #7565d6 20%, #5340cc 80%)',
    // Skeleton / Loading
    bgSkeleton: colors.gray100,
    bgSkeletonShimmer: colors.gray200,
    chartsWineHigh: colors.wine600,
    chartsWineMedium: colors.wine400,
    chartsWineLow: colors.wine200,
    chartsWineBase: colors.wine200,
    chartsPinkHigh: colors.pink300,
    chartsPinkMedium: colors.pink200,
    chartsPinkLow: colors.pink100,
    chartsPinkBase: colors.pink0,
    chartsSeafoamHigh: colors.seafoam300,
    chartsSeafoamMedium: colors.seafoam200,
    chartsSeafoamLow: colors.seafoam100,
    chartsSeafoamBase: colors.seafoam0,
    chartsTangerineHigh: colors.tangerine300,
    chartsTangerineMedium: colors.tangerine200,
    chartsTangerineLow: colors.tangerine100,
    chartsTangerineBase: colors.tangerine0,
    chartsOliveHigh: colors.darkgreen300,
    chartsOliveMedium: colors.darkgreen200,
    chartsOliveLow: colors.darkgreen100,
    chartsOliveBase: colors.darkgreen0,
    chartsBlueHigh: colors.cyan300,
    chartsBlueMedium: colors.cyan200,
    chartsBlueLow: colors.cyan100,
    chartsBlueBase: colors.cyan00,
    chartsGreenHigh: colors.mudgreen600,
    chartsGreenMedium: colors.mudgreen400,
    chartsGreenLow: colors.mudgreen200,
    chartsGreenBase: colors.mudgreen100,
    chartsBrandContrast: '#2200F9FF',
    chartsBrandHigh: colors.violet600,
    chartsBrandMedium: colors.violet500,
    chartsBrandLow: colors.violet300,
    chartsBrandBase: colors.violet200,
    chartsHeatmapHigh: colors.violet900,
    chartsHeatmapMedium: colors.violet500,
    chartsHeatmapLow: colors.violet200,
    chartsHeatmapBase: colors.gray100,
    chartsBrandHighAlpha: '#2200F999',
    chartsBrandMediumAlpha: '#917FFF99',
    chartsBrandLowAlpha: '#B0A7EA99',
    chartsBrandBaseAlpha: '#CAC3F166',
    chartsInformationHigh: colors.blue700,
    navBgGradientTop: '#705EE40A',
    navBgGradientBottom: '#533FD100',
    chartsInformationMedium: colors.blue600,
    chartsInformationLow: colors.blue400,
    chartsInformationBase: colors.blue300,
    tagsCoralBg: colors.pink100,
    tagsCoralBorder: colors.pink200,
    tagsCoralText: colors.pink400,
    tagsBrandBg: colors.violet0,
    tagsBrandBorder: colors.violet200,
    tagsBrandText: colors.violet600,
    tagsAccentBg: colors.blue0,
    tagsAccentBorder: colors.blue300,
    tagsAccentText: colors.blue700,
    tagsTangerineBg: colors.tangerine0,
    tagsTangerineBorder: colors.tangerine100,
    tagsTangerineText: colors.tangerine300,
    tagsSeafoamBg: colors.seafoam0,
    tagsSeafoamBorder: colors.seafoam100,
    tagsSeafoamText: colors.seafoam300,
    tagsTrueBlueBg: colors.trueblue0,
    tagsTrueBlueBorder: colors.trueblue100,
    tagsTrueBlueText: colors.trueblue300,
    tagsCobaltBlueBg: colors.cobalt0,
    tagsCobaltBlueBorder: colors.cobalt100,
    tagsCobaltBlueText: colors.cobalt300,
    tagsCyanBg: colors.cyan00,
    tagsCyanBorder: colors.cyan100,
    tagsCyanText: colors.cyan300,
    tagsDeepGreenBg: colors.darkgreen0,
    tagsDeepGreenBorder: colors.darkgreen100,
    tagsDeepGreenText: colors.darkgreen300,
    tagsOliveBg: colors.olive0,
    tagsOliveBorder: colors.olive100,
    tagsOliveText: colors.olive300,
    tagsLavenderBg: colors.lavender0,
    tagsLavenderBorder: colors.lavender100,
    tagsLavenderText: colors.lavender300,
    tagsBrownBg: colors.brown0,
    tagsBrownBorder: colors.brown200,
    tagsBrownText: colors.brown300,
    tagsTrueYellowBg: colors.trueyellow0,
    tagsTrueYellowBorder: colors.trueyellow100,
    tagsTrueYellowIcon: colors.trueyellow200,
    tagsTrueYellowText: colors.trueyellow300,
};

export default lightTheme;
