# Dockerfiles specific to Acryl
version: "3.8"
services:
  datahub-integrations-service:
    build:
      context: ../
      dockerfile: docker/datahub-integrations-service/Dockerfile
      args:
        APP_ENV: dev
    image: 795586375822.dkr.ecr.us-west-2.amazonaws.com/datahub-integrations-service:debug
    env_file:
      - ../datahub-integrations-service/.env
    environment:
      PYTHONPATH: "/metadata-ingestion/src:/datahub-integrations-service/src:$${PYTHONPATH}"
    volumes:
      - ./datahub-integrations-service/start.sh:/start_datahub_integrations_service.sh
      - ../datahub-integrations-service:/datahub-integrations-service
  datahub-executor-coordinator:
    container_name: datahub-executor-coordinator
    image: 795586375822.dkr.ecr.us-west-2.amazonaws.com/datahub-executor:debug
    build:
      context: ../
      dockerfile: docker/datahub-executor/Dockerfile
      args:
        APP_ENV: dev
    volumes:
      - ./datahub-executor/start.sh:/start_datahub_executor.sh
      - ../metadata-ingestion/src:/metadata-ingestion/src
      - ../datahub-executor:/datahub-executor
    env_file:
      - ./datahub-executor/env/docker.env
    ports:
      - ${DATAHUB_MAPPED_EXECUTOR_PORT:-9004}:9004
  datahub-cloud-router:
    container_name: datahub-cloud-router
    image: 795586375822.dkr.ecr.us-west-2.amazonaws.com/datahub-cloud-router:debug
    build:
      context: ../
      dockerfile: docker/datahub-cloud-router/Dockerfile
      args:
        APP_ENV: dev
    env_file:
      - ./datahub-cloud-router/env/docker.env
    ports:
      - ${DATAHUB_MAPPED_CLOUD_ROUTER_PORT:-9005}:9005
