plugins {
  id 'java-library'
  id 'io.acryl.gradle.plugin.avro'
}

configurations {
  avsc
}

dependencies {
  api externalDependency.avro
  implementation(externalDependency.avroCompiler) {
    exclude group: 'org.apache.velocity', module: 'velocity'
  }
  constraints {
    implementation('commons-collections:commons-collections:3.2.2') {
      because 'Vulnerability Issue'
    }
  }

  avsc project(':metadata-events:mxe-schemas')
}

def genDir = layout.buildDirectory.dir("generated/java")

sourceSets {
  main {
    java {
      srcDir(genDir)
    }
  }
}

task avroCodeGen(type: com.github.davidmc24.gradle.plugin.avro.GenerateAvroJavaTask, dependsOn: configurations.avsc) {
  source("$rootDir/metadata-events/mxe-schemas/src/renamed/avro")
  outputDir = genDir.get().asFile
  dependsOn(':metadata-events:mxe-schemas:syncRenamedAvroToSrc')
  outputs.cacheIf { true }
}

compileJava.dependsOn(avroCodeGen)

idea {
  module {
    sourceDirs += genDir.get().asFile
    generatedSourceDirs += genDir.get().asFile
  }
}

project.rootProject.tasks.idea.dependsOn(avroCodeGen)

clean {
  delete genDir
}
