REDACTED_PREFIX = "***REDACTED:"
REDACTED_SUFFIX = "***"
REDACTED_FORMAT = REDACTED_PREFIX + "{name}" + REDACTED_SUFFIX
MASKING_ERROR_MESSAGE = "[MASKING_ERROR - OUTPUT_SUPPRESSED_FOR_SECURITY]"
CAPACITY_EXCEEDED_MESSAGE = (
    "[MASKING_CAPACITY_EXCEEDED - OUTPUT_SUPPRESSED_FOR_SECURITY]"
)
CIRCUIT_OPEN_MESSAGE = "[REDACTED: Masking Circuit Open]"
SENTINEL_MESSAGES = (
    MASKING_ERROR_MESSAGE,
    CIRCUIT_OPEN_MESSAGE,
    CAPACITY_EXCEEDED_MESSAGE,
)
