MICROSTRATEGY_PLATFORM = "microstrategy"

MSTR_LOGIN_MODE_STANDARD = 1
MSTR_LOGIN_MODE_GUEST = 8

MSTR_OBJECT_TYPE_DASHBOARD = 55
MSTR_OBJECT_TYPE_DOCUMENT = 55
MSTR_OBJECT_TYPE_CUBE = 3
MSTR_OBJECT_TYPE_REPORT = 3

MEASURE_TAG_URN = "urn:li:tag:Measure"
DIMENSION_TAG_URN = "urn:li:tag:Dimension"
TEMPORAL_TAG_URN = "urn:li:tag:Temporal"
