import os

SNOWFLAKE_PLATFORM_NAME = "snowflake"
REDSHIFT_PLATFORM_NAME = "redshift"
BIGQUERY_PLATFORM_NAME = "bigquery"
DATABRICKS_PLATFORM_NAME = "databricks"
SNOWFLAKE_PLATFORM_URN = f"urn:li:dataPlatform:{SNOWFLAKE_PLATFORM_NAME}"
REDSHIFT_PLATFORM_URN = f"urn:li:dataPlatform:{REDSHIFT_PLATFORM_NAME}"
BIGQUERY_PLATFORM_URN = f"urn:li:dataPlatform:{BIGQUERY_PLATFORM_NAME}"
DATABRICKS_PLATFORM_URN = f"urn:li:dataPlatform:{DATABRICKS_PLATFORM_NAME}"
CLI_EXECUTOR_ID = "__datahub_cli_"

LIST_MONITORS_BATCH_SIZE = os.getenv("LIST_MONITORS_BATCH_SIZE", 10000)
LIST_MONITORS_REFRESH_INTERVAL_MINUTES = os.getenv(
    "LIST_MONITORS_REFRESH_INTERVAL_MINUTES", 1
)
