# Generated by ariadne-codegen
# Source: ./tableau-queries.graphql

from typing import Annotated, List, Literal, Optional, Union

from pydantic import Field

from datahub.ingestion.source.tableau.codegen_ariadne.base_model import BaseModel
from datahub.ingestion.source.tableau.codegen_ariadne.enums import RemoteType


class GetItemsCustomSQLTablesConnection(BaseModel):
    custom_sql_tables_connection: "GetItemsCustomSQLTablesConnectionCustomSqlTablesConnection" = Field(
        alias="customSQLTablesConnection"
    )


class GetItemsCustomSQLTablesConnectionCustomSqlTablesConnection(BaseModel):
    nodes: List["GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodes"]
    page_info: "GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionPageInfo" = (
        Field(alias="pageInfo")
    )


class GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodes(BaseModel):
    id: str
    name: Optional[str]
    query: Optional[str]
    columns: List[
        "GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumns"
    ]
    tables: List[
        "GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesTables"
    ]
    connection_type: Optional[str] = Field(alias="connectionType")
    database: Optional[
        "GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesDatabase"
    ]


class GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumns(BaseModel):
    id: str
    name: Optional[str]
    remote_type: RemoteType = Field(alias="remoteType")
    description: Optional[str]
    referenced_by_fields: Optional[
        List[
            Optional[
                "GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFields"
            ]
        ]
    ] = Field(alias="referencedByFields")


class GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFields(
    BaseModel
):
    datasource: Optional[
        Annotated[
            Union[
                "GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourceDatasource",
                "GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourceEmbeddedDatasource",
                "GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourcePublishedDatasource",
            ],
            Field(discriminator="typename__"),
        ]
    ]


class GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourceDatasource(
    BaseModel
):
    typename__: Literal["Datasource"] = Field(alias="__typename")
    id: str
    name: Optional[str]
    upstream_tables: List[
        "GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourceDatasourceUpstreamTables"
    ] = Field(alias="upstreamTables")


class GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourceDatasourceUpstreamTables(
    BaseModel
):
    id: str
    name: Optional[str]
    database: Optional[
        "GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourceDatasourceUpstreamTablesDatabase"
    ]
    schema_: Optional[str] = Field(alias="schema")
    full_name: Optional[str] = Field(alias="fullName")
    connection_type: Optional[str] = Field(alias="connectionType")


class GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourceDatasourceUpstreamTablesDatabase(
    BaseModel
):
    typename__: Literal[
        "CloudFile",
        "DataCloud",
        "Database",
        "DatabaseServer",
        "File",
        "WebDataConnector",
    ] = Field(alias="__typename")
    name: Optional[str]
    id: str


class GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourceEmbeddedDatasource(
    BaseModel
):
    typename__: Literal["EmbeddedDatasource"] = Field(alias="__typename")
    id: str
    name: Optional[str]
    upstream_tables: List[
        "GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourceEmbeddedDatasourceUpstreamTables"
    ] = Field(alias="upstreamTables")
    workbook: Optional[
        "GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourceEmbeddedDatasourceWorkbook"
    ]


class GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourceEmbeddedDatasourceUpstreamTables(
    BaseModel
):
    id: str
    name: Optional[str]
    database: Optional[
        "GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourceEmbeddedDatasourceUpstreamTablesDatabase"
    ]
    schema_: Optional[str] = Field(alias="schema")
    full_name: Optional[str] = Field(alias="fullName")
    connection_type: Optional[str] = Field(alias="connectionType")


class GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourceEmbeddedDatasourceUpstreamTablesDatabase(
    BaseModel
):
    typename__: Literal[
        "CloudFile",
        "DataCloud",
        "Database",
        "DatabaseServer",
        "File",
        "WebDataConnector",
    ] = Field(alias="__typename")
    name: Optional[str]
    id: str


class GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourceEmbeddedDatasourceWorkbook(
    BaseModel
):
    id: str
    name: Optional[str]
    project_name: Optional[str] = Field(alias="projectName")
    luid: str


class GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourcePublishedDatasource(
    BaseModel
):
    typename__: Literal["PublishedDatasource"] = Field(alias="__typename")
    id: str
    name: Optional[str]
    upstream_tables: List[
        "GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourcePublishedDatasourceUpstreamTables"
    ] = Field(alias="upstreamTables")
    project_name: Optional[str] = Field(alias="projectName")
    luid: str


class GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourcePublishedDatasourceUpstreamTables(
    BaseModel
):
    id: str
    name: Optional[str]
    database: Optional[
        "GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourcePublishedDatasourceUpstreamTablesDatabase"
    ]
    schema_: Optional[str] = Field(alias="schema")
    full_name: Optional[str] = Field(alias="fullName")
    connection_type: Optional[str] = Field(alias="connectionType")


class GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourcePublishedDatasourceUpstreamTablesDatabase(
    BaseModel
):
    typename__: Literal[
        "CloudFile",
        "DataCloud",
        "Database",
        "DatabaseServer",
        "File",
        "WebDataConnector",
    ] = Field(alias="__typename")
    name: Optional[str]
    id: str


class GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesTables(BaseModel):
    id: str
    name: Optional[str]
    database: Optional[
        "GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesTablesDatabase"
    ]
    schema_: Optional[str] = Field(alias="schema")
    full_name: Optional[str] = Field(alias="fullName")
    connection_type: Optional[str] = Field(alias="connectionType")
    description: Optional[str]
    columns_connection: Optional[
        "GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesTablesColumnsConnection"
    ] = Field(alias="columnsConnection")


class GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesTablesDatabase(
    BaseModel
):
    typename__: Literal[
        "CloudFile",
        "DataCloud",
        "Database",
        "DatabaseServer",
        "File",
        "WebDataConnector",
    ] = Field(alias="__typename")
    name: Optional[str]
    id: str


class GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesTablesColumnsConnection(
    BaseModel
):
    total_count: int = Field(alias="totalCount")


class GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesDatabase(
    BaseModel
):
    typename__: Literal[
        "CloudFile",
        "DataCloud",
        "Database",
        "DatabaseServer",
        "File",
        "WebDataConnector",
    ] = Field(alias="__typename")
    name: Optional[str]
    id: str
    connection_type: Optional[str] = Field(alias="connectionType")


class GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionPageInfo(BaseModel):
    has_next_page: bool = Field(alias="hasNextPage")
    end_cursor: Optional[str] = Field(alias="endCursor")


GetItemsCustomSQLTablesConnection.model_rebuild()
GetItemsCustomSQLTablesConnectionCustomSqlTablesConnection.model_rebuild()
GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodes.model_rebuild()
GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumns.model_rebuild()
GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFields.model_rebuild()
GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourceDatasource.model_rebuild()
GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourceDatasourceUpstreamTables.model_rebuild()
GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourceEmbeddedDatasource.model_rebuild()
GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourceEmbeddedDatasourceUpstreamTables.model_rebuild()
GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourcePublishedDatasource.model_rebuild()
GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesColumnsReferencedByFieldsDatasourcePublishedDatasourceUpstreamTables.model_rebuild()
GetItemsCustomSQLTablesConnectionCustomSqlTablesConnectionNodesTables.model_rebuild()
