# see https://docs.datahub.com/docs/generated/ingestion/sources/kafka for complete documentation
[source]
  type="kafka"
[source.config.connection]
    bootstrap="localhost:9092"

# see https://docs.datahub.com/docs/metadata-ingestion/sink_docs/console for complete documentation
[sink]
  type = "console"
