# flake8: noqa

# This file is autogenerated by /metadata-ingestion/scripts/avro_codegen.py
# Do not modify manually!

# fmt: off
from .....schema_classes import PartitionSpecClass
from .....schema_classes import TemporalInfoClass
from .....schema_classes import TimeWindowClass


PartitionSpec = PartitionSpecClass
TemporalInfo = TemporalInfoClass
TimeWindow = TimeWindowClass
# fmt: on
