query getIngestion($input: ListIngestionSourcesInput!) {
  listIngestionSources(input: $input) {
    start
    count
    total
    ingestionSources {
      urn
      type
      name
      schedule {
        timezone
        interval
      }
      platform {
        urn
      }
      config {
        recipe
        executorId
        version
        debugMode
        extraArgs {
          key,
          value
        }
      }
    }
  }
}
