query listExecutorConfigs {
  listExecutorConfigs {
    total
    executorConfigs {
      region
      executorId
      queueUrl
      accessKeyId
      secretKeyId
      sessionToken
      expiration
    }
  }
}
