import {
    AZURE_AUTHORITY_URL,
    AZURE_CLIENT_ID,
    AZURE_CLIENT_SECRET,
    AZURE_GRAPH_URL,
    AZURE_INGEST_GROUPS,
    AZURE_INGEST_USERS,
    AZURE_REDIRECT_URL,
    AZURE_TENANT_ID,
    AZURE_TOKEN_URL,
    GROUP_ALLOW,
    GROUP_DENY,
    USER_ALLOW,
    USER_DENY,
} from '@app/ingestV2/source/builder/RecipeForm/azure';
import {
    BIGID_ACCESS_TOKEN,
    BIGID_CONFIDENCE_LEVEL_TAG,
    BIGID_CONNECTION_ALLOW,
    BIGID_CONNECTION_DENY,
    BIGID_CREATE_DATASETS,
    BIGID_ENV,
    BIGID_MIN_CONFIDENCE,
    BIGID_PLATFORM_INSTANCE,
    BIGID_STATEFUL_INGESTION,
    BIGID_SYNC_IDSOR,
    BIGID_SYNC_TAGS,
    BIGID_SYNC_UNLINKED_CLASSIFIERS,
    BIGID_SYNC_UNSTRUCTURED,
    BIGID_URL,
    BIGID_USER_TOKEN,
} from '@app/ingestV2/source/builder/RecipeForm/bigid';
import {
    BIGQUERY_CLIENT_EMAIL,
    BIGQUERY_CLIENT_ID,
    BIGQUERY_PRIVATE_KEY,
    BIGQUERY_PRIVATE_KEY_ID,
} from '@app/ingestV2/source/builder/RecipeForm/bigquery';
import {
    BIGQUERY_BETA_PROJECT_ID,
    DATASET_ALLOW,
    DATASET_DENY,
    PROJECT_ALLOW,
    PROJECT_DENY,
} from '@app/ingestV2/source/builder/RecipeForm/bigqueryBeta';
import {
    COLUMN_PROFILING_ENABLED,
    DATABASE_ALLOW,
    DATABASE_DENY,
    ENV,
    EXTRACT_OWNERS,
    EXTRACT_USAGE_HISTORY,
    FilterRecipeField,
    INCLUDE_LINEAGE,
    INCLUDE_TABLES,
    INCLUDE_TABLE_LINEAGE,
    INCLUDE_VIEWS,
    INGEST_OWNER,
    INGEST_TAGS,
    PROFILING_ENABLED,
    PROFILING_TABLE_LEVEL_ONLY,
    REMOVE_STALE_METADATA_ENABLED,
    RecipeField,
    SCHEMA_ALLOW,
    SCHEMA_DENY,
    SKIP_PERSONAL_FOLDERS,
    START_TIME,
    STATEFUL_INGESTION_ENABLED,
    TABLE_ALLOW,
    TABLE_DENY,
    TABLE_LINEAGE_MODE,
    TABLE_PROFILING_ENABLED,
    VIEW_ALLOW,
    VIEW_DENY,
} from '@app/ingestV2/source/builder/RecipeForm/common';
import {
    CONFLUENCE_API_TOKEN,
    CONFLUENCE_DEPLOYMENT_TYPE,
    CONFLUENCE_PAGE_ALLOW,
    CONFLUENCE_PAGE_DENY,
    CONFLUENCE_PERSONAL_ACCESS_TOKEN,
    CONFLUENCE_SPACE_ALLOW,
    CONFLUENCE_SPACE_DENY,
    CONFLUENCE_URL,
    CONFLUENCE_USERNAME,
} from '@app/ingestV2/source/builder/RecipeForm/confluence';
import {
    CSV_ARRAY_DELIMITER,
    CSV_DELIMITER,
    CSV_FILE_URL,
    CSV_WRITE_SEMANTICS,
} from '@app/ingestV2/source/builder/RecipeForm/csv';
import {
    DATAPLEX_CLIENT_EMAIL,
    DATAPLEX_CLIENT_ID,
    DATAPLEX_ENTRIES_LOCATIONS,
    DATAPLEX_ENTRY_ALLOW,
    DATAPLEX_ENTRY_DENY,
    DATAPLEX_ENTRY_GROUP_ALLOW,
    DATAPLEX_ENTRY_GROUP_DENY,
    DATAPLEX_GLOSSARY_LOCATIONS,
    DATAPLEX_INCLUDE_GLOSSARIES,
    DATAPLEX_INCLUDE_GLOSSARY_TERM_ASSOCIATIONS,
    DATAPLEX_INCLUDE_LINEAGE,
    DATAPLEX_INCLUDE_SCHEMA,
    DATAPLEX_LINEAGE_LOCATIONS,
    DATAPLEX_PRIVATE_KEY,
    DATAPLEX_PRIVATE_KEY_ID,
    DATAPLEX_PROJECT_ALLOW,
    DATAPLEX_PROJECT_DENY,
    DATAPLEX_PROJECT_IDS,
} from '@app/ingestV2/source/builder/RecipeForm/dataplex';
import {
    DBT_CLOUD_ACCOUNT_ID,
    DBT_CLOUD_JOB_ID,
    DBT_CLOUD_PROJECT_ID,
    DBT_CLOUD_TOKEN,
    EXTRACT_OWNERS as DBT_EXTRACT_OWNERS,
    INCLUDE_MODELS,
    INCLUDE_SEEDS,
    INCLUDE_SOURCES,
    INCLUDE_TEST_DEFINITIONS,
    INCLUDE_TEST_RESULTS,
    NODE_ALLOW,
    NODE_DENY,
    TARGET_PLATFORM,
    TARGET_PLATFORM_INSTANCE,
} from '@app/ingestV2/source/builder/RecipeForm/dbt_cloud';
import {
    CONFLUENCE_DOCUMENTS_IMPORT_MODE,
    GITHUB_DOCUMENTS_IMPORT_MODE,
    NOTION_DOCUMENTS_IMPORT_MODE,
} from '@app/ingestV2/source/builder/RecipeForm/documentImportMode';
import {
    DORIS,
    DORIS_DATABASE,
    DORIS_HOST_PORT,
    DORIS_PASSWORD,
    DORIS_USERNAME,
} from '@app/ingestV2/source/builder/RecipeForm/doris';
import {
    DREMIO,
    DREMIO_AUTHENTICATION_METHOD,
    DREMIO_DREMIO_CLOUD_PROJECT_ID,
    DREMIO_DREMIO_CLOUD_REGION,
    DREMIO_HOSTNAME,
    DREMIO_INCLUDE_QUERY_LINEAGE,
    DREMIO_INGEST_OWNER,
    DREMIO_IS_DREMIO_CLOUD,
    DREMIO_PASSWORD,
    DREMIO_PLATFORM_INSTANCE,
    DREMIO_PORT,
    DREMIO_PROFILE_ALLOW,
    DREMIO_PROFILE_DENY,
    DREMIO_TLS,
    DREMIO_USERNAME,
} from '@app/ingestV2/source/builder/RecipeForm/dremio';
import {
    GITHUB_DOCUMENTS_BRANCH,
    GITHUB_DOCUMENTS_CREATE_REPO_ROOT_DOCUMENT,
    GITHUB_DOCUMENTS_FILE_EXTENSIONS,
    GITHUB_DOCUMENTS_PATH_PREFIX,
    GITHUB_DOCUMENTS_REPOSITORY,
    GITHUB_DOCUMENTS_TOKEN,
} from '@app/ingestV2/source/builder/RecipeForm/github-documents';
import {
    GLUE,
    GLUE_AWS_ACCESS_KEY_ID,
    GLUE_AWS_AUTHORIZATION_METHOD,
    GLUE_AWS_REGION,
    GLUE_AWS_ROLE,
    GLUE_AWS_SECRET_ACCESS_KEY,
    GLUE_AWS_SESSION_TOKEN,
    GLUE_CATALOG_ID,
    GLUE_EMIT_S3_LINEAGE,
    GLUE_EXTRACT_OWNERS,
    GLUE_EXTRACT_TRANSFORMS,
    GLUE_INCLUDE_COLUMN_LINEAGE,
    GLUE_PLATFORM_INSTANCE,
    GLUE_PROFILING_ENABLED,
    GLUE_REMOVE_STALE_METADATA_ENABLED,
} from '@app/ingestV2/source/builder/RecipeForm/glue';
import {
    HEX_PROJECT_ALLOW,
    HEX_PROJECT_DENY,
    HEX_TOKEN,
    HEX_WORKSPACE_NAME,
} from '@app/ingestV2/source/builder/RecipeForm/hex';
import {
    HIVE_DATABASE,
    HIVE_HOST_PORT,
    HIVE_PASSWORD,
    HIVE_USERNAME,
} from '@app/ingestV2/source/builder/RecipeForm/hive';
import {
    KAFKA_BOOTSTRAP,
    KAFKA_SASL_MECHANISM,
    KAFKA_SASL_PASSWORD,
    KAFKA_SASL_USERNAME,
    KAFKA_SCHEMA_REGISTRY_URL,
    KAFKA_SCHEMA_REGISTRY_USER_CREDENTIAL,
    KAFKA_SECURITY_PROTOCOL,
    TOPIC_ALLOW,
    TOPIC_DENY,
} from '@app/ingestV2/source/builder/RecipeForm/kafka';
import {
    CHART_ALLOW,
    CHART_DENY,
    LOOKER_BASE_URL,
    LOOKER_CLIENT_ID,
    LOOKER_CLIENT_SECRET,
    DASHBOARD_ALLOW as LOOKER_DASHBOARD_ALLOW,
    DASHBOARD_DENY as LOOKER_DASHBOARD_DENY,
} from '@app/ingestV2/source/builder/RecipeForm/looker';
import {
    CONNECTION_TO_PLATFORM_MAP,
    LOOKML,
    LOOKML_BASE_URL,
    LOOKML_CLIENT_ID,
    LOOKML_CLIENT_SECRET,
    LOOKML_GIT_INFO_DEPLOY_KEY,
    LOOKML_GIT_INFO_REPO,
    LOOKML_GIT_INFO_REPO_SSH_LOCATOR,
    PARSE_TABLE_NAMES_FROM_SQL,
    PROJECT_NAME,
} from '@app/ingestV2/source/builder/RecipeForm/lookml';
import {
    MARIADB,
    MARIADB_DATABASE,
    MARIADB_HOST_PORT,
    MARIADB_PASSWORD,
    MARIADB_USERNAME,
} from '@app/ingestV2/source/builder/RecipeForm/mariadb';
import {
    MATILLION_CLIENT_ID,
    MATILLION_CLIENT_SECRET,
    MATILLION_ENV,
    MATILLION_ENVIRONMENT_ALLOW,
    MATILLION_ENVIRONMENT_DENY,
    MATILLION_INCLUDE_EXECUTIONS,
    MATILLION_INCLUDE_UNPUBLISHED,
    MATILLION_PIPELINE_ALLOW,
    MATILLION_PIPELINE_DENY,
    MATILLION_PLATFORM_INSTANCE,
    MATILLION_PROJECT_ALLOW,
    MATILLION_PROJECT_DENY,
    MATILLION_REGION,
    MATILLION_STATEFUL_INGESTION,
    MATILLION_STREAMING_ALLOW,
    MATILLION_STREAMING_DENY,
} from '@app/ingestV2/source/builder/RecipeForm/matillion-dpc';
import {
    MICROSTRATEGY_AUTH_TYPE,
    MICROSTRATEGY_BASE_URL,
    MICROSTRATEGY_DASHBOARD_ALLOW,
    MICROSTRATEGY_DASHBOARD_DENY,
    MICROSTRATEGY_EMIT_DASHBOARD_DATASET_EDGES,
    MICROSTRATEGY_EXTRACT_CHARTS,
    MICROSTRATEGY_EXTRACT_CUBES,
    MICROSTRATEGY_EXTRACT_DASHBOARDS,
    MICROSTRATEGY_EXTRACT_DASHBOARD_DEPENDENCIES,
    MICROSTRATEGY_EXTRACT_INDEPENDENT_REPORTS,
    MICROSTRATEGY_EXTRACT_LINEAGE,
    MICROSTRATEGY_EXTRACT_METRIC_EXPRESSIONS,
    MICROSTRATEGY_EXTRACT_MODEL_LINEAGE,
    MICROSTRATEGY_EXTRACT_REPORTS,
    MICROSTRATEGY_EXTRACT_REPORT_SQL_LINEAGE,
    MICROSTRATEGY_EXTRACT_SOURCE_WAREHOUSES,
    MICROSTRATEGY_EXTRACT_USAGE_STATISTICS,
    MICROSTRATEGY_EXTRACT_VISUALIZATION_DETAILS,
    MICROSTRATEGY_EXTRACT_WAREHOUSE_LINEAGE,
    MICROSTRATEGY_FOLDER_ALLOW,
    MICROSTRATEGY_FOLDER_DENY,
    MICROSTRATEGY_INCLUDE_HIDDEN,
    MICROSTRATEGY_INGEST_OWNER,
    MICROSTRATEGY_PASSWORD,
    MICROSTRATEGY_PLATFORM_INSTANCE,
    MICROSTRATEGY_PROJECT_ALLOW,
    MICROSTRATEGY_PROJECT_DENY,
    MICROSTRATEGY_REPORT_ALLOW,
    MICROSTRATEGY_REPORT_DENY,
    MICROSTRATEGY_TAG_MEASURES_AND_DIMENSIONS,
    MICROSTRATEGY_USERNAME,
    MICROSTRATEGY_VERIFY_SSL,
} from '@app/ingestV2/source/builder/RecipeForm/microstrategy';
import {
    MSSQL,
    MSSQL_DATABASE,
    MSSQL_HOST_PORT,
    MSSQL_PASSWORD,
    MSSQL_USERNAME,
} from '@app/ingestV2/source/builder/RecipeForm/mssql';
import { MYSQL_HOST_PORT, MYSQL_PASSWORD, MYSQL_USERNAME } from '@app/ingestV2/source/builder/RecipeForm/mysql';
import { NOTION_API_KEY, NOTION_PAGE_IDS } from '@app/ingestV2/source/builder/RecipeForm/notion';
import {
    ODCS_AWS_REGION,
    ODCS_EMIT_ASSERTIONS,
    ODCS_EMIT_LOGICAL_PARENT,
    ODCS_EMIT_SCHEMA_ASSERTION,
    ODCS_GCS_HMAC_KEY_ID,
    ODCS_GCS_HMAC_KEY_SECRET,
    ODCS_GIT_INFO_BRANCH,
    ODCS_GIT_INFO_DEPLOY_KEY,
    ODCS_GIT_INFO_REPO,
    ODCS_PATH,
    ODCS_REPLICATE_CONTRACT_METADATA,
    ODCS_SCHEMA_ASSERTION_COMPATIBILITY,
    ODCS_STRICT_VALIDATION,
    ODCS_TAG_PREFIX,
    ODCS_VERIFY_PHYSICAL_URNS_EXIST,
} from '@app/ingestV2/source/builder/RecipeForm/odcs';
import {
    INCLUDE_DEPROVISIONED_USERS,
    INCLUDE_SUSPENDED_USERS,
    INGEST_GROUPS,
    INGEST_USERS,
    OKTA_API_TOKEN,
    OKTA_DOMAIN_URL,
    PROFILE_TO_GROUP,
    PROFILE_TO_GROUP_REGX_ALLOW,
    PROFILE_TO_GROUP_REGX_DENY,
    PROFILE_TO_USER,
    PROFILE_TO_USER_REGEX_DENY,
    PROFILE_TO_USER_REGX_ALLOW,
    SKIP_USERS_WITHOUT_GROUP,
} from '@app/ingestV2/source/builder/RecipeForm/okta';
import {
    ORACLE,
    ORACLE_CONVERT_URNS_TO_LOWERCASE,
    ORACLE_DATABASE,
    ORACLE_EXTRACT_USAGE_HISTORY,
    ORACLE_HOST_PORT,
    ORACLE_IDENTIFIER,
    ORACLE_INCLUDE_TABLES,
    ORACLE_INCLUDE_VIEWS,
    ORACLE_INCLUDE_VIEW_COLUMN_LINEAGE,
    ORACLE_INCLUDE_VIEW_LINEAGE,
    ORACLE_PASSWORD,
    ORACLE_PLATFORM_INSTANCE,
    ORACLE_PROFILING_ENABLED,
    ORACLE_SERVICE_NAME,
    ORACLE_USERNAME,
} from '@app/ingestV2/source/builder/RecipeForm/oracle';
import {
    POSTGRES_DATABASE,
    POSTGRES_HOST_PORT,
    POSTGRES_PASSWORD,
    POSTGRES_USERNAME,
} from '@app/ingestV2/source/builder/RecipeForm/postgres';
import {
    ADMIN_APIS_ONLY,
    EXTRACT_ENDORSEMENTS_AS_TAGS,
    EXTRACT_OWNERSHIP,
    INCLUDE_POWERBI_LINEAGE,
    INCLUDE_REPORTS,
    INCLUDE_WORKSPACES,
    POWERBI_CLIENT_ID,
    POWERBI_CLIENT_SECRET,
    POWERBI_TENANT_ID,
    WORKSPACE_ID_ALLOW,
    WORKSPACE_ID_DENY,
} from '@app/ingestV2/source/builder/RecipeForm/powerbi';
import {
    PRESTO,
    PRESTO_DATABASE,
    PRESTO_HOST_PORT,
    PRESTO_PASSWORD,
    PRESTO_USERNAME,
} from '@app/ingestV2/source/builder/RecipeForm/presto';
import {
    RDF_DIALECT,
    RDF_ENVIRONMENT,
    RDF_EXTENSIONS,
    RDF_FORMAT,
    RDF_PARENT_GLOSSARY_NODE,
    RDF_RECURSIVE,
    RDF_SOURCE,
} from '@app/ingestV2/source/builder/RecipeForm/rdf';
import {
    REDSHIFT_DATABASE,
    REDSHIFT_HOST_PORT,
    REDSHIFT_PASSWORD,
    REDSHIFT_USERNAME,
} from '@app/ingestV2/source/builder/RecipeForm/redshift';
import {
    FOLDER_ALLOW,
    FOLDER_DENY,
    INGEST_APPLICATIONS,
    INGEST_STORIES,
    RESOURCE_ID_ALLOW,
    RESOURCE_ID_DENY,
    RESOURCE_NAME_ALLOW,
    RESOURCE_NAME_DENY,
    SAC_CLIENT_ID,
    SAC_CLIENT_SECRET,
    SAC_TENANT_URL,
    SAC_TOKEN_URL,
} from '@app/ingestV2/source/builder/RecipeForm/sac';
import {
    SNOWFLAKE_ACCOUNT_ID,
    SNOWFLAKE_AUTHENTICATION_TYPE,
    SNOWFLAKE_PASSWORD,
    SNOWFLAKE_PRIVATE_KEY,
    SNOWFLAKE_PRIVATE_KEY_PASSWORD,
    SNOWFLAKE_ROLE,
    SNOWFLAKE_USERNAME,
    SNOWFLAKE_WAREHOUSE,
} from '@app/ingestV2/source/builder/RecipeForm/snowflake';
import {
    TABLEAU_CONNECTION_URI,
    TABLEAU_PASSWORD,
    TABLEAU_PROJECT,
    TABLEAU_SITE,
    TABLEAU_TOKEN_NAME,
    TABLEAU_TOKEN_VALUE,
    TABLEAU_USERNAME,
} from '@app/ingestV2/source/builder/RecipeForm/tableau';
import {
    TIDB,
    TIDB_DATABASE,
    TIDB_HOST_PORT,
    TIDB_PASSWORD,
    TIDB_USERNAME,
} from '@app/ingestV2/source/builder/RecipeForm/tidb';
import {
    TRINO,
    TRINO_DATABASE,
    TRINO_HOST_PORT,
    TRINO_PASSWORD,
    TRINO_USERNAME,
} from '@app/ingestV2/source/builder/RecipeForm/trino';
import {
    INCLUDE_COLUMN_LINEAGE,
    TOKEN,
    UNITY_CATALOG_ALLOW,
    UNITY_CATALOG_DENY,
    UNITY_METASTORE_ID_ALLOW,
    UNITY_METASTORE_ID_DENY,
    UNITY_TABLE_ALLOW,
    UNITY_TABLE_DENY,
    WORKSPACE_URL,
} from '@app/ingestV2/source/builder/RecipeForm/unity_catalog';
import {
    INCLUDE_MLMODELS,
    INCLUDE_PROJECTIONS,
    INCLUDE_PROJECTIONS_LINEAGE,
    INCLUDE_VIEW_LINEAGE,
    VERTICA_DATABASE,
    VERTICA_HOST_PORT,
    VERTICA_PASSWORD,
    VERTICA_USERNAME,
} from '@app/ingestV2/source/builder/RecipeForm/vertica';
import {
    AZURE,
    BIGID,
    CONFLUENCE,
    CSV,
    DATABRICKS,
    DBT_CLOUD,
    GITHUB_DOCUMENTS,
    MATILLION_DPC,
    MICROSTRATEGY,
    MYSQL,
    NOTION,
    OKTA,
    POWER_BI,
    RDF,
    SAC,
    VERTICA,
} from '@app/ingestV2/source/builder/constants';
import { BIGQUERY } from '@app/ingestV2/source/conf/bigquery/bigquery';
import { DATAPLEX } from '@app/ingestV2/source/conf/dataplex/dataplex';
import { HEX } from '@app/ingestV2/source/conf/hex/hex';
import { HIVE } from '@app/ingestV2/source/conf/hive/hive';
import { KAFKA } from '@app/ingestV2/source/conf/kafka/kafka';
import { LOOKER } from '@app/ingestV2/source/conf/looker/looker';
import { ODCS } from '@app/ingestV2/source/conf/odcs/odcs';
import { POSTGRES } from '@app/ingestV2/source/conf/postgres/postgres';
import { REDSHIFT } from '@app/ingestV2/source/conf/redshift/redshift';
import { SNOWFLAKE } from '@app/ingestV2/source/conf/snowflake/snowflake';
import { TABLEAU } from '@app/ingestV2/source/conf/tableau/tableau';

export enum RecipeSections {
    Connection = 0,
    Filter = 1,
    Advanced = 2,
}

interface RecipeFields {
    [key: string]: {
        fields: RecipeField[];
        filterFields: FilterRecipeField[];
        advancedFields: RecipeField[];
        connectionSectionTooltip?: string;
        filterSectionTooltip?: string;
        advancedSectionTooltip?: string;
        defaultOpenSections?: RecipeSections[];
        hasDynamicFields?: boolean;
    };
}

export const RECIPE_FIELDS: RecipeFields = {
    [SNOWFLAKE]: {
        fields: [
            SNOWFLAKE_ACCOUNT_ID,
            SNOWFLAKE_WAREHOUSE,
            SNOWFLAKE_USERNAME,
            SNOWFLAKE_AUTHENTICATION_TYPE,
            SNOWFLAKE_PASSWORD,
            SNOWFLAKE_PRIVATE_KEY,
            SNOWFLAKE_PRIVATE_KEY_PASSWORD,
            SNOWFLAKE_ROLE,
        ],
        advancedFields: [
            INCLUDE_TABLES,
            INCLUDE_VIEWS,
            INCLUDE_LINEAGE,
            TABLE_PROFILING_ENABLED,
            COLUMN_PROFILING_ENABLED,
            STATEFUL_INGESTION_ENABLED,
        ],
        filterFields: [
            DATABASE_ALLOW,
            DATABASE_DENY,
            SCHEMA_ALLOW,
            SCHEMA_DENY,
            TABLE_ALLOW,
            TABLE_DENY,
            VIEW_ALLOW,
            VIEW_DENY,
        ],
        filterSectionTooltip: 'Include or exclude specific Databases, Schemas, Tables and Views from ingestion.',
    },
    [BIGQUERY]: {
        fields: [
            BIGQUERY_BETA_PROJECT_ID,
            BIGQUERY_PRIVATE_KEY,
            BIGQUERY_PRIVATE_KEY_ID,
            BIGQUERY_CLIENT_EMAIL,
            BIGQUERY_CLIENT_ID,
        ],
        advancedFields: [
            INCLUDE_TABLES,
            INCLUDE_VIEWS,
            INCLUDE_TABLE_LINEAGE,
            TABLE_PROFILING_ENABLED,
            COLUMN_PROFILING_ENABLED,
            START_TIME,
            STATEFUL_INGESTION_ENABLED,
        ],
        filterFields: [
            PROJECT_ALLOW,
            PROJECT_DENY,
            DATASET_ALLOW,
            DATASET_DENY,
            TABLE_ALLOW,
            TABLE_DENY,
            VIEW_ALLOW,
            VIEW_DENY,
        ],
        filterSectionTooltip: 'Include or exclude specific Projects, Datasets, Tables and Views from ingestion.',
    },
    [DATAPLEX]: {
        fields: [
            DATAPLEX_PROJECT_IDS,
            DATAPLEX_PRIVATE_KEY,
            DATAPLEX_PRIVATE_KEY_ID,
            DATAPLEX_CLIENT_EMAIL,
            DATAPLEX_CLIENT_ID,
        ],
        filterFields: [
            DATAPLEX_PROJECT_ALLOW,
            DATAPLEX_PROJECT_DENY,
            DATAPLEX_ENTRY_ALLOW,
            DATAPLEX_ENTRY_DENY,
            DATAPLEX_ENTRY_GROUP_ALLOW,
            DATAPLEX_ENTRY_GROUP_DENY,
        ],
        advancedFields: [
            DATAPLEX_ENTRIES_LOCATIONS,
            DATAPLEX_INCLUDE_SCHEMA,
            DATAPLEX_INCLUDE_LINEAGE,
            DATAPLEX_INCLUDE_GLOSSARIES,
            DATAPLEX_INCLUDE_GLOSSARY_TERM_ASSOCIATIONS,
            DATAPLEX_LINEAGE_LOCATIONS,
            DATAPLEX_GLOSSARY_LOCATIONS,
            STATEFUL_INGESTION_ENABLED,
        ],
        filterSectionTooltip: 'Include or exclude specific Projects, Entries, and Entry Groups from ingestion.',
    },
    [ODCS]: {
        fields: [ODCS_PATH],
        filterFields: [],
        advancedFields: [
            ODCS_EMIT_ASSERTIONS,
            ODCS_EMIT_SCHEMA_ASSERTION,
            ODCS_SCHEMA_ASSERTION_COMPATIBILITY,
            ODCS_EMIT_LOGICAL_PARENT,
            ODCS_VERIFY_PHYSICAL_URNS_EXIST,
            ODCS_STRICT_VALIDATION,
            ODCS_REPLICATE_CONTRACT_METADATA,
            ODCS_TAG_PREFIX,
            ODCS_GIT_INFO_REPO,
            ODCS_GIT_INFO_BRANCH,
            ODCS_GIT_INFO_DEPLOY_KEY,
            ODCS_AWS_REGION,
            ODCS_GCS_HMAC_KEY_ID,
            ODCS_GCS_HMAC_KEY_SECRET,
            ENV,
            STATEFUL_INGESTION_ENABLED,
        ],
    },
    [REDSHIFT]: {
        fields: [REDSHIFT_HOST_PORT, REDSHIFT_DATABASE, REDSHIFT_USERNAME, REDSHIFT_PASSWORD],
        advancedFields: [
            INCLUDE_TABLES,
            INCLUDE_VIEWS,
            INCLUDE_TABLE_LINEAGE,
            TABLE_PROFILING_ENABLED,
            COLUMN_PROFILING_ENABLED,
            TABLE_LINEAGE_MODE,
            STATEFUL_INGESTION_ENABLED,
        ],
        filterFields: [SCHEMA_ALLOW, SCHEMA_DENY, TABLE_ALLOW, TABLE_DENY, VIEW_ALLOW, VIEW_DENY],
        filterSectionTooltip: 'Include or exclude specific Schemas, Tables and Views from ingestion.',
    },
    [TABLEAU]: {
        fields: [
            TABLEAU_CONNECTION_URI,
            TABLEAU_PROJECT,
            TABLEAU_SITE,
            TABLEAU_TOKEN_NAME,
            TABLEAU_TOKEN_VALUE,
            STATEFUL_INGESTION_ENABLED,
            TABLEAU_USERNAME,
            TABLEAU_PASSWORD,
        ],
        filterFields: [],
        advancedFields: [INGEST_TAGS, INGEST_OWNER],
    },
    [LOOKER]: {
        fields: [LOOKER_BASE_URL, LOOKER_CLIENT_ID, LOOKER_CLIENT_SECRET],
        filterFields: [LOOKER_DASHBOARD_ALLOW, LOOKER_DASHBOARD_DENY, CHART_ALLOW, CHART_DENY],
        advancedFields: [EXTRACT_USAGE_HISTORY, EXTRACT_OWNERS, SKIP_PERSONAL_FOLDERS, STATEFUL_INGESTION_ENABLED],
        filterSectionTooltip: 'Include or exclude specific Dashboard, Charts from Looker ingestion.',
    },
    [LOOKML]: {
        fields: [
            LOOKML_GIT_INFO_REPO,
            LOOKML_GIT_INFO_REPO_SSH_LOCATOR,
            LOOKML_GIT_INFO_DEPLOY_KEY,
            PROJECT_NAME,
            LOOKML_BASE_URL,
            LOOKML_CLIENT_ID,
            LOOKML_CLIENT_SECRET,
        ],
        filterFields: [],
        advancedFields: [PARSE_TABLE_NAMES_FROM_SQL, CONNECTION_TO_PLATFORM_MAP, STATEFUL_INGESTION_ENABLED],
        advancedSectionTooltip:
            'In order to ingest LookML data properly, you must either fill out Looker API client information (Base URL, Client ID, Client Secret) or an offline specification of the connection to platform mapping and the project name (Connection To Platform Map, Project Name).',
        defaultOpenSections: [RecipeSections.Connection, RecipeSections.Advanced],
    },
    [KAFKA]: {
        fields: [
            KAFKA_SECURITY_PROTOCOL,
            KAFKA_SASL_MECHANISM,
            KAFKA_SASL_USERNAME,
            KAFKA_SASL_PASSWORD,
            KAFKA_BOOTSTRAP,
            KAFKA_SCHEMA_REGISTRY_URL,
            KAFKA_SCHEMA_REGISTRY_USER_CREDENTIAL,
        ],
        filterFields: [TOPIC_ALLOW, TOPIC_DENY],
        advancedFields: [STATEFUL_INGESTION_ENABLED],
        filterSectionTooltip:
            'Filter out data assets based on allow/deny regex patterns we match against. Deny patterns take precedence over allow patterns.',
    },
    [POSTGRES]: {
        fields: [POSTGRES_HOST_PORT, POSTGRES_USERNAME, POSTGRES_PASSWORD, POSTGRES_DATABASE],
        filterFields: [SCHEMA_ALLOW, SCHEMA_DENY, TABLE_ALLOW, TABLE_DENY, VIEW_ALLOW, VIEW_DENY],
        advancedFields: [
            INCLUDE_TABLES,
            INCLUDE_VIEWS,
            TABLE_PROFILING_ENABLED,
            COLUMN_PROFILING_ENABLED,
            STATEFUL_INGESTION_ENABLED,
        ],
        filterSectionTooltip: 'Include or exclude specific Schemas, Tables and Views from ingestion.',
    },
    [MYSQL]: {
        fields: [MYSQL_HOST_PORT, MYSQL_USERNAME, MYSQL_PASSWORD],
        filterFields: [
            DATABASE_ALLOW,
            DATABASE_DENY,
            SCHEMA_ALLOW,
            SCHEMA_DENY,
            TABLE_ALLOW,
            TABLE_DENY,
            VIEW_ALLOW,
            VIEW_DENY,
        ],
        advancedFields: [
            INCLUDE_TABLES,
            INCLUDE_VIEWS,
            TABLE_PROFILING_ENABLED,
            COLUMN_PROFILING_ENABLED,
            STATEFUL_INGESTION_ENABLED,
        ],
        filterSectionTooltip: 'Include or exclude specific Databases, Schemas, Tables and Views from ingestion.',
    },
    [HIVE]: {
        fields: [HIVE_HOST_PORT, HIVE_USERNAME, HIVE_PASSWORD, HIVE_DATABASE],
        filterFields: [SCHEMA_ALLOW, SCHEMA_DENY, TABLE_ALLOW, TABLE_DENY, VIEW_ALLOW, VIEW_DENY],
        advancedFields: [INCLUDE_TABLES, TABLE_PROFILING_ENABLED, COLUMN_PROFILING_ENABLED, STATEFUL_INGESTION_ENABLED],
        filterSectionTooltip: 'Include or exclude specific Schemas, Tables and Views from ingestion.',
    },
    [PRESTO]: {
        fields: [PRESTO_HOST_PORT, PRESTO_USERNAME, PRESTO_PASSWORD, PRESTO_DATABASE],
        filterFields: [SCHEMA_ALLOW, SCHEMA_DENY, TABLE_ALLOW, TABLE_DENY, VIEW_ALLOW, VIEW_DENY],
        advancedFields: [
            INCLUDE_TABLES,
            INCLUDE_VIEWS,
            TABLE_PROFILING_ENABLED,
            COLUMN_PROFILING_ENABLED,
            STATEFUL_INGESTION_ENABLED,
        ],
        filterSectionTooltip: 'Include or exclude specific Schemas, Tables and Views from ingestion.',
    },
    [MSSQL]: {
        fields: [MSSQL_HOST_PORT, MSSQL_USERNAME, MSSQL_PASSWORD, MSSQL_DATABASE],
        filterFields: [SCHEMA_ALLOW, SCHEMA_DENY, TABLE_ALLOW, TABLE_DENY, VIEW_ALLOW, VIEW_DENY],
        advancedFields: [
            INCLUDE_TABLES,
            INCLUDE_VIEWS,
            TABLE_PROFILING_ENABLED,
            COLUMN_PROFILING_ENABLED,
            STATEFUL_INGESTION_ENABLED,
        ],
        filterSectionTooltip: 'Include or exclude specific Schemas, Tables and Views from ingestion.',
    },
    [TRINO]: {
        fields: [TRINO_HOST_PORT, TRINO_USERNAME, TRINO_PASSWORD, TRINO_DATABASE],
        filterFields: [SCHEMA_ALLOW, SCHEMA_DENY, TABLE_ALLOW, TABLE_DENY, VIEW_ALLOW, VIEW_DENY],
        advancedFields: [
            INCLUDE_TABLES,
            INCLUDE_VIEWS,
            TABLE_PROFILING_ENABLED,
            COLUMN_PROFILING_ENABLED,
            STATEFUL_INGESTION_ENABLED,
        ],
        filterSectionTooltip: 'Include or exclude specific Schemas, Tables and Views from ingestion.',
    },
    [MARIADB]: {
        fields: [MARIADB_HOST_PORT, MARIADB_USERNAME, MARIADB_PASSWORD, MARIADB_DATABASE],
        filterFields: [SCHEMA_ALLOW, SCHEMA_DENY, TABLE_ALLOW, TABLE_DENY, VIEW_ALLOW, VIEW_DENY],
        advancedFields: [
            INCLUDE_TABLES,
            INCLUDE_VIEWS,
            TABLE_PROFILING_ENABLED,
            COLUMN_PROFILING_ENABLED,
            STATEFUL_INGESTION_ENABLED,
        ],
        filterSectionTooltip: 'Include or exclude specific Schemas, Tables and Views from ingestion.',
    },
    [TIDB]: {
        fields: [TIDB_HOST_PORT, TIDB_USERNAME, TIDB_PASSWORD, TIDB_DATABASE],
        filterFields: [SCHEMA_ALLOW, SCHEMA_DENY, TABLE_ALLOW, TABLE_DENY, VIEW_ALLOW, VIEW_DENY],
        advancedFields: [
            INCLUDE_TABLES,
            INCLUDE_VIEWS,
            TABLE_PROFILING_ENABLED,
            COLUMN_PROFILING_ENABLED,
            STATEFUL_INGESTION_ENABLED,
        ],
        filterSectionTooltip: 'Include or exclude specific Schemas, Tables and Views from ingestion.',
    },
    [DORIS]: {
        fields: [DORIS_HOST_PORT, DORIS_USERNAME, DORIS_PASSWORD, DORIS_DATABASE],
        filterFields: [SCHEMA_ALLOW, SCHEMA_DENY, TABLE_ALLOW, TABLE_DENY, VIEW_ALLOW, VIEW_DENY],
        advancedFields: [
            INCLUDE_TABLES,
            INCLUDE_VIEWS,
            TABLE_PROFILING_ENABLED,
            COLUMN_PROFILING_ENABLED,
            STATEFUL_INGESTION_ENABLED,
        ],
        filterSectionTooltip: 'Include or exclude specific Schemas, Tables and Views from ingestion.',
    },
    [DATABRICKS]: {
        fields: [WORKSPACE_URL, TOKEN],
        filterFields: [
            UNITY_METASTORE_ID_ALLOW,
            UNITY_METASTORE_ID_DENY,
            UNITY_CATALOG_ALLOW,
            UNITY_CATALOG_DENY,
            SCHEMA_ALLOW,
            SCHEMA_DENY,
            UNITY_TABLE_ALLOW,
            UNITY_TABLE_DENY,
        ],
        advancedFields: [INCLUDE_TABLE_LINEAGE, INCLUDE_COLUMN_LINEAGE, STATEFUL_INGESTION_ENABLED],
        filterSectionTooltip: 'Include or exclude specific Metastores, Catalogs, Schemas, and Tables from ingestion.',
    },
    [DBT_CLOUD]: {
        fields: [
            DBT_CLOUD_ACCOUNT_ID,
            DBT_CLOUD_PROJECT_ID,
            DBT_CLOUD_JOB_ID,
            DBT_CLOUD_TOKEN,
            TARGET_PLATFORM,
            TARGET_PLATFORM_INSTANCE,
        ],
        filterFields: [NODE_ALLOW, NODE_DENY],
        advancedFields: [
            INCLUDE_MODELS,
            INCLUDE_SOURCES,
            INCLUDE_SEEDS,
            INCLUDE_TEST_DEFINITIONS,
            INCLUDE_TEST_RESULTS,
            DBT_EXTRACT_OWNERS,
            STATEFUL_INGESTION_ENABLED,
        ],
        filterSectionTooltip: 'Include or exclude specific dbt Node (resources) from ingestion.',
    },
    [BIGID]: {
        fields: [BIGID_URL, BIGID_USER_TOKEN, BIGID_ACCESS_TOKEN, BIGID_ENV, BIGID_PLATFORM_INSTANCE],
        filterFields: [BIGID_CONNECTION_ALLOW, BIGID_CONNECTION_DENY],
        advancedFields: [
            BIGID_MIN_CONFIDENCE,
            BIGID_CREATE_DATASETS,
            BIGID_CONFIDENCE_LEVEL_TAG,
            BIGID_SYNC_TAGS,
            BIGID_SYNC_UNLINKED_CLASSIFIERS,
            BIGID_SYNC_IDSOR,
            BIGID_SYNC_UNSTRUCTURED,
            BIGID_STATEFUL_INGESTION,
        ],
        filterSectionTooltip: 'Include or exclude specific BigID connections (data sources) from ingestion.',
    },
    [MATILLION_DPC]: {
        fields: [
            MATILLION_CLIENT_ID,
            MATILLION_CLIENT_SECRET,
            MATILLION_REGION,
            MATILLION_ENV,
            MATILLION_PLATFORM_INSTANCE,
        ],
        filterFields: [
            MATILLION_PROJECT_ALLOW,
            MATILLION_PROJECT_DENY,
            MATILLION_ENVIRONMENT_ALLOW,
            MATILLION_ENVIRONMENT_DENY,
            MATILLION_PIPELINE_ALLOW,
            MATILLION_PIPELINE_DENY,
            MATILLION_STREAMING_ALLOW,
            MATILLION_STREAMING_DENY,
        ],
        advancedFields: [MATILLION_INCLUDE_EXECUTIONS, MATILLION_INCLUDE_UNPUBLISHED, MATILLION_STATEFUL_INGESTION],
        filterSectionTooltip:
            'Include or exclude specific Projects, Environments, Pipelines, and Streaming Pipelines from ingestion.',
    },
    [POWER_BI]: {
        fields: [POWERBI_TENANT_ID, POWERBI_CLIENT_ID, POWERBI_CLIENT_SECRET],
        filterFields: [WORKSPACE_ID_ALLOW, WORKSPACE_ID_DENY],
        advancedFields: [
            INCLUDE_WORKSPACES,
            INCLUDE_REPORTS,
            INCLUDE_POWERBI_LINEAGE,
            EXTRACT_OWNERSHIP,
            EXTRACT_ENDORSEMENTS_AS_TAGS,
            ADMIN_APIS_ONLY,
            STATEFUL_INGESTION_ENABLED,
        ],
        filterSectionTooltip: 'Include or exclude specific PowerBI Workspaces from ingestion.',
    },
    [MICROSTRATEGY]: {
        fields: [
            MICROSTRATEGY_BASE_URL,
            MICROSTRATEGY_AUTH_TYPE,
            MICROSTRATEGY_USERNAME,
            MICROSTRATEGY_PASSWORD,
            MICROSTRATEGY_PLATFORM_INSTANCE,
        ],
        filterFields: [
            MICROSTRATEGY_PROJECT_ALLOW,
            MICROSTRATEGY_PROJECT_DENY,
            MICROSTRATEGY_FOLDER_ALLOW,
            MICROSTRATEGY_FOLDER_DENY,
            MICROSTRATEGY_DASHBOARD_ALLOW,
            MICROSTRATEGY_DASHBOARD_DENY,
            MICROSTRATEGY_REPORT_ALLOW,
            MICROSTRATEGY_REPORT_DENY,
        ],
        advancedFields: [
            MICROSTRATEGY_EXTRACT_DASHBOARDS,
            MICROSTRATEGY_EXTRACT_CHARTS,
            MICROSTRATEGY_EXTRACT_CUBES,
            MICROSTRATEGY_EXTRACT_REPORTS,
            MICROSTRATEGY_EXTRACT_INDEPENDENT_REPORTS,
            MICROSTRATEGY_EXTRACT_LINEAGE,
            MICROSTRATEGY_EXTRACT_VISUALIZATION_DETAILS,
            MICROSTRATEGY_EXTRACT_SOURCE_WAREHOUSES,
            MICROSTRATEGY_EXTRACT_DASHBOARD_DEPENDENCIES,
            MICROSTRATEGY_EXTRACT_METRIC_EXPRESSIONS,
            MICROSTRATEGY_EXTRACT_MODEL_LINEAGE,
            MICROSTRATEGY_EXTRACT_WAREHOUSE_LINEAGE,
            MICROSTRATEGY_EXTRACT_REPORT_SQL_LINEAGE,
            MICROSTRATEGY_EXTRACT_USAGE_STATISTICS,
            MICROSTRATEGY_EMIT_DASHBOARD_DATASET_EDGES,
            MICROSTRATEGY_TAG_MEASURES_AND_DIMENSIONS,
            MICROSTRATEGY_INGEST_OWNER,
            MICROSTRATEGY_INCLUDE_HIDDEN,
            MICROSTRATEGY_VERIFY_SSL,
            STATEFUL_INGESTION_ENABLED,
        ],
        filterSectionTooltip:
            'Include or exclude specific Projects, Folders, Dashboards, and Reports from MicroStrategy ingestion.',
    },
    [VERTICA]: {
        fields: [VERTICA_HOST_PORT, VERTICA_DATABASE, VERTICA_USERNAME, VERTICA_PASSWORD],
        filterFields: [SCHEMA_ALLOW, SCHEMA_DENY, TABLE_ALLOW, TABLE_DENY, VIEW_ALLOW, VIEW_DENY],
        advancedFields: [
            INCLUDE_TABLES,
            INCLUDE_VIEWS,
            INCLUDE_PROJECTIONS,
            INCLUDE_MLMODELS,
            INCLUDE_VIEW_LINEAGE,
            INCLUDE_PROJECTIONS_LINEAGE,
            TABLE_PROFILING_ENABLED,
        ],
        filterSectionTooltip: 'Include or exclude specific Schemas, Tables, Views and Projections from ingestion.',
    },
    [CSV]: {
        fields: [CSV_FILE_URL],
        filterFields: [],
        advancedFields: [CSV_ARRAY_DELIMITER, CSV_DELIMITER, CSV_WRITE_SEMANTICS],
    },
    [OKTA]: {
        fields: [OKTA_DOMAIN_URL, OKTA_API_TOKEN, PROFILE_TO_USER, PROFILE_TO_GROUP],
        filterFields: [
            PROFILE_TO_GROUP_REGX_ALLOW,
            PROFILE_TO_GROUP_REGX_DENY,
            PROFILE_TO_USER_REGX_ALLOW,
            PROFILE_TO_USER_REGEX_DENY,
        ],
        advancedFields: [
            INGEST_USERS,
            INGEST_GROUPS,
            INCLUDE_DEPROVISIONED_USERS,
            INCLUDE_SUSPENDED_USERS,
            STATEFUL_INGESTION_ENABLED,
            SKIP_USERS_WITHOUT_GROUP,
        ],
    },
    [HEX]: {
        fields: [HEX_WORKSPACE_NAME, HEX_TOKEN],
        filterFields: [HEX_PROJECT_ALLOW, HEX_PROJECT_DENY],
        advancedFields: [STATEFUL_INGESTION_ENABLED],
        filterSectionTooltip: 'Include or exclude specific Hex Projects from ingestion.',
    },
    [NOTION]: {
        fields: [NOTION_API_KEY, NOTION_PAGE_IDS, NOTION_DOCUMENTS_IMPORT_MODE],
        filterFields: [],
        advancedFields: [],
    },
    [GITHUB_DOCUMENTS]: {
        fields: [
            GITHUB_DOCUMENTS_TOKEN,
            GITHUB_DOCUMENTS_REPOSITORY,
            GITHUB_DOCUMENTS_BRANCH,
            GITHUB_DOCUMENTS_PATH_PREFIX,
            GITHUB_DOCUMENTS_FILE_EXTENSIONS,
            GITHUB_DOCUMENTS_IMPORT_MODE,
        ],
        filterFields: [],
        advancedFields: [GITHUB_DOCUMENTS_CREATE_REPO_ROOT_DOCUMENT],
    },
    [CONFLUENCE]: {
        fields: [
            CONFLUENCE_DEPLOYMENT_TYPE,
            CONFLUENCE_URL,
            CONFLUENCE_USERNAME,
            CONFLUENCE_API_TOKEN,
            CONFLUENCE_PERSONAL_ACCESS_TOKEN,
            CONFLUENCE_DOCUMENTS_IMPORT_MODE,
        ],
        filterFields: [CONFLUENCE_SPACE_ALLOW, CONFLUENCE_SPACE_DENY, CONFLUENCE_PAGE_ALLOW, CONFLUENCE_PAGE_DENY],
        advancedFields: [],
        filterSectionTooltip:
            'Control which Confluence content is ingested by filtering spaces and pages. Leave empty to ingest all accessible content.',
        defaultOpenSections: [RecipeSections.Filter],
    },
    [AZURE]: {
        fields: [
            AZURE_CLIENT_ID,
            AZURE_TENANT_ID,
            AZURE_CLIENT_SECRET,
            AZURE_REDIRECT_URL,
            AZURE_AUTHORITY_URL,
            AZURE_TOKEN_URL,
            AZURE_GRAPH_URL,
        ],
        filterFields: [GROUP_ALLOW, GROUP_DENY, USER_ALLOW, USER_DENY],
        advancedFields: [AZURE_INGEST_USERS, AZURE_INGEST_GROUPS, STATEFUL_INGESTION_ENABLED, SKIP_USERS_WITHOUT_GROUP],
    },
    [SAC]: {
        fields: [SAC_TENANT_URL, SAC_TOKEN_URL, SAC_CLIENT_ID, SAC_CLIENT_SECRET],
        filterFields: [
            FOLDER_ALLOW,
            FOLDER_DENY,
            RESOURCE_NAME_ALLOW,
            RESOURCE_NAME_DENY,
            RESOURCE_ID_ALLOW,
            RESOURCE_ID_DENY,
        ],
        advancedFields: [INGEST_STORIES, INGEST_APPLICATIONS, STATEFUL_INGESTION_ENABLED],
    },
    [GLUE]: {
        fields: [
            GLUE_AWS_REGION,
            GLUE_AWS_AUTHORIZATION_METHOD,
            GLUE_AWS_ACCESS_KEY_ID,
            GLUE_AWS_SECRET_ACCESS_KEY,
            GLUE_AWS_SESSION_TOKEN,
            GLUE_AWS_ROLE,
            GLUE_CATALOG_ID,
        ],
        filterFields: [DATABASE_ALLOW, DATABASE_DENY, TABLE_ALLOW, TABLE_DENY],
        advancedFields: [
            GLUE_PLATFORM_INSTANCE,
            ENV,
            GLUE_EXTRACT_OWNERS,
            GLUE_EXTRACT_TRANSFORMS,
            GLUE_EMIT_S3_LINEAGE,
            GLUE_INCLUDE_COLUMN_LINEAGE,
            GLUE_PROFILING_ENABLED,
            PROFILING_TABLE_LEVEL_ONLY,
            GLUE_REMOVE_STALE_METADATA_ENABLED,
        ],
        hasDynamicFields: true,
    },
    [ORACLE]: {
        fields: [
            ORACLE_HOST_PORT,
            ORACLE_USERNAME,
            ORACLE_PASSWORD,
            ORACLE_IDENTIFIER,
            ORACLE_DATABASE,
            ORACLE_SERVICE_NAME,
        ],
        filterFields: [SCHEMA_ALLOW, SCHEMA_DENY, TABLE_ALLOW, TABLE_DENY, VIEW_ALLOW, VIEW_DENY],
        advancedFields: [
            ORACLE_PLATFORM_INSTANCE,
            ENV,
            ORACLE_INCLUDE_TABLES,
            ORACLE_INCLUDE_VIEWS,
            ORACLE_INCLUDE_VIEW_LINEAGE,
            ORACLE_INCLUDE_VIEW_COLUMN_LINEAGE,
            ORACLE_PROFILING_ENABLED,
            PROFILING_TABLE_LEVEL_ONLY,
            ORACLE_EXTRACT_USAGE_HISTORY,
            ORACLE_CONVERT_URNS_TO_LOWERCASE,
            REMOVE_STALE_METADATA_ENABLED,
        ],
        hasDynamicFields: true,
    },
    [DREMIO]: {
        fields: [
            DREMIO_IS_DREMIO_CLOUD,
            DREMIO_DREMIO_CLOUD_REGION,
            DREMIO_DREMIO_CLOUD_PROJECT_ID,
            DREMIO_HOSTNAME,
            DREMIO_PORT,
            DREMIO_TLS,
            DREMIO_AUTHENTICATION_METHOD,
            DREMIO_USERNAME,
            DREMIO_PASSWORD,
        ],
        filterFields: [
            SCHEMA_ALLOW,
            SCHEMA_DENY,
            DATASET_ALLOW,
            DATASET_DENY,
            DREMIO_PROFILE_ALLOW,
            DREMIO_PROFILE_DENY,
        ],
        advancedFields: [
            DREMIO_PLATFORM_INSTANCE,
            ENV,
            DREMIO_INGEST_OWNER,
            DREMIO_INCLUDE_QUERY_LINEAGE,
            PROFILING_ENABLED,
            PROFILING_TABLE_LEVEL_ONLY,
            REMOVE_STALE_METADATA_ENABLED,
        ],
        hasDynamicFields: true,
    },
    [RDF]: {
        fields: [RDF_SOURCE],
        filterFields: [],
        advancedFields: [
            RDF_FORMAT,
            RDF_EXTENSIONS,
            RDF_RECURSIVE,
            RDF_ENVIRONMENT,
            RDF_DIALECT,
            RDF_PARENT_GLOSSARY_NODE,
        ],
        connectionSectionTooltip: 'Configure the RDF source location and basic settings.',
        advancedSectionTooltip: 'Advanced options for RDF format, file processing, and dialect selection.',
    },
};

const ALL_CONNECTORS_WITH_FORM = Object.keys(RECIPE_FIELDS);
export const CONNECTORS_WITH_FORM_INCLUDING_DYNAMIC_FIELDS = new Set(ALL_CONNECTORS_WITH_FORM);
export const CONNECTORS_WITH_FORM_NO_DYNAMIC_FIELDS = new Set(
    ALL_CONNECTORS_WITH_FORM.filter((sourceType) => !RECIPE_FIELDS[sourceType].hasDynamicFields),
);
