class Constant:
    """
    keys used in powerbi plugin
    """

    WEB_URL_BASE = "https://app.powerbi.com/groups"
    AUTHORIZATION = "Authorization"
    CORP_USER = "corpuser"
    CORP_USER_INFO = "corpUserInfo"
    CORP_USER_KEY = "corpUserKey"
    CHART_ID = "powerbi.linkedin.com/charts/{}"
    CONTAINER = "container"
    CHART = "chart"
    CHART_INFO = "chartInfo"
    CHART_KEY = "chartKey"
    REPORT_ID = "powerbi.linkedin.com/reports/{}"
    DASHBOARD_ID = "powerbi.linkedin.com/dashboards/{}"
    STATUS = "status"
    DASHBOARD = "dashboard"
    DASHBOARD_KEY = "dashboardKey"
    DASHBOARD_INFO = "dashboardInfo"
    SUBTYPES = "subTypes"
    OWNERSHIP = "ownership"
    BROWSERPATH = "browsePaths"
    DATAPLATFORM_INSTANCE = "dataPlatformInstance"
    DATASET = "dataset"
    DATASET_ID = "powerbi.linkedin.com/datasets/{}"
    DATASET_KEY = "datasetKey"
    DATASET_PROPERTIES = "datasetProperties"
    SCHEMA_METADATA = "schemaMetadata"


class APIEndpoints:
    POWERBI_BASE_URL = "https://api.powerbi.com/v1.0/myorg/groups"
    POWERBI_ADMIN_BASE_URL = "https://api.powerbi.com/v1.0/myorg/admin"
    POWERBI_AUTHORITY_URL = "https://login.microsoftonline.com/"
    POWERBI_SCOPE = "https://analysis.windows.net/powerbi/api/.default"
    WORKSPACE_MODIFIED_LIST = POWERBI_ADMIN_BASE_URL + "/workspaces/modified"
    SCAN_CREATE = POWERBI_ADMIN_BASE_URL + "/workspaces/getInfo"
    SCAN_GET = POWERBI_ADMIN_BASE_URL + "/workspaces/scanStatus/{SCAN_ID}"
    SCAN_RESULT_GET = POWERBI_ADMIN_BASE_URL + "/workspaces/scanResult/{SCAN_ID}"
