#!/usr/bin/env bash

: ${PARTITIONS:=1}
: ${REPLICATION_FACTOR:=1}

: ${KAFKA_PROPERTIES_SECURITY_PROTOCOL:=PLAINTEXT}

: ${DATAHUB_ANALYTICS_ENABLED:=true}

export KAFKA_HEAP_OPTS="-Xmx64M"

CONNECTION_PROPERTIES_PATH=/tmp/connection.properties

WORKERS=4
