entity_analyzer_config:
  settings:
    index:
      analysis:
        normalizer:
          keyword_normalizer:
            filter:
              - trim
              - lowercase
              - asciifolding
            type: custom
            char_filter: []
        analyzer:
          browse_path_v2_hierarchy:
            tokenizer: unit_separator_path_tokenizer
          unit_separator_pattern:
            tokenizer: unit_separator_pattern_tokenizer
        tokenizer:
          unit_separator_path_tokenizer:
            type: path_hierarchy
            delimiter: "␟"
          unit_separator_pattern_tokenizer:
            type: pattern
            pattern: "␟"
