# Notes:
#
# First match wins
#
# queryRegex = Java regex syntax
#
# functionScores - See the following for function score syntax
# https://www.elastic.co/guide/en/elasticsearch/reference/7.17/query-dsl-function-score-query.html

queryConfigurations:
  # Select */explore all
  # Attempt to rank active incidents at the top followed by enrichment factors
  - queryRegex: '[*]|'
    simpleQuery: false
    prefixMatchQuery: false
    exactMatchQuery: false
    functionScore:
      functions:
        - filter:
            term:
              hasActiveIncidents:
                value: true
          weight: 2.0
        - filter:
            term:
              hasDescription:
                value: true
          weight: 1.25
        - filter:
            term:
              hasOwners:
                value: true
          weight: 1.25
        - filter:
            term:
              hasDomain:
                value: true
          weight: 1.1
        - filter:
            term:
              hasGlossaryTerms:
                value: true
          weight: 1.1
        - filter:
            term:
              hasTags:
                value: true
          weight: 1.1
        - filter:
            term:
              hasRowCount:
                value: true
          weight: 1.05
        - filter:
            term:
              hasColumnCount:
                value: true
          weight: 1.05
        - filter:
            term:
              deprecated:
                value: true
          weight: 0.25
      score_mode: multiply
      boost_mode: replace

  # Criteria for exact-match only
  # Contains quotes then use exact match query
  - queryRegex: >-
      ^["'].+["']$
    simpleQuery: false
    prefixMatchQuery: true
    exactMatchQuery: true
    functionScore:
      functions:
        - filter:
            term:
              deprecated:
                value: true
          weight: 0.25
      score_mode: multiply
      boost_mode: multiply

  # default
  - queryRegex: .*
    simpleQuery: true
    prefixMatchQuery: true
    exactMatchQuery: true
    functionScore:
      functions:
        - filter:
            term:
              deprecated:
                value: true
          weight: 0.25
      score_mode: multiply
      boost_mode: multiply
