MATILLION_PLATFORM = "matillion"

# Container subtypes are now defined in datahub.ingestion.source.common.subtypes:
# - DatasetContainerSubTypes.MATILLION_PROJECT
# - DatasetContainerSubTypes.MATILLION_ENVIRONMENT

API_ENDPOINT_PROJECTS = "v1/projects"
API_ENDPOINT_ENVIRONMENTS = "v1/environments"
API_ENDPOINT_PIPELINES = "v1/pipelines"
API_ENDPOINT_PIPELINE_EXECUTIONS = "v1/pipelines/executions"
API_ENDPOINT_CONNECTIONS = "v1/connections"
API_ENDPOINT_AGENTS = "v1/agents"
API_ENDPOINT_SCHEDULES = "v1/schedules"
API_ENDPOINT_REPOSITORIES = "v1/repositories"
API_ENDPOINT_LINEAGE = "v1/data-lineage"
API_ENDPOINT_STREAMING_PIPELINES = "v1/streaming-pipelines"
API_ENDPOINT_CONSUMPTION = "v1/consumption"
API_ENDPOINT_AUDIT_EVENTS = "v1/audit-events"
API_ENDPOINT_CONNECTORS = "v1/connectors"

ENTITY_NAME_PROJECT = "project"
ENTITY_NAME_ENVIRONMENT = "environment"
ENTITY_NAME_PIPELINE = "pipeline"
ENTITY_NAME_PIPELINE_EXECUTION = "pipeline execution"
ENTITY_NAME_CONNECTION = "connection"
ENTITY_NAME_AGENT = "agent"
ENTITY_NAME_SCHEDULE = "schedule"
ENTITY_NAME_REPOSITORY = "repository"
ENTITY_NAME_STREAMING_PIPELINE = "streaming pipeline"
ENTITY_NAME_LINEAGE = "lineage data"
ENTITY_NAME_CONSUMPTION = "consumption data"
ENTITY_NAME_AUDIT_EVENT = "audit event"
ENTITY_NAME_CONNECTOR = "connector"

HTTP_METHOD_GET = "GET"
HTTP_PROTOCOL_HTTP = "http://"
HTTP_PROTOCOL_HTTPS = "https://"
HTTP_HEADER_AUTHORIZATION = "Authorization"
HTTP_HEADER_CONTENT_TYPE = "Content-Type"
HTTP_CONTENT_TYPE_JSON = "application/json"

HTTP_RETRY_MAX_ATTEMPTS = 3
HTTP_RETRY_BACKOFF_FACTOR = 1
HTTP_RETRY_STATUS_CODES = [429, 500, 502, 503, 504]
HTTP_RETRY_ALLOWED_METHODS = [HTTP_METHOD_GET]

API_PAGINATION_DEFAULT_SIZE = 25
API_PAGINATION_DEFAULT_PAGE = 0

API_RESPONSE_FIELD_CONTENT = "content"
API_RESPONSE_FIELD_TOTAL_ELEMENTS = "totalElements"
API_RESPONSE_FIELD_NUMBER = "number"
API_RESPONSE_FIELD_SIZE = "size"

MATILLION_EU1_URL = "https://eu1.api.matillion.com/dpc"
MATILLION_US1_URL = "https://us1.api.matillion.com/dpc"

DEFAULT_REQUEST_TIMEOUT_SEC = 30
MAX_REQUEST_TIMEOUT_WARNING_THRESHOLD = 300
