{
 "title": "DataHub Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Get",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Get QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_get_Count{}[1m])/60",
     "legendFormat": "Get QPS"
    },
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_get_failed_Count{}[1m])/60",
     "legendFormat": "Get Failure"
    },
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_batchGet_Count{}[1m])/60",
     "legendFormat": "BatchGet QPS"
    },
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_batchGet_failed_Count{}[1m])/60",
     "legendFormat": "BatchGet Failure"
    }
   ]
  },
  {
   "title": "Get Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_resources_entity_EntityResource_get_Mean{}",
     "legendFormat": "Get Avg"
    },
    {
     "expr": "metrics_com_linkedin_metadata_resources_entity_EntityResource_get_75thPercentile{}",
     "legendFormat": "Get P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_resources_entity_EntityResource_get_95thPercentile{}",
     "legendFormat": "Get P95"
    },
    {
     "expr": "metrics_com_linkedin_metadata_resources_entity_EntityResource_batchGet_Mean{}",
     "legendFormat": "BatchGet Avg"
    },
    {
     "expr": "metrics_com_linkedin_metadata_resources_entity_EntityResource_batchGet_75thPercentile{}",
     "legendFormat": "BatchGet P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_resources_entity_EntityResource_batchGet_95thPercentile{}",
     "legendFormat": "BatchGet P95"
    }
   ]
  },
  {
   "title": "Ingest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ingest QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_ingest_Count{}[1m])/60",
     "legendFormat": "Ingest Count"
    },
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_batchIngest_Count{}[1m])/60",
     "legendFormat": "BatchIngest Count"
    },
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_ingest_failed_Count[1m])/60",
     "legendFormat": "Ingest Failure"
    },
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_batchIngest_failed_Count[1m])/60",
     "legendFormat": "BatchIngest Failure"
    }
   ]
  },
  {
   "title": "Ingest Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 10 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_resources_entity_EntityResource_ingest_Mean{}",
     "legendFormat": "Avg"
    },
    {
     "expr": "metrics_com_linkedin_metadata_resources_entity_EntityResource_ingest_75thPercentile{}",
     "legendFormat": "P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_resources_entity_EntityResource_ingest_95thPercentile{}",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Ingest Steps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 10 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_entity_EntityService_ingestAspectsToLocalDB_Mean{}",
     "legendFormat": "Ingest To DB"
    },
    {
     "expr": "metrics_com_linkedin_metadata_entity_EntityService_produceMAE_Mean{}",
     "legendFormat": "Produce MAE"
    }
   ]
  },
  {
   "title": "MAE Process Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_maeProcess_Mean",
     "legendFormat": "Avg"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataAuditEventsProcessor_maeProcess_75thPercentile",
     "legendFormat": "P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataAuditEventsProcessor_maeProcess_95thPercentile",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Search",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Search QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_search_Count{}[1m])/60",
     "legendFormat": "QPS"
    },
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_search_failed_Count{}[1m])/60",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Search Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 27 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_resources_entity_EntityResource_search_Mean{}",
     "legendFormat": "Avg"
    },
    {
     "expr": "metrics_com_linkedin_metadata_resources_entity_EntityResource_search_75thPercentile{}",
     "legendFormat": "P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_resources_entity_EntityResource_search_95thPercentile{}",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Search Steps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 27 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_search_elasticsearch_query_ESSearchDAO_esSearch_Mean{}",
     "legendFormat": "ES Search"
    },
    {
     "expr": "metrics_com_linkedin_metadata_search_elasticsearch_query_ESSearchDAO_searchRequest_Mean{}",
     "legendFormat": "Request Builder"
    },
    {
     "expr": "metrics_com_linkedin_metadata_resources_entity_EntityResource_search_Mean{}",
     "legendFormat": "Total Search"
    }
   ]
  },
  {
   "title": "Browse",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Browse QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_browse_Count{}[1m])/60",
     "legendFormat": "QPS"
    },
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_entity_EntityResource_browse_failed_Count{}[1m])/60",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Browse Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 36 },
   "targets": [
    {
     "expr": "metrics_com_datahub_graphql_GraphQLController_browse_Mean{}",
     "legendFormat": "Avg"
    },
    {
     "expr": "metrics_com_datahub_graphql_GraphQLController_browse_75thPercentile{}",
     "legendFormat": "P75"
    },
    {
     "expr": "metrics_com_datahub_graphql_GraphQLController_browse_95thPercentile{}",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Browse Steps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 36 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_search_elasticsearch_query_ESBrowseDAO_esGroupSearch_Mean{}",
     "legendFormat": "ES Groups Query"
    },
    {
     "expr": "metrics_com_linkedin_metadata_search_elasticsearch_query_ESBrowseDAO_esEntitiesSearch_Mean{}",
     "legendFormat": "ES Entities Query"
    },
    {
     "expr": "metrics_com_datahub_graphql_GraphQLController_browse_Mean{}",
     "legendFormat": "Total Browse"
    }
   ]
  },
  {
   "title": "Graph",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Graph QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_lineage_Relationships_getLineage_Count{}[1m])/60",
     "legendFormat": "Relationships QPS"
    },
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_lineage_Lineage_get_Count{}[1m])/60",
     "legendFormat": "Lineage QPS"
    },
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_lineage_Relationships_getLineage_failed_Count{}[1m])/60",
     "legendFormat": "Relationships Failure"
    },
    {
     "expr": "increase(metrics_com_linkedin_metadata_resources_lineage_Lineage_get_failed_Count{}[1m])/60",
     "legendFormat": "Lineage Failure"
    }
   ]
  },
  {
   "title": "Graph Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 45 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_resources_lineage_Relationships_getLineage_Mean{}",
     "legendFormat": "Avg"
    },
    {
     "expr": "metrics_com_linkedin_metadata_resources_lineage_Relationships_getLineage_75thPercentile{}",
     "legendFormat": "P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_resources_lineage_Relationships_getLineage_95thPercentile{}",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Producer Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_producer_producer_topic_metrics_record_send_rate{})"
    }
   ]
  },
  {
   "title": "Consumer Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "sum by (client_id) (kafka_consumer_consumer_metrics_request_rate{})"
    }
   ]
  },
  {
   "title": "MetadataChangeEvent Topic Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeEventsProcessor_kafkaLag_Mean{}",
     "legendFormat": "Avg"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeEventsProcessor_kafkaLag_75thPercentile{}",
     "legendFormat": "P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeEventsProcessor_kafkaLag_95thPercentile{}",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "MetadataChangeProposal Topic Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeProposalsProcessor_kafkaLag_Mean{}",
     "legendFormat": "Avg"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeProposalsProcessor_kafkaLag_75thPercentile{}",
     "legendFormat": "P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeProposalsProcessor_kafkaLag_95thPercentile{}",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "MetadataAuditEvent Topic Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_kafkaLag_Mean{}",
     "legendFormat": "Avg"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_kafkaLag_75thPercentile{}",
     "legendFormat": "P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_kafkaLag_95thPercentile{}",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "MetadataChangeLog Topic Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_kafkaLag_Mean{}",
     "legendFormat": "Avg"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_kafkaLag_75thPercentile{}",
     "legendFormat": "P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_MetadataChangeLogProcessor_kafkaLag_95thPercentile{}",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "DataHubUsageEvent Topic Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "metrics_com_linkedin_metadata_kafka_DataHubUsageEventsProcessor_kafkaLag_Mean{}",
     "legendFormat": "Avg"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_DataHubUsageEventsProcessor_kafkaLag_75thPercentile{}",
     "legendFormat": "P75"
    },
    {
     "expr": "metrics_com_linkedin_metadata_kafka_DataHubUsageEventsProcessor_kafkaLag_95thPercentile{}",
     "legendFormat": "P95"
    }
   ]
  }
 ]
}