# flake8: noqa

# This file is autogenerated by /metadata-ingestion/scripts/avro_codegen.py
# Do not modify manually!

# fmt: off

import functools
import pathlib

def _load_schema(schema_name: str) -> str:
    return (pathlib.Path(__file__).parent / f"{schema_name}.avsc").read_text()

@functools.lru_cache(maxsize=None)
def getMetadataChangeEventSchema() -> str:
    return _load_schema("MetadataChangeEvent")

@functools.lru_cache(maxsize=None)
def getMetadataChangeProposalSchema() -> str:
    return _load_schema("MetadataChangeProposal")

@functools.lru_cache(maxsize=None)
def getUsageAggregationSchema() -> str:
    return _load_schema("UsageAggregation")

@functools.lru_cache(maxsize=None)
def getDatasetProfileSchema() -> str:
    return _load_schema("DatasetProfile")
# fmt: on
