INTER_CLUSTER_PENALTY_WEIGHT = 0.2
NUM_ANOMALY_PENALTY_WEIGHT = 0.2
ANOMALY_CONFIDENCE_PENALTY_WEIGHT = 0.2
CLUSTER_INDEX_PENALTY_WEIGHT = 0.1
TIME_SPAN_PENALTY_WEIGHT = 0.4
MISSING_DAYS_PENALTY_WEIGHT = 0.6
MISSING_DAYS_PENALTY_THRESHOLD = 0.2
BUFFER_RATIO = 0.1

IQR_MULTIPLICATION_FACTOR = 3

# Z-score constants
SKEWNESS_THRESHOLD = 0.5
P_VALUE_THRESHOLD = 0.5
DEVIATION_THRESHOLD = 1.8

# MAD constants
MAD_THRESHOLD = 1.5
# k = 1.5

# Autoencoder constants
STDEV_SCALE_FACTOR = 2.0
EPOCHS = 100

# Isolation Forest constants
N_ESTIMATORS = 100
MAX_SAMPLES = "auto"
ISOF_CONTAMINATION = 0.1

# LOF Constants
N_NEIGHBORS = 3
LOF_CONTAMINATION = "auto"
# 0.1

# OCSVM Constants
KERNEL = "rbf"
NU = 0.1

# DBSCAN Constants
