import datetime
import logging
from collections import Counter
from typing import Dict, List, Optional, Sequence, Tuple, Union

import numpy as np
import pandas as pd
from scipy.signal import find_peaks
from scipy.stats import gaussian_kde
from sklearn.neighbors import LocalOutlierFactor

from datahub_executor.common.monitor.inference.fixed_interval.fixed_interval_inference import (
    config,
)

logger = logging.getLogger(__name__)


def preprocess_data(
    timestamps: Sequence[Union[int, pd.Timestamp, datetime.datetime]],
    known_anomaly_timestamps: Sequence[int],
) -> pd.DataFrame:
    """
    This function performs the following tasks:
        - Convert timestamps to dataframe
        - Remove duplicates
        - Create diff feature from the ordered timestamps
        - Filter out intervals that end with known anomalies

    :param timestamps: List of integer/pd.Timestamp/datetime object
    :param known_anomaly_timestamps: List of known anomalous timestamps (in milliseconds)
    :return: pd.DataFrame, dataframe with timestamps and time differences (with anomalies filtered out)
    """
    # Convert timestamps to DataFrame
    if all(isinstance(n, int) for n in timestamps):
        ts = (
            pd.DataFrame(pd.to_datetime(timestamps, unit="ms"), columns=["ds"])
            .sort_values("ds")
            .drop_duplicates()
        )
    else:
        ts = pd.DataFrame(timestamps, columns=["ds"])
        ts["ds"] = pd.to_datetime(ts.ds)
        ts = ts.sort_values("ds").drop_duplicates().reset_index(drop=True)

    # Create time delta feature
    ts["time_delta"] = ts["ds"].diff().apply(lambda x: x.total_seconds() / 60)
    ts["date"] = ts.ds.dt.date

    # Filter out intervals that end with known anomalies
    if known_anomaly_timestamps and len(known_anomaly_timestamps) > 0:
        # Convert known anomalies to datetime
        known_anomalies_dt = pd.to_datetime(known_anomaly_timestamps, unit="ms")

        # Mask timestamps that are anomalies
        is_anomaly = ts["ds"].isin(known_anomalies_dt)

        # Set time_delta to NaN only where timestamp is an anomaly (i.e., filter interval ending here)
        ts.loc[is_anomaly, "time_delta"] = np.nan

        logger.info(
            f"Filtered out {len(known_anomaly_timestamps)} intervals that end with known anomalies"
        )

    return ts


def detect_anomaly_z_score(past_values: np.ndarray) -> Optional[List[bool]]:
    """
    This function determines the anomalous values in a given series of data using z_score statistics.
    :param past_values:
                        Type: numpy ndarray
    :return: list of boolean values, returns a boolean list of length of past_values with
    """
    try:
        is_anomaly: List[bool] = []
        # past_values = np.array(past_values)

        mean = np.mean(past_values)
        std_dev = np.std(past_values)
        lower_bound = mean - config.DEVIATION_THRESHOLD * std_dev
        upper_bound = mean + config.DEVIATION_THRESHOLD * std_dev
        for value in past_values:
            if lower_bound < value < upper_bound:
                is_anomaly.append(False)
            else:
                is_anomaly.append(True)
    except Exception as e:
        logger.exception(f"Could not detect anomaly due to {e}")
        return None
    return is_anomaly


def detect_anomaly_lof(past_values: np.ndarray) -> Optional[List[bool]]:
    """
    This function determines the anomalous values in a given series of data using local outlier
    factor.
    :param past_values:
                        Type: numpy ndarray
    :return: list of boolean values, returns a boolean list of length of past_values with
    """
    try:
        is_anomaly: List[bool] = []
        x = np.array(past_values).reshape(-1, 1)
        n_neighbors = config.N_NEIGHBORS
        contamination = config.LOF_CONTAMINATION

        lof = LocalOutlierFactor(
            n_neighbors=n_neighbors, contamination=contamination, novelty=True
        ).fit(x)

        predictions = lof.predict(x)
        for prediction in predictions:
            if prediction == -1:
                is_anomaly.append(True)
            else:
                is_anomaly.append(False)
    except Exception as e:
        logger.exception(f"Could not detect anomaly due to {e}")
        return None
    return is_anomaly


ANOMALY_METHODS = {
    "z_score": detect_anomaly_z_score,
    "lof": detect_anomaly_lof,
}


def predict_anomaly(
    data: np.ndarray,
    anomaly_detection_method: str = "auto",
    missing_days_penalty: Optional[float] = None,
) -> Tuple[Optional[List[bool]], float]:
    """
    This function predicts anomalies in the given data by comparing anomaly predictions
    generated by z_score and lof methods and labels the data where both methods agree.
    It returns the boolean anomaly labels for every data point with anomaly_confidence_penalty,
    which accounts for the number of disagreements between the two methods.

    :param data:
                Type: numpy array
                Description: Array of time differences
    :param anomaly_detection_method:
                Type: str
                Description:
    :param missing_days_penalty:
                Type: float
                Description: floating point value between 0 and 1,
                            Penalty corresponding to the number of missing days.
    :return:
    """
    is_anomaly = None
    try:
        if anomaly_detection_method == "auto":
            is_anomaly_z_score = detect_anomaly_z_score(data)
            is_anomaly_lof = detect_anomaly_lof(data)
            if is_anomaly_lof is not None and is_anomaly_z_score is not None:
                if (
                    missing_days_penalty is not None
                    and missing_days_penalty >= config.MISSING_DAYS_PENALTY_THRESHOLD
                ):
                    is_anomaly = is_anomaly_z_score
                else:
                    is_anomaly = [
                        x & y
                        for x, y in zip(
                            is_anomaly_lof, is_anomaly_z_score, strict=False
                        )
                    ]
                # is_anomaly = [x & y for x, y in zip(is_anomaly_lof, is_anomaly_z_score)]
                if sum(is_anomaly_lof) > 0 or sum(is_anomaly_z_score) > 0:
                    num_disagreements = sum(
                        [
                            x ^ y
                            for x, y in zip(
                                is_anomaly_z_score, is_anomaly_lof, strict=False
                            )
                        ]
                    )
                    num_union = sum(
                        [
                            x | y
                            for x, y in zip(
                                is_anomaly_z_score, is_anomaly_lof, strict=False
                            )
                        ]
                    )
                    anomaly_confidence_penalty = (num_disagreements / num_union) * (
                        np.log(num_union + 1) / np.log(len(data) + 1)
                    )
                else:
                    anomaly_confidence_penalty = 0
            else:
                raise Exception(
                    "Error in anomaly detection with lof and z score methods!!!"
                )
        elif anomaly_detection_method in ANOMALY_METHODS.keys():
            is_anomaly = ANOMALY_METHODS[anomaly_detection_method](data)
            anomaly_confidence_penalty = 0
        else:
            raise Exception("Invalid Anomaly Method argument!!!")

        anomaly_confidence_penalty = (
            config.ANOMALY_CONFIDENCE_PENALTY_WEIGHT * anomaly_confidence_penalty
        )
    except Exception as e:
        logger.exception(f"Could not predict anomaly due to {e}")
        return is_anomaly, -1.0
    return is_anomaly, anomaly_confidence_penalty


def find_most_common(numbers: List[int], preference: str = "maximum") -> Optional[int]:
    """
    A function to get the mode of the provided list of integers.
    In case of multiple modes, it returns the number which is largest.
    :param numbers:
            Type: list of integers
    :param preference:
            Type: string ('maximum' or 'most_recent')
            Description: In case of multimodal input series of numbers,
                        this field selects the criteria of choosing the mode
                        the function selects the mode which is larger in terms
                        of magnitude if preference is set as 'maximum' and
                        selects the mode which has the highest index in the
                        list if set as 'most_recent'.
    :return: int, most common number in the list.
    """
    try:
        count = Counter(numbers)
        most_common = count.most_common()
        max_count = most_common[0][1]
        final_most_common_value = most_common[0][0]
        if preference == "most_recent":
            numbers.reverse()
            index_of_final_most_common_value = numbers.index(final_most_common_value)
            for i in range(1, len(most_common)):
                index_of_next_most_common_value = numbers.index(most_common[i][0])
                if (
                    most_common[i][1] == max_count
                    and index_of_next_most_common_value
                    < index_of_final_most_common_value
                ):
                    final_most_common_value = most_common[i][0]
                elif most_common[i][1] < max_count:
                    break
        else:
            final_most_common_value = most_common[0][0]
            for i in range(1, len(most_common)):
                if (
                    most_common[i][1] == max_count
                    and most_common[i][0] > final_most_common_value
                ):
                    final_most_common_value = most_common[i][0]
                elif most_common[i][1] < max_count:
                    break
    except Exception as e:
        logger.exception(f"Failed to get most common number due to {e}")
        return None
    return final_most_common_value


def get_missing_days_penalty(
    datewise_diff_counts: np.ndarray, max_weight: float = 1.0
) -> float:
    if len(datewise_diff_counts) == 0:
        return 0
    datewise_diff_counts = datewise_diff_counts[~np.isnan(datewise_diff_counts)]
    mode = find_most_common(list(datewise_diff_counts))
    nunique_penalty = (len(np.unique(datewise_diff_counts)) - 1) / len(
        datewise_diff_counts
    )
    unique_values_length_penalty = len(
        datewise_diff_counts[datewise_diff_counts != mode]
    ) / len(datewise_diff_counts)
    combined_penalty = max_weight * (nunique_penalty + unique_values_length_penalty) / 2
    return combined_penalty


def get_time_span_penalty(time_span: int, max_weight: float = 0.4) -> Optional[float]:
    """
    Generates a penalty based on the time span of data available.
    :param time_span:
                Type: int
                Description: difference between the end and start
                            date of event records
    :param max_weight:
                Type: float
                Description: scaling factor  for the penalty, ranging from 0 to 1.
    :return: float, ranging from 0 to max_weight
    """
    try:
        if time_span < 14:
            num_missing_days = 14 - time_span
            penalty = max_weight * (num_missing_days / 14)
        else:
            penalty = 0
    except Exception as e:
        logger.exception(f"Failed to get time span penalty due to {e}")
        return None
    return penalty


def get_cluster_penalties(
    data: np.ndarray, recent_data: np.ndarray, max_normal: float
) -> Tuple[float, float, float]:
    if len(data) == 0:
        logger.warning("No data provided to get_cluster_penalties")
        return 0.0, 0.0, max_normal

    kde = gaussian_kde(data)
    num_steps = max(1000, int(max(data)))
    linear_spaced_vector = np.linspace(np.min(data), np.max(data), num_steps)
    density = kde(linear_spaced_vector)
    peaks, _ = find_peaks(density)

    if len(peaks) == 0:
        logger.warning("No peaks found in KDE, using single cluster")
        # If no peaks found, treat all data as one cluster
        inter_cluster_penalty = config.INTER_CLUSTER_PENALTY_WEIGHT * (
            np.std(data) / (max(data) - min(data)) if len(data) > 1 else 1.0
        )
        cluster_index_penalty = 0.0
        return inter_cluster_penalty, cluster_index_penalty, max_normal

    centroids = linear_spaced_vector[peaks]

    # Label data and create clusters

    labels = np.argmin(np.abs(data[:, np.newaxis] - centroids), axis=1)
    unique_labels = np.unique(labels)
    clusters: Dict[str, list] = {}
    for label in unique_labels:
        clusters[label] = data[labels == label]  # type: ignore

    # Identify the max normal cluster

    max_normal_cluster = "none"
    for key, value in clusters.items():
        if max_normal in value:
            max_normal_cluster = key

    if max_normal_cluster == "none":
        raise Exception("Could not determine the 'max normal cluster'!!!")

    # Calculate Inter Cluster Penalty:

    if len(clusters[max_normal_cluster]) == 1:
        inter_cluster_penalty = config.INTER_CLUSTER_PENALTY_WEIGHT
        max_normal = max(np.delete(recent_data, np.where(recent_data == max_normal)))
        max_normal_cluster = str(int(max_normal_cluster) - 1)
    else:
        inter_cluster_penalty = config.INTER_CLUSTER_PENALTY_WEIGHT * (
            np.std(clusters[max_normal_cluster])
            / (max(clusters[max_normal_cluster]) - min(clusters[max_normal_cluster]))
        )

    # Calculate Cluster Index Penalty:

    cluster_index_penalty = config.CLUSTER_INDEX_PENALTY_WEIGHT * (
        1 - (float(max_normal_cluster) + 1) / len(clusters)
    )
    return inter_cluster_penalty, cluster_index_penalty, max_normal
