import json

from locust import HttpUser, constant, task
from threading import Lock, Thread
from random import randint

lock = Lock()


class SearchUser(HttpUser):
    wait_time = constant(1)

    @task
    def search(self):
        query = "breadth" + str(randint(0, 100))
        headers = {"Authorization": "Bearer YOUR_TOKEN_HERE"}
        self.client.request(
            method="POST",
            name=query,
            url="/api/graphql",
            headers=headers,
            data=json.dumps({
                "operationName": "getSearchResultsForMultiple",
                "variables": {
                    "input": {
                        "types": [],
                        "query": query,
                        "start": 0,
                        "count": 10,
                        "filters": [],
                        "orFilters": []
                    }
                },
                "query": "query getSearchResultsForMultiple($input: SearchAcrossEntitiesInput!) {\n  "
                         "searchAcrossEntities(input: $input) {\n    ...searchResults\n    __typename\n  "
                         "}\n}\n\nfragment searchResults on SearchResults {\n  start\n  count\n  total\n  "
                         "searchResults {\n    entity {\n      ...searchResultFields\n      __typename\n    }\n    "
                         "matchedFields {\n      name\n      value\n      __typename\n    }\n    insights {\n      "
                         "text\n      icon\n      __typename\n    }\n    __typename\n  }\n  facets {\n    "
                         "...facetFields\n    __typename\n  }\n  __typename\n}\n\nfragment searchResultFields on "
                         "Entity {\n  urn\n  type\n  ... on Dataset {\n    name\n    origin\n    uri\n    platform {"
                         "\n      ...platformFields\n      __typename\n    }\n    dataPlatformInstance {\n      "
                         "...dataPlatformInstanceFields\n      __typename\n    }\n    editableProperties {\n      "
                         "description\n      __typename\n    }\n    platformNativeType\n    properties {\n      "
                         "name\n      description\n      qualifiedName\n      customProperties {\n        key\n       "
                         " value\n        __typename\n      }\n      externalUrl\n      __typename\n    }\n    "
                         "ownership {\n      ...ownershipFields\n      __typename\n    }\n    globalTags {\n      "
                         "...globalTagsFields\n      __typename\n    }\n    glossaryTerms {\n      ...glossaryTerms\n "
                         "     __typename\n    }\n    subTypes {\n      typeNames\n      __typename\n    }\n    "
                         "domain {\n      ...entityDomain\n      __typename\n    }\n    parentContainers {\n      "
                         "...parentContainersFields\n      __typename\n    }\n    deprecation {\n      "
                         "...deprecationFields\n      __typename\n    }\n    siblings {\n      isPrimary\n      "
                         "siblings {\n        urn\n        type\n        ... on Dataset {\n          platform {\n     "
                         "       ...platformFields\n            __typename\n          }\n          name\n          "
                         "properties {\n            name\n            description\n            qualifiedName\n        "
                         "    externalUrl\n            __typename\n          }\n          __typename\n        }\n     "
                         "   __typename\n      }\n      __typename\n    }\n    lastProfile: datasetProfiles(limit: 1) "
                         "{\n      rowCount\n      timestampMillis\n      __typename\n    }\n    lastOperation: "
                         "operations(limit: 1) {\n      lastUpdatedTimestamp\n      timestampMillis\n      "
                         "__typename\n    }\n    statsSummary {\n      queryCountLast30Days\n      "
                         "queryCountPercentileLast30Days\n      queryCountRankLast30Days\n      "
                         "uniqueUserCountLast30Days\n      uniqueUserPercentileLast30Days\n      "
                         "uniqueUserRankLast30Days\n      topUsersLast30Days {\n        urn\n        type\n        "
                         "username\n        properties {\n          displayName\n          firstName\n          "
                         "lastName\n          fullName\n          __typename\n        }\n        editableProperties {"
                         "\n          displayName\n          pictureLink\n          __typename\n        }\n        "
                         "__typename\n      }\n      __typename\n    }\n    __typename\n  }\n  ... on CorpUser {\n    "
                         "username\n    properties {\n      active\n      displayName\n      title\n      firstName\n "
                         "     lastName\n      fullName\n      email\n      __typename\n    }\n    info {\n      "
                         "active\n      displayName\n      title\n      firstName\n      lastName\n      fullName\n   "
                         "   email\n      __typename\n    }\n    editableProperties {\n      displayName\n      "
                         "title\n      pictureLink\n      __typename\n    }\n    __typename\n  }\n  ... on CorpGroup "
                         "{\n    name\n    info {\n      displayName\n      description\n      __typename\n    }\n    "
                         "memberCount: relationships(\n      input: {types: [\"IsMemberOfGroup\", "
                         "\"IsMemberOfNativeGroup\"], direction: INCOMING, start: 0, count: 1}\n    ) {\n      "
                         "total\n      __typename\n    }\n    __typename\n  }\n  ... on Dashboard {\n    "
                         "dashboardId\n    properties {\n      name\n      description\n      externalUrl\n      "
                         "access\n      lastModified {\n        time\n        __typename\n      }\n      __typename\n "
                         "   }\n    ownership {\n      ...ownershipFields\n      __typename\n    }\n    globalTags {"
                         "\n      ...globalTagsFields\n      __typename\n    }\n    glossaryTerms {\n      "
                         "...glossaryTerms\n      __typename\n    }\n    editableProperties {\n      description\n    "
                         "  __typename\n    }\n    platform {\n      ...platformFields\n      __typename\n    }\n    "
                         "dataPlatformInstance {\n      ...dataPlatformInstanceFields\n      __typename\n    }\n    "
                         "domain {\n      ...entityDomain\n      __typename\n    }\n    deprecation {\n      "
                         "...deprecationFields\n      __typename\n    }\n    parentContainers {\n      "
                         "...parentContainersFields\n      __typename\n    }\n    statsSummary {\n      viewCount\n   "
                         "   viewCountLast30Days\n      viewCountPercentileLast30Days\n      "
                         "uniqueUserCountLast30Days\n      uniqueUserPercentileLast30Days\n      "
                         "uniqueUserRankLast30Days\n      topUsersLast30Days {\n        urn\n        type\n        "
                         "username\n        properties {\n          displayName\n          firstName\n          "
                         "lastName\n          fullName\n          __typename\n        }\n        editableProperties {"
                         "\n          displayName\n          pictureLink\n          __typename\n        }\n        "
                         "__typename\n      }\n      __typename\n    }\n    subTypes {\n      typeNames\n      "
                         "__typename\n    }\n    __typename\n  }\n  ... on Chart {\n    chartId\n    properties {\n   "
                         "   name\n      description\n      externalUrl\n      type\n      access\n      lastModified "
                         "{\n        time\n        __typename\n      }\n      created {\n        time\n        "
                         "__typename\n      }\n      __typename\n    }\n    ownership {\n      ...ownershipFields\n   "
                         "   __typename\n    }\n    globalTags {\n      ...globalTagsFields\n      __typename\n    "
                         "}\n    glossaryTerms {\n      ...glossaryTerms\n      __typename\n    }\n    "
                         "editableProperties {\n      description\n      __typename\n    }\n    platform {\n      "
                         "...platformFields\n      __typename\n    }\n    dataPlatformInstance {\n      "
                         "...dataPlatformInstanceFields\n      __typename\n    }\n    domain {\n      "
                         "...entityDomain\n      __typename\n    }\n    deprecation {\n      ...deprecationFields\n   "
                         "   __typename\n    }\n    parentContainers {\n      ...parentContainersFields\n      "
                         "__typename\n    }\n    statsSummary {\n      viewCount\n      viewCountLast30Days\n      "
                         "viewCountPercentileLast30Days\n      uniqueUserCountLast30Days\n      "
                         "uniqueUserPercentileLast30Days\n      topUsersLast30Days {\n        urn\n        type\n     "
                         "   username\n        properties {\n          displayName\n          firstName\n          "
                         "lastName\n          fullName\n          __typename\n        }\n        editableProperties {"
                         "\n          displayName\n          pictureLink\n          __typename\n        }\n        "
                         "__typename\n      }\n      __typename\n    }\n    __typename\n  }\n  ... on DataFlow {\n    "
                         "flowId\n    cluster\n    properties {\n      name\n      description\n      project\n      "
                         "externalUrl\n      __typename\n    }\n    ownership {\n      ...ownershipFields\n      "
                         "__typename\n    }\n    globalTags {\n      ...globalTagsFields\n      __typename\n    }\n   "
                         " glossaryTerms {\n      ...glossaryTerms\n      __typename\n    }\n    editableProperties {"
                         "\n      description\n      __typename\n    }\n    platform {\n      ...platformFields\n     "
                         " __typename\n    }\n    dataPlatformInstance {\n      ...dataPlatformInstanceFields\n      "
                         "__typename\n    }\n    domain {\n      ...entityDomain\n      __typename\n    }\n    "
                         "deprecation {\n      ...deprecationFields\n      __typename\n    }\n    childJobs: "
                         "relationships(\n      input: {types: [\"IsPartOf\"], direction: INCOMING, start: 0, "
                         "count: 100}\n    ) {\n      total\n      __typename\n    }\n    __typename\n  }\n  ... on "
                         "DataJob {\n    dataFlow {\n      ...nonRecursiveDataFlowFields\n      __typename\n    }\n   "
                         " jobId\n    ownership {\n      ...ownershipFields\n      __typename\n    }\n    properties "
                         "{\n      name\n      description\n      externalUrl\n      __typename\n    }\n    "
                         "globalTags {\n      ...globalTagsFields\n      __typename\n    }\n    glossaryTerms {\n     "
                         " ...glossaryTerms\n      __typename\n    }\n    editableProperties {\n      description\n   "
                         "   __typename\n    }\n    domain {\n      ...entityDomain\n      __typename\n    }\n    "
                         "deprecation {\n      ...deprecationFields\n      __typename\n    }\n    "
                         "dataPlatformInstance {\n      ...dataPlatformInstanceFields\n      __typename\n    }\n    "
                         "lastRun: runs(start: 0, count: 1) {\n      count\n      start\n      total\n      runs {\n  "
                         "      urn\n        type\n        created {\n          time\n          actor\n          "
                         "__typename\n        }\n        __typename\n      }\n      __typename\n    }\n    "
                         "__typename\n  }\n  ... on GlossaryTerm {\n    name\n    hierarchicalName\n    properties {"
                         "\n      name\n      description\n      termSource\n      sourceRef\n      sourceUrl\n      "
                         "rawSchema\n      customProperties {\n        key\n        value\n        __typename\n      "
                         "}\n      __typename\n    }\n    deprecation {\n      ...deprecationFields\n      "
                         "__typename\n    }\n    parentNodes {\n      ...parentNodesFields\n      __typename\n    }\n "
                         "   domain {\n      ...entityDomain\n      __typename\n    }\n    __typename\n  }\n  ... on "
                         "GlossaryNode {\n    ...glossaryNode\n    parentNodes {\n      ...parentNodesFields\n      "
                         "__typename\n    }\n    __typename\n  }\n  ... on Domain {\n    properties {\n      name\n   "
                         "   description\n      __typename\n    }\n    ownership {\n      ...ownershipFields\n      "
                         "__typename\n    }\n    __typename\n  }\n  ... on Container {\n    properties {\n      "
                         "name\n      description\n      externalUrl\n      __typename\n    }\n    platform {\n      "
                         "...platformFields\n      __typename\n    }\n    dataPlatformInstance {\n      "
                         "...dataPlatformInstanceFields\n      __typename\n    }\n    editableProperties {\n      "
                         "description\n      __typename\n    }\n    ownership {\n      ...ownershipFields\n      "
                         "__typename\n    }\n    tags {\n      ...globalTagsFields\n      __typename\n    }\n    "
                         "glossaryTerms {\n      ...glossaryTerms\n      __typename\n    }\n    subTypes {\n      "
                         "typeNames\n      __typename\n    }\n    entities(input: {}) {\n      total\n      "
                         "__typename\n    }\n    deprecation {\n      ...deprecationFields\n      __typename\n    }\n "
                         "   parentContainers {\n      ...parentContainersFields\n      __typename\n    }\n    "
                         "__typename\n  }\n  ... on MLFeatureTable {\n    name\n    description\n    "
                         "featureTableProperties {\n      description\n      mlFeatures {\n        urn\n        "
                         "__typename\n      }\n      mlPrimaryKeys {\n        urn\n        __typename\n      }\n      "
                         "__typename\n    }\n    ownership {\n      ...ownershipFields\n      __typename\n    }\n    "
                         "platform {\n      ...platformFields\n      __typename\n    }\n    deprecation {\n      "
                         "...deprecationFields\n      __typename\n    }\n    dataPlatformInstance {\n      "
                         "...dataPlatformInstanceFields\n      __typename\n    }\n    __typename\n  }\n  ... on "
                         "MLFeature {\n    ...nonRecursiveMLFeature\n    __typename\n  }\n  ... on MLPrimaryKey {\n   "
                         " ...nonRecursiveMLPrimaryKey\n    __typename\n  }\n  ... on MLModel {\n    name\n    "
                         "description\n    origin\n    ownership {\n      ...ownershipFields\n      __typename\n    "
                         "}\n    platform {\n      ...platformFields\n      __typename\n    }\n    deprecation {\n    "
                         "  ...deprecationFields\n      __typename\n    }\n    dataPlatformInstance {\n      "
                         "...dataPlatformInstanceFields\n      __typename\n    }\n    __typename\n  }\n  ... on "
                         "MLModelGroup {\n    name\n    origin\n    description\n    ownership {\n      "
                         "...ownershipFields\n      __typename\n    }\n    platform {\n      ...platformFields\n      "
                         "__typename\n    }\n    deprecation {\n      ...deprecationFields\n      __typename\n    }\n "
                         "   dataPlatformInstance {\n      ...dataPlatformInstanceFields\n      __typename\n    }\n   "
                         " __typename\n  }\n  ... on Tag {\n    name\n    properties {\n      name\n      "
                         "__typename\n    }\n    description\n    __typename\n  }\n  ... on DataPlatform {\n    "
                         "...nonConflictingPlatformFields\n    __typename\n  }\n  __typename\n}\n\nfragment "
                         "platformFields on DataPlatform {\n  urn\n  type\n  lastIngested\n  name\n  properties {\n   "
                         " type\n    displayName\n    datasetNameDelimiter\n    logoUrl\n    __typename\n  }\n  "
                         "displayName\n  info {\n    type\n    displayName\n    datasetNameDelimiter\n    logoUrl\n   "
                         " __typename\n  }\n  __typename\n}\n\nfragment dataPlatformInstanceFields on "
                         "DataPlatformInstance {\n  urn\n  type\n  platform {\n    ...platformFields\n    "
                         "__typename\n  }\n  instanceId\n  __typename\n}\n\nfragment ownershipFields on Ownership {\n "
                         " owners {\n    owner {\n      ... on CorpUser {\n        urn\n        type\n        "
                         "username\n        info {\n          active\n          displayName\n          title\n        "
                         "  email\n          firstName\n          lastName\n          fullName\n          "
                         "__typename\n        }\n        properties {\n          active\n          displayName\n      "
                         "    title\n          email\n          firstName\n          lastName\n          fullName\n   "
                         "       __typename\n        }\n        editableProperties {\n          displayName\n         "
                         " title\n          pictureLink\n          email\n          __typename\n        }\n        "
                         "__typename\n      }\n      ... on CorpGroup {\n        urn\n        type\n        name\n    "
                         "    properties {\n          displayName\n          email\n          __typename\n        }\n "
                         "       info {\n          displayName\n          email\n          admins {\n            "
                         "urn\n            username\n            info {\n              active\n              "
                         "displayName\n              title\n              email\n              firstName\n            "
                         "  lastName\n              fullName\n              __typename\n            }\n            "
                         "editableInfo {\n              pictureLink\n              teams\n              skills\n      "
                         "        __typename\n            }\n            __typename\n          }\n          members {"
                         "\n            urn\n            username\n            info {\n              active\n         "
                         "     displayName\n              title\n              email\n              firstName\n       "
                         "       lastName\n              fullName\n              __typename\n            }\n          "
                         "  editableInfo {\n              pictureLink\n              teams\n              skills\n    "
                         "          __typename\n            }\n            __typename\n          }\n          "
                         "groups\n          __typename\n        }\n        __typename\n      }\n      __typename\n    "
                         "}\n    type\n    associatedUrn\n    __typename\n  }\n  lastModified {\n    time\n    "
                         "__typename\n  }\n  __typename\n}\n\nfragment globalTagsFields on GlobalTags {\n  tags {\n   "
                         " tag {\n      urn\n      type\n      name\n      description\n      properties {\n        "
                         "colorHex\n        __typename\n      }\n      __typename\n    }\n    associatedUrn\n    "
                         "__typename\n  }\n  __typename\n}\n\nfragment glossaryTerms on GlossaryTerms {\n  terms {\n  "
                         "  term {\n      ...glossaryTerm\n      __typename\n    }\n    actor {\n      urn\n      "
                         "__typename\n    }\n    associatedUrn\n    __typename\n  }\n  __typename\n}\n\nfragment "
                         "glossaryTerm on GlossaryTerm {\n  urn\n  name\n  type\n  hierarchicalName\n  properties {\n "
                         "   name\n    description\n    definition\n    termSource\n    customProperties {\n      "
                         "key\n      value\n      __typename\n    }\n    __typename\n  }\n  ownership {\n    "
                         "...ownershipFields\n    __typename\n  }\n  parentNodes {\n    ...parentNodesFields\n    "
                         "__typename\n  }\n  __typename\n}\n\nfragment parentNodesFields on ParentNodesResult {\n  "
                         "count\n  nodes {\n    urn\n    type\n    properties {\n      name\n      __typename\n    "
                         "}\n    __typename\n  }\n  __typename\n}\n\nfragment entityDomain on DomainAssociation {\n  "
                         "domain {\n    urn\n    type\n    properties {\n      name\n      description\n      "
                         "__typename\n    }\n    __typename\n  }\n  associatedUrn\n  __typename\n}\n\nfragment "
                         "parentContainersFields on ParentContainersResult {\n  count\n  containers {\n    "
                         "...entityContainer\n    __typename\n  }\n  __typename\n}\n\nfragment entityContainer on "
                         "Container {\n  urn\n  platform {\n    ...platformFields\n    __typename\n  }\n  properties "
                         "{\n    name\n    __typename\n  }\n  subTypes {\n    typeNames\n    __typename\n  }\n  "
                         "deprecation {\n    ...deprecationFields\n    __typename\n  }\n  __typename\n}\n\nfragment "
                         "deprecationFields on Deprecation {\n  actor\n  deprecated\n  note\n  decommissionTime\n  "
                         "__typename\n}\n\nfragment nonRecursiveDataFlowFields on DataFlow {\n  urn\n  type\n  "
                         "orchestrator\n  flowId\n  cluster\n  properties {\n    name\n    description\n    project\n "
                         "   externalUrl\n    customProperties {\n      key\n      value\n      __typename\n    }\n   "
                         " __typename\n  }\n  editableProperties {\n    description\n    __typename\n  }\n  ownership "
                         "{\n    ...ownershipFields\n    __typename\n  }\n  platform {\n    ...platformFields\n    "
                         "__typename\n  }\n  domain {\n    ...entityDomain\n    __typename\n  }\n  deprecation {\n    "
                         "...deprecationFields\n    __typename\n  }\n  __typename\n}\n\nfragment glossaryNode on "
                         "GlossaryNode {\n  urn\n  type\n  properties {\n    name\n    __typename\n  }\n  children: "
                         "relationships(\n    input: {types: [\"IsPartOf\"], direction: INCOMING, start: 0, "
                         "count: 10000}\n  ) {\n    total\n    __typename\n  }\n  __typename\n}\n\nfragment "
                         "nonRecursiveMLFeature on MLFeature {\n  urn\n  type\n  lastIngested\n  name\n  "
                         "featureNamespace\n  description\n  dataType\n  properties {\n    description\n    "
                         "dataType\n    version {\n      versionTag\n      __typename\n    }\n    sources {\n      "
                         "urn\n      name\n      type\n      origin\n      description\n      uri\n      platform {\n "
                         "       ...platformFields\n        __typename\n      }\n      platformNativeType\n      "
                         "__typename\n    }\n    __typename\n  }\n  ownership {\n    ...ownershipFields\n    "
                         "__typename\n  }\n  institutionalMemory {\n    ...institutionalMemoryFields\n    "
                         "__typename\n  }\n  status {\n    removed\n    __typename\n  }\n  glossaryTerms {\n    "
                         "...glossaryTerms\n    __typename\n  }\n  domain {\n    ...entityDomain\n    __typename\n  "
                         "}\n  tags {\n    ...globalTagsFields\n    __typename\n  }\n  editableProperties {\n    "
                         "description\n    __typename\n  }\n  deprecation {\n    ...deprecationFields\n    "
                         "__typename\n  }\n  dataPlatformInstance {\n    ...dataPlatformInstanceFields\n    "
                         "__typename\n  }\n  featureTables: relationships(\n    input: {types: [\"Contains\"], "
                         "direction: INCOMING, start: 0, count: 100}\n  ) {\n    relationships {\n      type\n      "
                         "entity {\n        ... on MLFeatureTable {\n          platform {\n            "
                         "...platformFields\n            __typename\n          }\n          __typename\n        }\n   "
                         "     __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  "
                         "__typename\n}\n\nfragment institutionalMemoryFields on InstitutionalMemory {\n  elements {"
                         "\n    url\n    author {\n      urn\n      username\n      __typename\n    }\n    "
                         "description\n    created {\n      actor\n      time\n      __typename\n    }\n    "
                         "__typename\n  }\n  __typename\n}\n\nfragment nonRecursiveMLPrimaryKey on MLPrimaryKey {\n  "
                         "urn\n  type\n  lastIngested\n  name\n  featureNamespace\n  description\n  dataType\n  "
                         "properties {\n    description\n    dataType\n    version {\n      versionTag\n      "
                         "__typename\n    }\n    sources {\n      urn\n      name\n      type\n      origin\n      "
                         "description\n      uri\n      platform {\n        ...platformFields\n        __typename\n   "
                         "   }\n      platformNativeType\n      __typename\n    }\n    __typename\n  }\n  ownership {"
                         "\n    ...ownershipFields\n    __typename\n  }\n  institutionalMemory {\n    "
                         "...institutionalMemoryFields\n    __typename\n  }\n  status {\n    removed\n    "
                         "__typename\n  }\n  glossaryTerms {\n    ...glossaryTerms\n    __typename\n  }\n  domain {\n "
                         "   ...entityDomain\n    __typename\n  }\n  tags {\n    ...globalTagsFields\n    "
                         "__typename\n  }\n  editableProperties {\n    description\n    __typename\n  }\n  "
                         "deprecation {\n    ...deprecationFields\n    __typename\n  }\n  dataPlatformInstance {\n    "
                         "...dataPlatformInstanceFields\n    __typename\n  }\n  featureTables: relationships(\n    "
                         "input: {types: [\"KeyedBy\"], direction: INCOMING, start: 0, count: 100}\n  ) {\n    "
                         "relationships {\n      type\n      entity {\n        ... on MLFeatureTable {\n          "
                         "platform {\n            ...platformFields\n            __typename\n          }\n          "
                         "__typename\n        }\n        __typename\n      }\n      __typename\n    }\n    "
                         "__typename\n  }\n  __typename\n}\n\nfragment nonConflictingPlatformFields on DataPlatform {"
                         "\n  urn\n  type\n  name\n  properties {\n    displayName\n    datasetNameDelimiter\n    "
                         "logoUrl\n    __typename\n  }\n  displayName\n  info {\n    type\n    displayName\n    "
                         "datasetNameDelimiter\n    logoUrl\n    __typename\n  }\n  __typename\n}\n\nfragment "
                         "facetFields on FacetMetadata {\n  field\n  displayName\n  aggregations {\n    value\n    "
                         "count\n    entity {\n      urn\n      type\n      ... on Tag {\n        name\n        "
                         "properties {\n          colorHex\n          __typename\n        }\n        __typename\n     "
                         " }\n      ... on GlossaryTerm {\n        name\n        properties {\n          name\n       "
                         "   __typename\n        }\n        __typename\n      }\n      ... on DataPlatform {\n        "
                         "...platformFields\n        __typename\n      }\n      ... on DataPlatformInstance {\n       "
                         " ...dataPlatformInstanceFields\n        __typename\n      }\n      ... on Domain {\n        "
                         "properties {\n          name\n          __typename\n        }\n        __typename\n      "
                         "}\n      ... on Container {\n        platform {\n          ...platformFields\n          "
                         "__typename\n        }\n        properties {\n          name\n          __typename\n        "
                         "}\n        __typename\n      }\n      ... on CorpUser {\n        username\n        "
                         "properties {\n          displayName\n          fullName\n          __typename\n        }\n  "
                         "      editableProperties {\n          displayName\n          pictureLink\n          "
                         "__typename\n        }\n        __typename\n      }\n      ... on CorpGroup {\n        "
                         "name\n        properties {\n          displayName\n          __typename\n        }\n        "
                         "__typename\n      }\n      __typename\n    }\n    __typename\n  }\n  __typename\n}\n "
            }),
        )
