[mypy]
mypy_path = src:stubs
check_untyped_defs = True
plugins = pydantic.mypy

[pydantic-mypy]
# https://github.com/pydantic/pydantic/issues/11054 populate_by_name not recognized by mypy when set by a non literal
init_typed = True

[mypy-aws_msk_iam_sasl_signer.*]
ignore_missing_imports = True

[mypy-acryl.executor.*]
# acryl-executor package doesn't have type stubs
ignore_missing_imports = True

[mypy-prophet.*]
ignore_missing_imports = True

[mypy-sklearn.*]
ignore_missing_imports = True

[mypy-redshift_connector.*]
ignore_missing_imports = True

[mypy-databricks.*]
ignore_missing_imports = True

[mypy-kombu.*]
ignore_missing_imports = True

[mypy-boto3.*]
ignore_missing_imports = True

[mypy-botocore.*]
ignore_missing_imports = True

[mypy-apscheduler.*]
ignore_missing_imports = True

[mypy-datahub_actions.*]
ignore_missing_imports = True

[mypy-debugpy.*]
ignore_missing_imports = True

