/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * This file is unmodified from its original version developed by Acryl Data, Inc.,
 * and is now included as part of a repository maintained by the National Digital Twin Programme.
 * All support, maintenance and further development of this code is now the responsibility
 * of the National Digital Twin Programme.
 */

export const EXECUTION_REQUEST_STATUS_RUNNING = 'RUNNING';
export const EXECUTION_REQUEST_STATUS_SUCCESS = 'SUCCESS';
export const EXECUTION_REQUEST_STATUS_SUCCEEDED_WITH_WARNINGS = 'SUCCEEDED_WITH_WARNINGS';
export const EXECUTION_REQUEST_STATUS_WARNING = 'WARNING';
export const EXECUTION_REQUEST_STATUS_FAILURE = 'FAILURE';
export const EXECUTION_REQUEST_STATUS_CONNECTION_FAILURE = 'CONNECTION_FAILURE';
export const EXECUTION_REQUEST_STATUS_CANCELLED = 'CANCELLED';
export const EXECUTION_REQUEST_STATUS_ABORTED = 'ABORTED';
export const EXECUTION_REQUEST_STATUS_UP_FOR_RETRY = 'UP_FOR_RETRY';
export const EXECUTION_REQUEST_STATUS_ROLLING_BACK = 'ROLLING_BACK';
export const EXECUTION_REQUEST_STATUS_ROLLED_BACK = 'ROLLED_BACK';
export const EXECUTION_REQUEST_STATUS_ROLLBACK_FAILED = 'ROLLBACK_FAILED';
export const EXECUTION_REQUEST_STATUS_DUPLICATE = 'DUPLICATE';
export const EXECUTION_REQUEST_STATUS_PENDING = 'PENDING';
export const EXECUTION_REQUEST_STATUS_LOADING = 'LOADING';

export const EXECUTION_REQUEST_STATUS_ACTIVE = [
    EXECUTION_REQUEST_STATUS_RUNNING,
    EXECUTION_REQUEST_STATUS_ROLLING_BACK,
    EXECUTION_REQUEST_STATUS_PENDING,
    EXECUTION_REQUEST_STATUS_UP_FOR_RETRY,
    EXECUTION_REQUEST_STATUS_LOADING,
];
