/**
 * Curated list of Phosphor icon names for the domain icon picker.
 * These are decorative icons suited for labeling business domains,
 * data domains, teams, and organizational categories.
 */
export const DOMAIN_ICON_NAMES: string[] = [
    // People & Organizations
    'UserCircle',
    'User',
    'UserPlus',
    'Users',
    'UsersThree',
    'UserGear',

    // Business & Finance
    'Buildings',
    'Briefcase',
    'Bank',
    'Wallet',
    'CurrencyDollar',
    'CurrencyCircleDollar',
    'Money',
    'CreditCard',
    'Receipt',
    'Storefront',
    'ShoppingCart',
    'Bag',
    'Truck',
    'Package',
    'Warehouse',
    'Factory',
    'PiggyBank',
    'Coins',
    'HandCoins',
    'Scales',

    // Data & Analytics
    'ChartLine',
    'ChartBar',
    'ChartPie',
    'ChartLineUp',
    'ChartDonut',
    'TrendUp',
    'TrendDown',
    'Table',
    'Database',
    'Gauge',
    'Lightbulb',
    'Trophy',
    'SquaresFour',
    'Path',
    'Graph',

    // Technology & Engineering
    'Code',
    'Terminal',
    'Desktop',
    'Laptop',
    'DeviceMobile',
    'Cpu',
    'Cloud',
    'CloudCheck',
    'HardDrives',
    'GitBranch',
    'Plugs',
    'Gear',
    'GearSix',
    'Wrench',
    'Bug',
    'Robot',

    // Science & Education
    'Flask',
    'GraduationCap',
    'BookOpen',
    'Books',
    'Book',
    'Brain',
    'Microscope',
    'Atom',
    'Dna',

    // Healthcare
    'Hospital',
    'ShieldCheck',
    'FirstAid',
    'Heartbeat',
    'Pill',
    'Syringe',
    'Stethoscope',

    // Communication & Media
    'Envelope',
    'ChatCircle',
    'Megaphone',
    'Bell',
    'Phone',
    'Microphone',
    'Headset',
    'ShareNetwork',

    // Content & Creative
    'FileText',
    'Article',
    'Newspaper',
    'Camera',
    'Image',
    'MusicNote',
    'Palette',
    'PaintBrush',
    'FilmStrip',

    // Navigation & Location
    'House',
    'Compass',
    'MapPin',
    'GlobeSimple',
    'Globe',
    'NavigationArrow',

    // Nature & Environment
    'Leaf',
    'Tree',
    'Plant',
    'PawPrint',
    'Drop',
    'Mountains',

    // Security & Legal
    'Shield',
    'Lock',
    'LockOpen',
    'SealCheck',
    'Gavel',
    'ShieldWarning',

    // Files & Organization
    'Folder',
    'FolderOpen',
    'FolderStar',
    'FolderPlus',
    'Folders',
    'Archive',
    'Stack',
    'Tag',

    // Favorites & Status
    'Heart',
    'Star',
    'Flag',
    'BookmarkSimple',
    'PuzzlePiece',

    // Objects & Misc
    'Rocket',
    'Anchor',
    'Lightning',
    'Target',
    'Crosshair',
    'Funnel',
    'Handshake',
    'CalendarBlank',
    'Clock',
    'Eye',
    'WifiHigh',
    'Plug',
    'Car',
    'Airplane',
    'ForkKnife',
    'Barbell',
    'GameController',
    'DiceFive',
    'Confetti',
    'Medal',
    'HandHeart',
];
