# flake8: noqa
# fmt: off
# This file is autogenerated by /metadata-ingestion/scripts/avro_codegen.py
# Do not modify manually!
from .....schema_classes import DataFlowInfoClass
from .....schema_classes import DataJobInfoClass
from .....schema_classes import DataJobInputOutputClass


DataFlowInfo = DataFlowInfoClass
DataJobInfo = DataJobInfoClass
DataJobInputOutput = DataJobInputOutputClass
# fmt: on
