name: Notify Slack on New Docs

on:
  push:
    branches:
      - docs/slack-noti-ci
      # - master
    paths:
      - 'docs/**.md'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Detect new .md files
        id: check_docs
        run: |
          NEW_DOCS=$(git diff --name-status ${{ github.event.before }} ${{ github.sha }} | grep '^A' | grep '\.md$' | cut -f2-)
          echo "NEW_DOCS<<EOF" >> $GITHUB_ENV
          echo "$NEW_DOCS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Notify Slack
        if: env.NEW_DOCS != ''
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "*📘 New Docs Published on `${{ github.ref_name }}`!*\n\n${{ env.NEW_DOCS }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
