name: Delete stale branches
on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  remove-stale-branches:
    name: Remove Stale Branches
    runs-on: ubuntu-latest
    steps:
      - uses: fpicalausa/remove-stale-branches@v1.6.0
        with:
          exempt-protected-branches: true
          operations-per-run: 25
          days-before-branch-stale: 365
          ignore-unknown-authors: true
          default-recipient: anshbansal
          # (days when branch is noticed as stale)
          days-before-branch-delete: 0
          dry-run: false
