name: pypi-release acryl-datahub-cloud
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print ref for debugging
        run: echo "Current ref is ${{ github.ref }}"
  setup:
    if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, '-acryl')
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compute Tag
        id: tag
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          SHORT_SHA=$(git rev-parse --short "$GITHUB_SHA")
          TAG=$(echo ${GITHUB_REF} | sed -e 's,refs/tags/v,,g')
          echo "tag=$TAG" >> $GITHUB_OUTPUT
  push_to_pypi:
    name: Build and push python package to PyPI
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine build
      - name: Install dependencies
        run: ./metadata-ingestion/scripts/install_deps.sh
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          cd metadata-ingestion-modules/acryl-cloud
          RELEASE_VERSION="${{ needs.setup.outputs.tag }}" RELEASE_SKIP_TEST=1 ./scripts/release.sh
