name: Quickstart Regression Test
description: Test that quickstart continues to work with already released versions
on:
  workflow_dispatch:
  schedule:
    - cron: "5 0 * * *" # Run at 5AM every day

jobs:
  test-quickstart-regression:
    name: Quickstart regression tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO: once more supported versions are aded, this should become list last n versions
        datahub_version: ["v1.0.0", "v1.1.0", "head"]
      fail-fast: false
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: install datahub cli
        run: |
          pip install acryl-datahub

      - name: bring up datahub using old cli
        run: |
          datahub docker quickstart --version ${{ matrix.datahub_version }}
          datahub docker check
          datahub docker ingest-sample-data
          datahub docker check

      - name: Backup, nuke and restart and restore
        run: |
          echo "Running backup"
          datahub docker quickstart --backup
          echo "Running nuke"
          datahub docker nuke
          datahub docker quickstart
          echo "Running restore"
          echo "y" | datahub docker quickstart --restore
          datahub docker check
