package com.linkedin.metadata.aspect.patch.builder;

import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertNotNull;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.linkedin.common.OwnershipType;
import com.linkedin.common.urn.GlossaryTermUrn;
import com.linkedin.common.urn.TagUrn;
import com.linkedin.common.urn.Urn;
import com.linkedin.mxe.MetadataChangeProposal;
import java.io.InputStream;
import java.util.List;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

/**
 * Verifies that the Java patch builders produce the same MCP JSON payloads as the Python patch
 * builders.
 *
 * <p>The golden file {@code patch_builder_parity.json} is generated by the Python script: {@code
 * metadata-ingestion/scripts/generate_patch_parity_golden.py}
 *
 * <p>If you change the patch builder output format, regenerate the golden file and update this
 * test.
 */
public class PatchBuilderParityTest {

  private static final ObjectMapper MAPPER = new ObjectMapper();
  private static final String DATASET_URN =
      "urn:li:dataset:(urn:li:dataPlatform:hive,SampleTable,PROD)";
  private static final String TYPE_URN = "urn:li:ownershipType:__system__technical_owner";
  private static final String ATTRIBUTION_SOURCE = "urn:li:dataHubAction:testSource";

  private JsonNode golden;

  @BeforeClass
  public void loadGolden() throws Exception {
    try (InputStream is =
        getClass().getClassLoader().getResourceAsStream("patch_builder_parity.json")) {
      assertNotNull(is, "patch_builder_parity.json not found on classpath");
      golden = MAPPER.readTree(is);
    }
  }

  private JsonNode buildAndParsePayload(MetadataChangeProposal mcp) throws Exception {
    byte[] bytes = mcp.getAspect().getValue().copyBytes();
    return MAPPER.readTree(bytes);
  }

  private void assertPayloadMatches(String goldenKey, MetadataChangeProposal mcp) throws Exception {
    JsonNode expected = golden.get(goldenKey);
    assertNotNull(expected, "Missing golden key: " + goldenKey);
    JsonNode actual = buildAndParsePayload(mcp);

    // Compare arrayPrimaryKeys exactly
    assertEquals(
        actual.get("arrayPrimaryKeys"),
        expected.get("arrayPrimaryKeys"),
        goldenKey + ": arrayPrimaryKeys mismatch");

    // Compare patch ops (op and path must match; value structure may differ for removes)
    JsonNode expectedPatch = expected.get("patch");
    JsonNode actualPatch = actual.get("patch");
    assertNotNull(actualPatch, goldenKey + ": missing patch array");
    assertEquals(actualPatch.size(), expectedPatch.size(), goldenKey + ": patch array size");

    for (int i = 0; i < expectedPatch.size(); i++) {
      JsonNode expectedOp = expectedPatch.get(i);
      JsonNode actualOp = actualPatch.get(i);
      assertEquals(
          actualOp.get("op").asText(),
          expectedOp.get("op").asText(),
          goldenKey + "[" + i + "]: op mismatch");
      assertEquals(
          actualOp.get("path").asText(),
          expectedOp.get("path").asText(),
          goldenKey + "[" + i + "]: path mismatch");
    }
  }

  // ---- Tags ----

  @Test
  public void testGlobalTagsAdd() throws Exception {
    MetadataChangeProposal mcp =
        new GlobalTagsPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .addTag(TagUrn.createFromString("urn:li:tag:testTag"), null)
            .build();
    assertPayloadMatches("globalTags_add", mcp);
  }

  @Test
  public void testGlobalTagsAddAttributed() throws Exception {
    MetadataChangeProposal mcp =
        new GlobalTagsPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .addTag(
                TagUrn.createFromString("urn:li:tag:testTag"),
                null,
                Urn.createFromString(ATTRIBUTION_SOURCE))
            .build();
    assertPayloadMatches("globalTags_add_attributed", mcp);
  }

  @Test
  public void testGlobalTagsAddWithContext() throws Exception {
    MetadataChangeProposal mcp =
        new GlobalTagsPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .addTag(TagUrn.createFromString("urn:li:tag:testTag"), "testContext")
            .build();
    assertPayloadMatches("globalTags_add_with_context", mcp);
  }

  @Test
  public void testGlobalTagsRemove() throws Exception {
    MetadataChangeProposal mcp =
        new GlobalTagsPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .removeTag(TagUrn.createFromString("urn:li:tag:testTag"))
            .build();
    assertPayloadMatches("globalTags_remove", mcp);
  }

  @Test
  public void testGlobalTagsRemoveAttributed() throws Exception {
    MetadataChangeProposal mcp =
        new GlobalTagsPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .removeTag(
                TagUrn.createFromString("urn:li:tag:testTag"),
                Urn.createFromString(ATTRIBUTION_SOURCE))
            .build();
    assertPayloadMatches("globalTags_remove_attributed", mcp);
  }

  // ---- Terms ----

  @Test
  public void testGlossaryTermsAdd() throws Exception {
    MetadataChangeProposal mcp =
        new GlossaryTermsPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .addTerm(GlossaryTermUrn.createFromString("urn:li:glossaryTerm:testTerm"), null)
            .build();
    assertPayloadMatches("glossaryTerms_add", mcp);
  }

  @Test
  public void testGlossaryTermsAddAttributed() throws Exception {
    MetadataChangeProposal mcp =
        new GlossaryTermsPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .addTerm(
                GlossaryTermUrn.createFromString("urn:li:glossaryTerm:testTerm"),
                null,
                Urn.createFromString(ATTRIBUTION_SOURCE))
            .build();
    assertPayloadMatches("glossaryTerms_add_attributed", mcp);
  }

  @Test
  public void testGlossaryTermsAddWithContext() throws Exception {
    MetadataChangeProposal mcp =
        new GlossaryTermsPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .addTerm(
                GlossaryTermUrn.createFromString("urn:li:glossaryTerm:testTerm"), "testContext")
            .build();
    assertPayloadMatches("glossaryTerms_add_with_context", mcp);
  }

  @Test
  public void testGlossaryTermsRemove() throws Exception {
    MetadataChangeProposal mcp =
        new GlossaryTermsPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .removeTerm(GlossaryTermUrn.createFromString("urn:li:glossaryTerm:testTerm"))
            .build();
    assertPayloadMatches("glossaryTerms_remove", mcp);
  }

  @Test
  public void testGlossaryTermsRemoveAttributed() throws Exception {
    MetadataChangeProposal mcp =
        new GlossaryTermsPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .removeTerm(
                GlossaryTermUrn.createFromString("urn:li:glossaryTerm:testTerm"),
                Urn.createFromString(ATTRIBUTION_SOURCE))
            .build();
    assertPayloadMatches("glossaryTerms_remove_attributed", mcp);
  }

  // ---- Ownership ----

  @Test
  public void testOwnershipAdd() throws Exception {
    MetadataChangeProposal mcp =
        new OwnershipPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .addOwner(Urn.createFromString("urn:li:corpuser:testUser"), OwnershipType.DATAOWNER)
            .build();
    assertPayloadMatches("ownership_add", mcp);
  }

  @Test
  public void testOwnershipAddAttributed() throws Exception {
    MetadataChangeProposal mcp =
        new OwnershipPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .addOwner(
                Urn.createFromString("urn:li:corpuser:testUser"),
                OwnershipType.DATAOWNER,
                null,
                Urn.createFromString(ATTRIBUTION_SOURCE))
            .build();
    assertPayloadMatches("ownership_add_attributed", mcp);
  }

  @Test
  public void testOwnershipRemoveOwner1() throws Exception {
    MetadataChangeProposal mcp =
        new OwnershipPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .removeOwner(Urn.createFromString("urn:li:corpuser:testUser"))
            .build();
    assertPayloadMatches("ownership_removeOwner_1", mcp);
  }

  @Test
  public void testOwnershipRemoveOwnershipType() throws Exception {
    MetadataChangeProposal mcp =
        new OwnershipPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .removeOwnershipType(
                Urn.createFromString("urn:li:corpuser:testUser"), OwnershipType.DATAOWNER)
            .build();
    assertPayloadMatches("ownership_removeOwnershipType", mcp);
  }

  @Test
  public void testOwnershipRemoveOwner3() throws Exception {
    // Remove by typeUrn only (no type enum filter). The backend expands this to all entries
    // for the given owner where typeUrn matches, regardless of the type enum.
    MetadataChangeProposal mcp =
        new OwnershipPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .removeOwner(
                Urn.createFromString("urn:li:corpuser:testUser"),
                OwnershipType.DATAOWNER,
                Urn.createFromString(TYPE_URN))
            .build();
    assertPayloadMatches("ownership_removeOwner_3", mcp);
  }

  @Test
  public void testOwnershipRemoveAttributed() throws Exception {
    MetadataChangeProposal mcp =
        new OwnershipPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .removeOwner(
                Urn.createFromString("urn:li:corpuser:testUser"),
                OwnershipType.DATAOWNER,
                Urn.createFromString(TYPE_URN),
                Urn.createFromString(ATTRIBUTION_SOURCE))
            .build();
    assertPayloadMatches("ownership_remove_attributed", mcp);
  }

  // ---- Documentation ----

  @Test
  public void testDocumentationAdd() throws Exception {
    MetadataChangeProposal mcp =
        new DocumentationPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .addDocumentation("Test documentation")
            .build();
    assertPayloadMatches("documentation_add", mcp);
  }

  @Test
  public void testDocumentationAddAttributed() throws Exception {
    MetadataChangeProposal mcp =
        new DocumentationPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .addDocumentation("Test documentation", Urn.createFromString(ATTRIBUTION_SOURCE))
            .build();
    assertPayloadMatches("documentation_add_attributed", mcp);
  }

  @Test
  public void testDocumentationRemove() throws Exception {
    MetadataChangeProposal mcp =
        new DocumentationPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .removeDocumentation()
            .build();
    assertPayloadMatches("documentation_remove", mcp);
  }

  @Test
  public void testDocumentationRemoveAttributed() throws Exception {
    MetadataChangeProposal mcp =
        new DocumentationPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .removeDocumentation(Urn.createFromString(ATTRIBUTION_SOURCE))
            .build();
    assertPayloadMatches("documentation_remove_attributed", mcp);
  }

  // ---- Structured Properties ----

  @Test
  public void testStructuredPropertiesAdd() throws Exception {
    MetadataChangeProposal mcp =
        new StructuredPropertiesPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .setStringProperty(
                Urn.createFromString("urn:li:structuredProperty:io.acryl.testProperty"),
                "testValue")
            .build();
    assertPayloadMatches("structuredProperties_add", mcp);
  }

  @Test
  public void testStructuredPropertiesAddAttributed() throws Exception {
    MetadataChangeProposal mcp =
        new StructuredPropertiesPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .setStringProperty(
                Urn.createFromString("urn:li:structuredProperty:io.acryl.testProperty"),
                "testValue",
                Urn.createFromString(ATTRIBUTION_SOURCE))
            .build();
    assertPayloadMatches("structuredProperties_add_attributed", mcp);
  }

  @Test
  public void testStructuredPropertiesRemoveAttributed() throws Exception {
    MetadataChangeProposal mcp =
        new StructuredPropertiesPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .removeProperty(
                Urn.createFromString("urn:li:structuredProperty:io.acryl.testProperty"),
                Urn.createFromString(ATTRIBUTION_SOURCE))
            .build();
    assertPayloadMatches("structuredProperties_remove_attributed", mcp);
  }

  @Test
  public void testStructuredPropertiesSetNumber() throws Exception {
    MetadataChangeProposal mcp =
        new StructuredPropertiesPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .setNumberProperty(
                Urn.createFromString("urn:li:structuredProperty:io.acryl.testProperty"), 42)
            .build();
    assertPayloadMatches("structuredProperties_setNumber", mcp);
  }

  @Test
  public void testStructuredPropertiesSetStringList() throws Exception {
    MetadataChangeProposal mcp =
        new StructuredPropertiesPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .setStringProperty(
                Urn.createFromString("urn:li:structuredProperty:io.acryl.testProperty"),
                List.of("value1", "value2"))
            .build();
    assertPayloadMatches("structuredProperties_setStringList", mcp);
  }

  @Test
  public void testStructuredPropertiesSetNumberList() throws Exception {
    MetadataChangeProposal mcp =
        new StructuredPropertiesPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .setNumberProperty(
                Urn.createFromString("urn:li:structuredProperty:io.acryl.testProperty"),
                List.of(42, 43))
            .build();
    assertPayloadMatches("structuredProperties_setNumberList", mcp);
  }

  @Test
  public void testStructuredPropertiesRemove() throws Exception {
    MetadataChangeProposal mcp =
        new StructuredPropertiesPatchBuilder()
            .urn(Urn.createFromString(DATASET_URN))
            .removeProperty(Urn.createFromString("urn:li:structuredProperty:io.acryl.testProperty"))
            .build();
    assertPayloadMatches("structuredProperties_remove", mcp);
  }
}
